### ISSUE TITLE
UI Overhaul: Add Dashboard and Metrics like Laravel Horizon

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler#100]
[Laravel Horizon](https://horizon.laravel.com/) offers some neat metrics on the performance of queues, including jobs and workers. It also provides a really great UI for both those metrics and other insights.

Screenshots from the [launch post](https://medium.com/@taylorotwell/introducing-laravel-horizon-4585f66e3e):

![Horizon Dashboard](https://cl.ly/2U43422g1q19/download/Image%202017-11-06%20at%2020.37.20.png)

![Horizon Current Workload](https://cl.ly/2g411k2o1S46/download/Image%202017-11-06%20at%2020.41.49.png)

![Horizon Metrics](https://cl.ly/3P1A2M16250R/download/Image%202017-11-06%20at%2020.40.42.png)

Similar UI elements could be added to Action Scheduler's Admin UI based on existing data. Doing so would provide both a handy overview and deeper insight into the status and performance of Action Scheduler that isn't available currently.

---

It also has a nice _Failed Job_ interface that would be worth sourcing some inspiration from.

![Horizon Failed Job Page](https://cl.ly/1m0W2M1B1W0O/download/Image%202017-11-06%20at%2020.41.54.png)

**Comment by cesar-prospress** [comment]
Their "failed" view is beautiful and useful.

**Comment by cesar-prospress** [comment]
@JPry I think @thenbrent meant to adds those views/metrics, not to include this library (which has a lot of deps)

**Comment by thenbrent** [comment]
@JPry yes @cesar-prospress's is right. I've just updated the description a little to avoid that ambiguity. 🙂

**Comment by thenbrent** [comment]
Closing this for now. I'd like to see this implemented, but it's not a priority for now so closing. We can reopen eventually if it makes sense to work on it.

**Comment by rrennick** [comment]
For reference, here is the current WooCommerce Admin dashboard

![WCA-dashboard](https://user-images.githubusercontent.com/343847/55797562-26490700-5aa3-11e9-9f26-4eeb3b22efec.png)

I am working on https://github.com/woocommerce/woocommerce-admin/issues/1965 by creating https://github.com/Prospress/action-scheduler-admin with the plan to eventually roll the dashboard into Action Scheduler. I'm re-opening this and self assigning.

**Comment by rrennick** [comment]
Ref https://github.com/Prospress/action-scheduler-admin/pull/6

**Comment by thenbrent** [comment]
Closing this in favour of https://github.com/Prospress/action-scheduler-admin. We can open a new issue if/when it comes time to merge that feature plugin into AS core.
