### ISSUE TITLE
unable to access original exception in hook action_scheduler_failed_execution

### ISSUE THREAD

**Issue by sweber83** [Prospress/action-scheduler#1003]
I have a situation where I need to look at the type of exception, which arrives in the `action_scheduler_failed_execution` hook.
The action scheduler catches the original exception and throws a new one here: https://github.com/woocommerce/action-scheduler/blame/754dc005b82a858c6398f1d0799d41771e2f5779/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php#L94
I expected to be able to access the original exception via `$e->getPrevious()`, but that does not work, because instead of `$e` the new exception gets passed `$e->getPrevious()` as the third parameter, which in my case returns null.

Is this behavior intended?
If it is, is there another way to access the original exception?

**Comment by barryhughes** [comment]
> Is this behavior intended?

An oversight, I think: we should be passing in `$e`, just as you suggest. I'll mark this as a bug ... and if you are interested in submitting a PR please feel free (otherwise we'll try to address as soon as we can).

**Comment by sweber83** [comment]
@barryhughes 
Here you go
https://github.com/woocommerce/action-scheduler/pull/1007
