### ISSUE TITLE
WordPress.org plugin review warning/issue about internationalization

### ISSUE THREAD

**Issue by remcotolsma** [Prospress/action-scheduler#1011]
We received the following feedback from the WordPress.org plugin review team (plugins@wordpress.org) about a new plugin in which we included this library:

> Hi!
> 
> Good work with the corrections!
> 
> ## Internationalization: Don't use variables or defines as text, context or text domain parameters.
> 
> Please **do not use variable names** for the text, context or text domain portion of a gettext function, all of them NEED to be strings, otherwise they could not be read by the translation parser.
> 
> For example, this is a bad call: `esc_html__( 'Translate me.' , $plugin_slug );` , the fix here would be like this `esc_html__( 'Translate me.' , 'plugin-slug' );`
> 
> This is also wrong: `esc_html__( 'Your city is ' . $city . '.' , 'plugin-slug' );` , the fix here would be using a placeholder and change it later using `printf` , like this:
> 
> ```php
> printf(
> 
>       /* translators: %s: Name of a city */
> 
>       esc_html__( 'Your city is %s.', 'plugin-slug' ),
> 
>       esc_html($city)
> 
> );
> ```
> 
> Also have in mind that your text domain has to be the same as your plugin's slug (also known as permalink).
> 
> The text domain also needs to be added to the plugin header. WordPress uses it to internationalize your plugin meta-data even when the plugin is disabled.
> 
> You can read https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains for more information.
> 
> Example(s) from your plugin:
> 
> ```
> packages/woocommerce/action-scheduler/classes/ActionScheduler_ListTable.php:237 _n(self::$time_periods[$time_period_index]['names'][0], self::$time_periods[$time_period_index]['names'][1], $periods_in_interval, 'pronamic-pay-with-mollie-for-woocommerce');
> ```
> 
> --
> WordPress Plugin Review Team | [plugins@wordpress.org](mailto:plugins@wordpress.org)
> https://make.wordpress.org/plugins/
> https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/

We don't think this is actually an issue, but for future plugin reviews it might be useful to address this.

https://github.com/woocommerce/action-scheduler/blob/10c96381d2ae6162654b370cbb944ec6bb42dbc8/classes/ActionScheduler_ListTable.php#L237

https://github.com/woocommerce/action-scheduler/blob/10c96381d2ae6162654b370cbb944ec6bb42dbc8/classes/ActionScheduler_ListTable.php#L140-L176

**Comment by jorgeatorres** [comment]
Hi @remcotolsma!

Thanks for the report. We reviewed the code and we were in fact using `_n_noop()` (as we should) but then passed that string to `_n()` instead of `translate_nooped_plural()` as we should have. We'll take care of this in a future release. Thanks again!

(Context: p1700131030038709-slack-C0E1AV8T0)

**Comment by remcotolsma** [comment]
We submitted a new plugin a few weeks ago via https://wordpress.org/plugins/developers/add/ and again received the following feedback from the WordPress.org plugin review team:

> **## Internationalization: Don't use variables or defines as text, context or text domain parameters.**
> 
> Please **do not use variable names** for the text, context or text domain portion of a `gettext` function, all of them NEED to be strings, otherwise they could not be read by the translation parser.
> 
> For example, this is a bad call: `esc_html__( 'Translate me.' , $plugin_slug );`, the fix here would be like this `esc_html__( 'Translate me.' , 'plugin-slug' );`
> 
> This is also wrong: `esc_html__( 'Your city is ' . $city . '.' , 'plugin-slug' );`, the fix here would be using a placeholder and change it later using printf, like this:
> 
> ```php
> printf(
>        /* translators: %s: Name of a city */
>        esc_html__( 'Your city is %s.', 'plugin-slug' ),
>        esc_html($city)
>  );
> ```
> 
> Also have in mind that your text domain has to be the same as your plugin's slug (also known as permalink).
> 
> The text domain also needs to be added to the plugin header. WordPress uses it to internationalize your plugin meta-data even when the plugin is disabled.
> 
> You can read https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains for more information.
> 
> Example(s) from your plugin:
> 
> ```
> pronamic-pay-with-mollie-for-ninja-forms/packages/woocommerce/action-scheduler/classes/ActionScheduler_ListTable.php:237 _n(self::$time_periods[$time_period_index]['names'][0], self::$time_periods[$time_period_index]['names'][1], $periods_in_interval, 'pronamic-pay-with-mollie-for-ninja-forms');
> ```

Perhaps it would be good to give this issue a little more priority because it is a recurring problem and the WordPress.org plugin review team is already very busy?

Will it help if I submit a PR to resolve this issue, or would the maintainers of this library prefer to handle this themselves?

**Comment by jorgeatorres** [comment]
Hi @remcotolsma!

Sorry we haven't been able to prioritize work on this and weren't aware this is becoming a blocker for approval of plugins on the .org directory.
If you're willing to submit a PR for this issue, we would be more than happy to review it!

**Comment by remcotolsma** [comment]
> If you're willing to submit a PR for this issue, we would be more than happy to review it!

Great, PR is ready:

- https://github.com/woocommerce/action-scheduler/pull/1026

**Comment by lukecarbis** [comment]
Hi – I'm a member of the plugin review team. I just wanted to confirm that this is, in fact, holding up plugin review. We really appreciate your prompt attention to the issue. Thank you!

**Comment by remcotolsma** [comment]
Fixed in https://github.com/woocommerce/action-scheduler/commit/750ad4e4b94900e0c844003ed9c559b869aff87e.

**Comment by nigeljamesstevenson** [comment]
Thanks @remcotolsma !

@lukecarbis, just a note that we aim to release the new version of Action Scheduler by Wednesday - thanks!

**Comment by remcotolsma** [comment]
Thanks @nigeljamesstevenson, the WordPress.org plugin review team found some other 'issues':

- https://github.com/woocommerce/action-scheduler/issues/1027
