### ISSUE TITLE
Suppress notices

### ISSUE THREAD

**Issue by riverofjanuary** [Prospress/action-scheduler#1014]
Hi there, a plugin we are using has as part of its config Action Scheduler and through some issue on the server we are constantly getting "Action Scheduler: 1 past-due action found; something may be wrong. Read documentation »" notifications. How do we suppress these?

**Comment by barryhughes** [comment]
Is there any more information you can provide? I wonder if, for example, a plugin is consistently scheduling actions in the past, something like the following, as a means of prioritizing them ahead of other work?

```php
as_schedule_single_action( time() - 10, 'callback' );
```

In any case, it should be possible to suppress this with a small snippet like the following:

```php
add_filter( 'action_scheduler_pastdue_actions_check_pre', '__return_true' );
```

Does that help?

**Comment by riverofjanuary** [comment]
Thanks for that filter, that helps. The plugin is a 3rd party (I'm not sure about the value of naming them here) who is including your library, and I don't really know what exactly they're using the chron hooks for exactly. The hook in question was `action_scheduler/migration_hook` and it keeps popping up. I would ignore it except for the enduser of this site might mistake this (nondismissable) alert as something bad. Thank you for the filter

**Comment by barryhughes** [comment]
Thanks. In that case, I think this problem may actually be with Action Scheduler:

https://github.com/woocommerce/action-scheduler/issues/990

However, I'll close this one since you have a temporary solution.
