### ISSUE TITLE
Tasks stuck in-progress and then failed 

### ISSUE THREAD

**Issue by majidempire** [Prospress/action-scheduler#1018]
Hey,

I've noticed an issue with running tasks. I use Automatewoo to execute mass tasks, and when, for example, I have 10,000 tasks to run using this plugin or any other plugin, after a while, one task gets stuck in "In-progress" mode, as you can see in the picture below, for about 10-15 minutes. Then, it fails, and in the failed tab, I see a log like this:

Before getting stuck in this situation, I observe that the task runs very quickly, probably at the default of 25 tasks per run, but suddenly it gets stuck. It's quite weird.

`2023-12-16 00:26:37 +0000
    action created
    2023-12-16 00:26:37 +0000
    action started via Async Request
    2023-12-16 00:32:00 +0000
    action marked as failed after 300 seconds. Unknown error occurred. Check server, PHP and database error logs to diagnose cause.`

<img width="1231" alt="fd" src="https://github.com/woocommerce/action-scheduler/assets/5389240/e5fc2a89-6d97-45dd-acd6-03e11dc92457">

and here is debug log php
`WordPress database error Commands out of sync; you can't run this command now for query SELECT option_value FROM wp_options WHERE option_name = 'action_scheduler_lock_async-request-runner' made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_OptionLock->set, ActionScheduler_OptionLock->get_existing_lock, QM_DB->query`

And as I checked in same time in Mysql log is:
`2023-12-17 11:19:04 85589 [Warning] Aborted connection 85589 to db: 'db' user: 'user' host: 'localhost' (Got an error writing communication packets)`

**Comment by shaybanshee** [comment]
Related to this [forum post](https://wordpress.org/support/topic/stuck-in-progress-2/). While issue resolved for user; please still investigated during bug sweep!

**Comment by jorgeatorres** [comment]
Hi @majidempire!

Thanks for reaching out. Based on the forum post, it seems you were able to work around this by using WP-CLI. This makes us think that there might be something environmental going on with your site. WP-CLI provides a slightly more controlled environment (and more performant) than "regular" WP and WP-Cron in particular.

It's not clear to us if you were able to perform a proper conflict test on your site or if you're able to consistently reproduce with most (or all) plugins disabled. It might definitely be related to the sheer number of tasks that you are running, and WP-CLI is probably the way to go, but if you could provide any other details we would be more than happy to investigate a bit further.

**Comment by majidempire** [comment]
Hello,

Currently, I'm unable to conduct a conflict test on the website I'm working on due to it being a development site, which restricts such actions. However, we do have an identical environment website where I intend to conduct an investigation. At this point, I cannot conclusively determine if the issue lies with actionscheduler.

It's possible that it could be an issue related to the Automatewoo plugin. This plugin features a job exception function triggered when a specified number of failures occur (although the specific count is unknown, perhaps around 8). Consequently, other tasks with the same parameters remain stuck in progress until they eventually fail after some time.

**Comment by lsinger** [comment]
Thank you, @majidempire! I'll close the issue for the time being -- once you have new information that you can share, please feel free to reopen it or ping us here again.
