### ISSUE TITLE
Need to add a hook when ever new action is registered

### ISSUE THREAD

**Issue by Hafiz-Ahmed0** [Prospress/action-scheduler#1020]
I am using woo and action schedulers. I am manually renewing subscriptions and I need to call third party service when a new action schedule is registered ( function needs to be called on action schedule success and need action schedule data in it ). Is there any hook of action schedule plugin that I can use for that.

**Comment by lsinger** [comment]
Hello, @Hafiz-Ahmed0! We don't have a good overview of the provided hooks, unfortunately. However, searching the code base for `do_action( '` yields [a few interesting results](https://github.com/search?q=repo%3Awoocommerce%2Faction-scheduler%20%22do_action(%20%27%22&type=code). 

Do you need to run when the action has been scheduled or when it has been executed? There certainly is a hook for after execution: 

`do_action( 'action_scheduler_after_execute', $action_id, $action, $context );`

This one gets called when the action is being marked as complete: 

`do_action( 'action_scheduler_completed_action', $action_id );`

There's also a hook that gets called when an action has been saved to the database:

`do_action( 'action_scheduler_stored_action', $action_id );`

Does one of these do what you're looking for?

**Comment by Hafiz-Ahmed0** [comment]
Thank you @lsinger, I was looking for the hook 'action_scheduler_stored_action'.
