### ISSUE TITLE
Hybrid store does not support unique actions

### ISSUE THREAD

**Issue by rrennick** [Prospress/action-scheduler#1023]
The action scheduler [migration gets re-enabled](https://github.com/woocommerce/action-scheduler/blob/trunk/classes/ActionScheduler_DataController.php#L169) every time a plugin is deactivated. In turn this switches AS to the hybrid data store which does not support unique actions.

I have a dev install that only runs AS actions through CLI that added ~1K copies of a unique action in a couple hours.

1- It should be safe to remove the code that re-enables the hybrid store as the DBStore has been default for almost 4 years.
2- The Hybrid store should support unique actions primarily for development/staging installs

**Comment by barryhughes** [comment]
> It should be safe to remove the code that re-enables the hybrid store as the DBStore has been default for almost 4 years.

For whenever we take this up: let's be careful on this point. Though it was a couple of years back, we did see a relatively popular third party plugin still shipping 2.x (and there could definitely be unmaintained custom plugins in the same boat).

Definitely great if we can do it safely.

**Comment by barryhughes** [comment]
I think #1039 is a satisfactory solution for this problem. The post store is generally not used, and unless we decide to retain it as a backup for other problems (like missing tables [[1]](https://github.com/woocommerce/action-scheduler/issues/1059) [[2]](https://github.com/woocommerce/action-scheduler/issues/973) [[3]](https://github.com/woocommerce/action-scheduler/issues/1032)) then I don't think it's worth investing too much more time into the provision of full-fledged unique actions.
