### ISSUE TITLE
Race condition when deleting old actions from multiple processes

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler#103]
If more than one queue is running at the same time, there is potential for a race condition when [deleting old actions](https://github.com/Prospress/action-scheduler/blob/6168e5f4c95a9b25fadfc996a49b780641d207c9/classes/ActionScheduler_QueueCleaner.php#L17-L31), because we don't "lock" actions for deletion.

When this occurs, the `ActionScheduler_Store::delete_action()` method can throw an unhandled `InvalidArgumentException`, because in the time between when `ActionScheduler_QueueCleaner::delete_old_actions()` calls `ActionScheduler_Store::query_actions()` and `ActionScheduler_Store::delete_action()`, the other queue may have deleted the action, meaning the ID of the action still exists in the `$actions_to_delete` array in `ActionScheduler_QueueCleaner::delete_old_actions()`, but the `get_post()` call in `ActionScheduler_wpPostStore::delete_action()` will not instantiate it, because it's since been deleted, meaning `empty($post)` will evaluate `true`.

There are a few possible approaches to fix this:

1. claim actions before deleting them. This is the most complex. The added complexity isn't really required as it should be sufficient to just avoid deleting already deleted actions.
1. check if `ActionScheduler_Store::fetch_action()` returns a valid action before calling `ActionScheduler_Store::delete_action()`. This has minor perf issues, as it requires instantiating the action twice, and also won't always fix the issue, because there are still microseconds between when `ActionScheduler_Store::fetch_action()` will be called by `ActionScheduler_QueueCleaner::delete_old_actions()` and when `get_post()` will be called in `ActionScheduler_Store::delete_action()`
1. catch the `InvalidArgumentException` exception and ignore it (perhaps with some type of logging about the issue?). This will guarantee this race condition is ignored, but it may catch other exceptions for new conditions, so it will need special handling.

Related links:

* [Original Slack thread](https://prospress.slack.com/archives/C74DUNZQ8/p1515778094000388)
* [Follow-up Slack thread](https://prospress.slack.com/archives/C03A22H08/p1516121271000709)
* [Support ticket](https://secure.helpscout.net/conversation/506206000/4119?folderId=1524429)

**Comment by unfulvio** [comment]
Following this as it may affect Memberships, especially when Follow Up Emails is used (they trigger events around the same time).

**Comment by thenbrent** [comment]
@unfulvio the fix won’t have any special impact on other plugins using it, or sites with multiple plugins using it. The issue is more about multiple threads/processes/queues running at the same time. Those queues could easily all be from one plugin.
