### ISSUE TITLE
Action not scheduled, no error logged

### ISSUE THREAD

**Issue by Dekadinious** [Prospress/action-scheduler#1031]
I am trying to debug something that has started happening for apparently no reason, on code that has worked before.

I'll just post the whole function for clarity:

```
function fl_featured_products_save( $post_id ) {

	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
		return;
	}

	if ( ! isset( $_POST['post_type'] ) || $_POST['post_type'] !== 'product' ) {
		return;
	}

	$featured_products_option = get_option( '_fl_featured_products' ) ?: array();
	$status                   = $_POST['featured_products'] ?? 0;

	if ( $status == 1 ) {
		$featured_products_option[] = $post_id;
	} elseif ( in_array( $post_id, $featured_products_option ) ) {
		$featured_products_option = array_diff( $featured_products_option, array( $post_id ) );
	}

	update_option( '_fl_featured_products', $featured_products_option );

	$last_date = $_POST['featured_products_date'] ?? null;

	write_log( 'Featured date: ' . $last_date );
	write_log( 'Status: ' . $status );
	write_log( 'Post ID: ' . $post_id );

	if ( $last_date && $status == 1 ) {
		as_unschedule_action( 'fl_featured_product_remove', array( $post_id ), 'fl' );

		update_post_meta( $post_id, '_fl_featured_last_date', $last_date );

		$timestamp = strtotime( $last_date . ' +1 day ' . wp_timezone_string() );
		$action_id = as_schedule_single_action( $timestamp, 'fl_featured_product_remove', array( $post_id ), 'fl', true );

		write_log( 'Scheduled action ID: ' . $action_id );
	} else {
		delete_post_meta( $post_id, '_fl_featured_last_date' );
		as_unschedule_action( 'fl_featured_product_remove', array( $post_id ), 'fl' );
	}
}
add_action( 'save_post', 'fl_featured_products_save' );
```

I have added some log statements. The write_log function is just a wrapper for error_log with some print_r handling etc. These are my logs when saving the product:

```
[22-Feb-2024 14:35:22 UTC] Featured date: 2024-02-23
[22-Feb-2024 14:35:22 UTC] Status: 1
[22-Feb-2024 14:35:22 UTC] Post ID: 683403
[22-Feb-2024 14:35:22 UTC] Scheduled action ID: 0
```
We have a valid date, status, and post ID, but `as_schedule_single_action()` returns 0. I can't find anything in the logs, even with the documentation stating an error will be logged if the scheduled action is 0. Debug-logging is confirmed on. There is also nothing in the logs on the WooCommerce Status-page.

I have tried commenting out the unscheduling function because I thought about race conditions, but it had no effect. Also, I was wondering about something slightly related. When passing true as the unique-parameter, what is expected to happen? That is poorly documented. Will the new action overwrite the old one, or will the old one stay and the new one fail to schedule?

I'm using version 3.7.2.

How can I troubleshoot this further?

**Comment by Dekadinious** [comment]
Also, to add, we have one "fl_featured_product_remove" action pending. This action is for another post_id.

**Comment by Konamiman** [comment]
Hi @Dekadinious. It's true that the meaning of the `$unique` argument isn't properly documented, apologies for that. What `$unique` does is the following: "If an action with the same combination of hook name and group is already pending or running, do nothing and return zero". So this is what is likely happening to you.

Yes, you are using `as_unschedule_action` before `as_schedule_single_action`. But this will remove _only_ the next scheduled action; if there are more actions scheduled with the same hook (maybe you created them while testing?) they won't be removed.

My suggestion is to use `as_unschedule_all_actions` instead, this will effectively remove all the actions for the hook and group. Please try that and get back to us wit the results.

**Comment by Dekadinious** [comment]
I managed to find out by digging through the code. I also submitted a PR 😊

I initially thought the arguments were part of what made it unique. As you can see I am trying to schedule actions that should be unique per post ID. I removed the unique parameter and now it works 👍

One question though: Will the removal of action make sure to only remove actions where the arguments also match?

**Comment by Konamiman** [comment]
@Dekadinious Awesome, thanks for your contribution!

As for your question: I guess you are referring to `as_unschedule_action` and `as_unschedule_all_actions`. These will only remove actions with matching arguments provided that a non-empty list of arguments is provided to the functions.

**Comment by Dekadinious** [comment]
Thank you! @Konamiman 

Closing this now :)
