### ISSUE TITLE
Have Past Due Items but CLI command won't pick them up

### ISSUE THREAD

**Issue by its-leofisher** [Prospress/action-scheduler#1041]
Action Scheduler has past due actions and when I run the action-scheduler command on the server to process them it says there are none in the batch to process.  It also gets stuck on some of these and I have to delete them as the jobs don't self recover.

Items that are past due:
<img width="1078" alt="image" src="https://github.com/woocommerce/action-scheduler/assets/40841827/5b473379-37ba-4ad5-b9c3-eb47fc9116e7">

Command return on server:
<img width="1249" alt="image" src="https://github.com/woocommerce/action-scheduler/assets/40841827/fc12c858-a78f-4089-85c7-547dea62b3d7">

When I process them manually they run just great, and no errors in debug.log as well

**Comment by vedanshujain** [comment]
Hey @its-leofisher , that's interesting, are there more details about why this isn't picked? are you able to reproduce this consistently?

**Comment by its-leofisher** [comment]
> Hey @its-leofisher , that's interesting, are there more details about why this isn't picked? are you able to reproduce this consistently? 

There is a long time timeout set for 300s, but after it hits that limit, it keeps the process occupied until it is manually deleted.

Unable to reproduce, it typically gets stuck during our subscription renewals on the 1st and the 15th, the last round of jobs stuck were orders with stripe as the payment.

**Comment by jorgeatorres** [comment]
@its-leofisher: Thanks for getting back to us. We don't have much to investigate at this point, but can you confirm if this is only happening for Subscriptions-related hooks (i.e `woocommerce_scheduled_subscription_payment`) or does this happen with A-S actions invoking other hooks?

**Comment by barryhughes** [comment]
It doesn't feel like we have enough information to take this further, so I'll go ahead and close. Of course, it can easily be re-opened (or a fresh issue with more information can be logged).
