### ISSUE TITLE
Could I pause scheduled actions?

### ISSUE THREAD

**Issue by NicolaModugno** [Prospress/action-scheduler#1046]
Hello, everyone,
I am working on a data import system that has to work constantly (in loop) to update local data from a remote source.
On some occasions the amount of data to be imported is large and I have been wondering how to use AS to handle it.

Is there any way to "pause" the execution of certain actions?

Let us assume that we are downloading a large dataset to import: I could schedule all the actions needed to import the data straight away (as is logical), but in this way, if needed, I do not have the option of pausing the import (pausing specific scheduled actions or all actions by group name) to restart it later. The only alternative would be to create a few actions at a time after checking whether the import can continue, but then the management would be more complex and the procedure less efficient in general.

What do you think?
I look forward to your considerations and thank you for this fantastic tool!

**Comment by barryhughes** [comment]
That's an interesting use case. Unfortunately, though, it's not something that's directly supported.

> The only alternative would be to create a few actions at a time after checking whether the import can continue, but then the management would be more complex and the procedure less efficient in general.

The above note makes me think this option may not be attractive to you, but my first thought was that you could use a recurring action and, if the pause is in effect, it would simply exit early without doing anything. To do this, you *might* need to store any data the import job needs outside of the action arguments.


```php
$action_ids = ActionScheduler::store()->query_actions( $criteria );
```

☝🏼 Another option is using something like the above to fetch the actions you are interested in, and then simulate a pause by re-scheduling them into the far future, or even cancelling them, *or* perhaps apply a custom status of some kind.

Cancellation is already supported via `as_unschedule_action()`. However, the other options I mentioned would require custom code (and, of course, you'd probably need to write some corresponding code to un-pause). This is probably the less efficient strategy.

**Comment by barryhughes** [comment]
It doesn't seem like there are any further questions here, so will go ahead and close the issue.

**Comment by NicolaModugno** [comment]
@barryhughes sorry for the delay.

I chose to go the custom state route for scheduled actions.
The problem, however, is that I cannot find any filters to customise the display of the actions in the backend (either at the level of table filters for the state of actions, or to specify the custom status label in the table).
Would you have any suggestions?

Thanks!

**Comment by barryhughes** [comment]
The list table found at **Tools ‣ Scheduled Actions** does seem to be a little lacking in hooks to allow easier customization. Definitely feel free to log a new issue for this or, if you wished to submit a PR, we'd also be happy to take a look at that.
