### ISSUE TITLE
WP_CLI Hook filter not supporting "/"

### ISSUE THREAD

**Issue by JUVOJustin** [Prospress/action-scheduler#1063]
I love using the WP_CLI to prioritize executions of special hooks like webhooks. I create a library to import massive csv files that are automatically split in chunks. To prioritize this import i would love to add a cron that runs every minute and only processes jobs ob this import. 

The hook name looks like this: `SW/Sync/Amazon/Inventory/process_chunk`

The CLI always finishes immediately since it cannot find any jobs. Using the UI as well as the CLI without any filters applied works flawless.

I think there might be a bug how the CLI´s hook filter values are passed to the DB query.

**Comment by barryhughes** [comment]
@JUVOJustin would you mind providing some steps to replicate, so we can be sure we understand the nature of the bug? To give a sense of what I tried already, I created the following mu-plugin:

```php
add_action( 'action_scheduler_init', function () {
	as_schedule_single_action( time(), 'foo/bar' );
} );

add_action( 'foo/bar', function () {
	! defined( WP_CLI::class ) or WP_CLI::line( 'Hello' );
} );

add_action( 'bar/baz', function () {
	! defined( WP_CLI::class ) or WP_CLI::line( 'Will not be echoed' );
} );
```

Then, on the command line, I ran:

```
wp action-scheduler run --hooks=foo/bar --force
```

This worked, and I could tell by the presence of `Hello` in the output that our callback was invoked (depending on how many other queue runners are present, you may need to run a few times to see this).

**Comment by JUVOJustin** [comment]
@barryhughes it either was fixed previously or i wasted all of our time. If the later is the case, i am really sorry.

Currently, i cannot reproduce the issue. I used the exact same project (though with updated deps).

**Comment by barryhughes** [comment]
No problem whatsoever, happy to hear it is no longer a problem. That said, if it does surface again, or you find the conditions needed to replicate it, please just let us know and we'll take a fresh look.
