### ISSUE TITLE
WordPress.org plugin review warnings/issues 🔁 3️⃣

### ISSUE THREAD

**Issue by remcotolsma** [Prospress/action-scheduler#1068]
This is a follow-up of the following issues:

- https://github.com/woocommerce/action-scheduler/issues/1027
- https://github.com/woocommerce/action-scheduler/issues/1011

---

We received some additional feedback from the WordPress.org plugin review team:

> **## Variables and options must be escaped when echo'd**
> 
> Much related to sanitizing everything, all variables that are echoed need to be escaped when they're echoed, so it can't hijack users or (worse) admin screens. There are many esc_*() functions you can use to make sure you don't show people the wrong data, as well as some that will allow you to echo HTML safely.
> 
> At this time, we ask you escape **all $-variables, options, and any sort of generated data when it is being echoed**. That means you should not be escaping when you build a variable, but when you output it at the end. We call this 'escaping late.'
> 
> Besides protecting yourself from a possible XSS vulnerability, escaping late makes sure that you're keeping the future you safe. While today your code may be only outputted hardcoded content, that may not be true in the future. By taking the time to properly escape **when** you echo, you prevent a mistake in the future from becoming a critical security issue.
> 
> This remains true of options you've saved to the database. Even if you've properly sanitized when you saved, the tools for sanitizing and escaping aren't interchangeable. Sanitizing makes sure it's safe for processing and storing in the database. Escaping makes it safe to output.
> 
> Also keep in mind that sometimes a function is echoing when it should really be returning content instead. This is a common mistake when it comes to returning JSON encoded content. Very rarely is that actually something you should be echoing at all. Echoing is because it needs to be on the screen, read by a human. Returning (which is what you would do with an API) can be json encoded, though remember to **sanitize** when you save to that json object!
> 
> There are a number of options to secure all types of content (html, email, etc). Yes, even HTML needs to be properly escaped.
> 
> https://developer.wordpress.org/apis/security/escaping/
> 
> Remember: You must use the most appropriate functions for the context. There is pretty much an option for everything you could echo. Even echoing HTML safely.
> 
> Example(s) from your plugin:
> 
> ```
> packages/woocommerce/action-scheduler/classes/ActionScheduler_AdminView.php:196 _n(
> '<strong>Action Scheduler:</strong> %1$d <a href="%2$s">past-due action</a> found; something may be wrong. <a href="https://actionscheduler.org/faq/#my-site-has-past-due-actions-what-can-i-do" target="_blank">Read documentation &raquo;</a>',
> '<strong>Action Scheduler:</strong> %1$d <a href="%2$s">past-due actions</a> found; something may be wrong. <a href="https://actionscheduler.org/faq/#my-site-has-past-due-actions-what-can-i-do" target="_blank">Read documentation &raquo;</a>',
> $num_pastdue_actions,
> 'text-domain'
> ),
> packages/woocommerce/action-scheduler/classes/abstracts/ActionScheduler_Abstract_ListTable.php:726 echo implode( " | \n", $status_list_items ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
>  -----> echo implode(" | \n", $status_list_items);
> packages/woocommerce/action-scheduler/classes/abstracts/ActionScheduler_Abstract_ListTable.php:748 echo $this->search_box( $this->get_search_box_button_text(), 'plugin' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
> ```

---

> **## Unsafe SQL calls**
> 
> When making database calls, it's highly important to protect your code from SQL injection vulnerabilities. You need to update your code to use wpdb calls and prepare() with your queries to protect them.
> 
> Please review the following:
> 
> - https://developer.wordpress.org/reference/classes/wpdb/#protect-queries-against-sql-injection-attacks
> - https://codex.wordpress.org/Data_Validation#Database
> - https://make.wordpress.org/core/2012/12/12/php-warning-missing-argument-2-for-wpdb-prepare/
> - https://ottopress.com/2013/better-know-a-vulnerability-sql-injection/
> 
> Example(s) from your plugin:
> 
> ```
> packages/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:928 $wpdb->prepare(
> "SELECT {$column_name} FROM {$wpdb->posts} WHERE ID=%d AND post_type=%s", // phpcs:ignore
> $action_id,
> self::POST_TYPE
> )
> packages/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:927 return $wpdb->get_var(
> $wpdb->prepare(
> "SELECT {$column_name} FROM {$wpdb->posts} WHERE ID=%d AND post_type=%s", // phpcs:ignore
> $action_id,
> self::POST_TYPE
> )
> );
> # There is a call to a wpdb::prepare() function, that's correct.
> # You cannot add variables like "$column_name" directly to the SQL query.
> # Using wpdb::prepare($query, $args) you will need to include placeholders for each variable within the query and include the variables in the second parameter.
> 
> 
> packages/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:666 $where    = "WHERE post_type = %s AND post_status = %s AND post_password = ''";
> packages/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:684 $where   .= ' AND post_date_gmt <= %s';
> packages/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:682 $where .= ' AND ID IN (' . join( ',', $ids ) . ')';
> packages/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:672 $where       .= ' AND post_title IN (' . join( ', ', $placeholders ) . ')';
> packages/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:658 $update = "UPDATE {$wpdb->posts} SET post_password = %s, post_modified_gmt = %s, post_modified = %s";
> packages/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:693 $rows_affected = $wpdb->query( $wpdb->prepare( "{$update} {$where} {$order}", $params ) ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare
>  -----> $wpdb->query($wpdb->prepare("{$update} {$where} {$order}", $params))
> # There is a call to a wpdb::prepare() function, that's correct.
> # You cannot add calls like "join(', ', $placeholders)" directly to the SQL query.
> # Using wpdb::prepare($query, $args) you will need to include placeholders for each variable within the query and include the variables in the second parameter.
> # You cannot add calls like "join(',', $ids)" directly to the SQL query.
> ```
> 
> ... out of a total of 25 incidences.
> 
> **Note**: Passing individual values to wpdb::prepare using placeholders is fairly straightforward, but what if we need to pass an array of values instead?
> 
> You'll need to create a placeholder for each item of the array and pass all the corresponding values to those placeholders, this seems tricky, but here is a snippet to do so.
> 
> ```
> $wordcamp_id_placeholders = implode( ', ', array_fill( 0, count( $wordcamp_ids ), '%d' ) ); 
>     
> $prepare_values = array_merge( array( $new_status ), $wordcamp_ids ); 
>     
> 
>     
> $wpdb->query( $wpdb->prepare( "
>             UPDATE `$table_name`
>             SET `post_status` = %s
>             WHERE ID IN ( $wordcamp_id_placeholders )",
>             $prepare_values
>         ) );
> ```
> 
> There is a core ticket that could make this easier in the future: https://core.trac.wordpress.org/ticket/54042
> 
> Example(s) from your plugin:
> 
> ```
> packages/woocommerce/action-scheduler/classes/abstracts/ActionScheduler_Abstract_ListTable.php:488 $columns = '`' . implode( '`, `', $this->get_table_columns() ) . '`';
> packages/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php:805 $action_id_string = implode( ',', array_map( 'intval', $action_ids ) );
> ```

**Comment by barryhughes** [comment]
Thanks, @remcotolsma. Closing this and, in a sense, 'merging' it with existing issue https://github.com/woocommerce/action-scheduler/issues/971, as the outcomes are very similar.
