### ISSUE TITLE
Handle hosts with hard timeouts better

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler#108]
Some hosts, like [WP Engine](https://wpengine.com/support/troubleshooting-502-error/), enforce hard timeouts:

> On WP Engine we have a 60-second timeout for long processes. So if a PHP worker has to process a request for 60 seconds or more, that request will be rejected and will produce the 502 error.
> ...
> The 60-second timeout is in place to ensure our servers are able to serve the maximum amount of concurrent requests. Without a timeout in place, we’ve seen requests take minutes to even hours to complete. With the continued performance of your site in mind, we will not be able to disable the timeout. This timeout is programmed at the root of our platform. It is in place to ensure optimal server health, speed, and uptime.

Sometimes, these timeouts are not only outside of PHP's control, they can even be outside of PHP's access (e.g. `ini_get( 'max_execution_time' )` deceptively returns something like 300 when the time limit is actually 60).

This can lead to Action Scheduler being terminated part-way through executing an action, and very little information to go on to explain why that happened (it's almost always just the `action timed out after 300 seconds` log entry once the action is cleaned up later).

### Possible Solution

I _think_ the only way to handle this is to hardcode time limits on `ActionScheduler_QueueRunner::do_batch()` and avoid processing further actions if current script exection is approaching that time limit.

Specifically, at the start of `ActionScheduler_QueueRunner::do_batch()` :

1. set an `$max_execution_time` value which is based on known host hard time limits when constants like `WPENGINE_ACCOUNT`, or `PANTHEON_ENVIRONMENT` are seen, or otherwise, falls back to  `ini_get( 'max_execution_time' )`
1. start a stopwatch - for hosts that use a "wallclock" like WP ENgine, we'll need to use `$time_elapsed = microtime()`, because we care about real time, not CPU time here. For others, like Pantheon, which use PHP's execution time, we should use `getrusage()`.
1. at the beginning of each interaction of `$claim->get_actions()`:
    1. find `$time_elapsed / $processed_actions` to determine roughly the number of seconds each action is taking
   1. check if there is less than twice that number of seconds remaining within the host's hard time limit (i.e. if the hosts hard time limit is 60 seconds, and it's taking roughly 5 seconds to process each action, then check if the `$time_elapsed` is more than 50 seconds/there is less than 10 seconds remaining before reaching `$max_execution_time`)
   1. if there is, do not process any more actions and allow `do_batch()` to `release_claim()`, `clear_caches()` etc.

While it's a bit hacky to hardcode time limits for some hosts, and it will slow down the execution of actions on those hosts, it's worth it to avoid actions being terminated midway through their execution. Which can be serious, especially in the case of Subscriptions.

**Comment by code2prog** [comment]
Could you please show implemented solution for Wpengine? At the moment scheduled jobs are not processed. Stucked in queue with "in progress" status and then fail with timeout error.

**Comment by code2prog** [comment]
any help?

**Comment by thenbrent** [comment]
@code2prog you can manually tweak the batch size and queue concurrency for your client using the [Action Scheduler Low Volume](https://github.com/Prospress/action-scheduler-low-volume) plugin. To understand the hooks used in that plugin, please read over the [Performance Tuning](https://github.com/Prospress/action-scheduler#performance-tuning) section of the README. (Just note that you'll be decreasing things instead of increasing them).

Manually setting those limits first requires monitoring how long each action in the queue is taking. If your scheduled jobs are with Subscriptions, you can use something like [Renewal Timer](https://github.com/prospress/woocommerce-subscriptions-renewal-timer/) for that. If they are for something else, you'll need to figure out how to track them.

> Could you please show implemented solution for Wpengine?

There is no code written to automatically detect or handle timeouts on specific hosts yet. When there is, it will be submitted in a pull request linking to this issue.

> any help?

This repo is not a support channel. It is a development repository and _Issues_ are designed for reporting bugs, tracking progress on development and as a roadmap for future development.

To get help with Subscriptions or other plugins using Action Scheduler, please submit a support ticket to the respective author of the plugin, which is usually via WooCommerce.com: https://woocommerce.com/my-account/marketplace-ticket
