### ISSUE TITLE
Using WordPress, ActionScheduler and PHPstan

### ISSUE THREAD

**Issue by thomas-price** [Prospress/action-scheduler#1096]
We are using ActionScheduler in our custom plugin, installed as a library. Thank you

In https://actionscheduler.org/api/ for Function Reference / `as_get_scheduled_actions()`
the following is recommended in parameters:
'status' => '' - ActionScheduler_Store::STATUS_COMPLETE or ActionScheduler_Store::STATUS_PENDING

Our use is:
```
require_once PLUGIN_DIR . 'vendor/woocommerce/action-scheduler/action-scheduler.php';

... other file ...
declare( strict_types = 1 );
namespace ...
class ...

$args = array(
	'this_hook' => $this_hook,
	'status'    => \ActionScheduler_Store::STATUS_PENDING,
);
```

When PHPstan is run, it raises an error:
`Access to constant STATUS_PENDING on an unknown class ActionScheduler_Store.`

The easy way to resolve this is to use PHPstan to ignore the error, but the preferred way is not to have any unknown classes.

Any suggestions?

regards

**Comment by crstauf** [comment]
Does your PHPStan config have a directive to scan the directory with Action Scheduler?

**Comment by thomas-price** [comment]
Action Scheduler is included in the composer config.
`phpstan.neon` includes a config for composer dependencies
```
	bootstrapFiles:
		- my-plugin/vendor/autoload.php
```
It finds the classes, functions and constants for the composer dependencies ....except Action Scheduler

OK read the manual ... again
Reference: https://phpstan.org/user-guide/discovering-symbols#third-party-code-outside-of-composer-dependencies

So tried:
```
	bootstrapFiles:
		- my-plugin/vendor/autoload.php
	scanFiles:
		- my-plugin/vendor/woocommerce/action-scheduler/functions.php
		- my-plugin/vendor/woocommerce/action-scheduler/classes/abstracts/ActionScheduler_Store.php
```
SUCCESS!

thank you
