### ISSUE TITLE
Empty $args at scheduled action trigger

### ISSUE THREAD

**Issue by crouti** [Prospress/action-scheduler#111]
I use your plugin without any problem to create scheduled actions : work great!
I just created a new action type (almost copied pasted from the working one) to schedule:

```
 add_action(AUTO_CANCEL_ACTION, array(
                    $this,
                    'process_auto_cancellation'
                ), 10, 1);
```

Unfortunately this one does not work well, the trigger works prefect but only the first item of my initial array

```
$args = array(
                    'title' => $post_title,
                    'id' => $postID,
                    'sent_lead_id' => $lead_id,
                    'practitioner_id' => $practitioner_id,
                    'patient_id' => $patient_id,
                    'reminder_timeshift' => $timeShift,
                    'type' => 'rdv_auto_cancel',
                );
                
                $group = strval($postID);
                
                $createdScheduledAction = wc_schedule_single_action($reminderTimestamp, AUTO_CANCEL_ACTION, $args, $group);
```

is passed to the callback fonction ($args only contains the first item of created array, as a string!):

```
function process_auto_cancellation($args) {           
            MEDAPI::getLogger()->debug($args);
}
```
Any idea please ?
Thanks

**Comment by thenbrent** [comment]
@crouti the args are not passed to your callback in an array unless they are an array.

You should specify each each arg as a separate parameter and make sure you `add_action()` call passes the callback all 7 params. e.g. 

```
 add_action(AUTO_CANCEL_ACTION, array( $this, 'process_auto_cancellation' ), 10, 7 );
```

And then update `process_auto_cancellation()` to be:

```
function process_auto_cancellation( $title, $id, $sent_lead_id, $practitioner_id, $patient_id, $reminder_timeshift', $type )
```

**Comment by crouti** [comment]
Thank you very much. Very clear.

_the args are not passed to your callback in an array unless they are an array._

Isn't my $args parameter an array ?

**Comment by thenbrent** [comment]
The `$args` parameter is an array, but non of the values within it are an array. To receive args as an array, you would instead need to pass in a multidimensional array, like this:

```
$action_args = array(
	'first_arg_is_string' = 'This is a string',
	'second_arg_is_int' = 123,
	'third_arg_is_array' = array(
		'some_key'            => 'some_value',
		'some_other_key' => 'some_other_value',
	),
);
wc_schedule_single_action( time(), 'hook_name', $action_args );
```

Then your callback would accept 3 parameters, and the 3rd would be an array containing those values. Hope that helps. :)

**Comment by crouti** [comment]
Ok thanks!
