### ISSUE TITLE
Log custom messages?

### ISSUE THREAD

**Issue by mathishuettl** [Prospress/action-scheduler#122]
Hello,

how can I log custom messages?
Now there are only three logs (started,  created, completed).

I have a array as argument and want to log all values from the array to reproduce if a schedule fails.

**Comment by thenbrent** [comment]
@mathishuettl you can call `ActionScheduler::logger()->log( $action_id, $message )`. :)

**Comment by alexminza** [comment]
How can one get the `$action_id` inside the recurring action hook?

**Comment by thenbrent** [comment]
@alexminza you'd need to attached a callback to `'action_scheduler_before_execute'` that caches it for your use later once `$action->execute()` is called.

**Comment by alexminza** [comment]
Hooking into `action_scheduler_before_execute`, storing the `$action_id` and obtaining it during action hook execution, all while juggling between instance and static methods makes the code a mess.

An actual example is described here #95.

**Comment by thenbrent** [comment]
@alexminza I'm help you avoid avoid a mess in your code - if you submit a PR I'll review it. This isn't a priority for us though. I've left some notes on how to achieve this via #215.
