### ISSUE TITLE
How to run an action immediately ?

### ISSUE THREAD

**Issue by veptune** [Prospress/action-scheduler#1223]
Hello all,

I tried :

$action_id = as_enqueue_async_action('update_order_with_files_action', array('order_id' => $order_id));
       
as_run_action($action_id);

But there is still a delay of a few seconds before my function is run.

Any ideas?

Thanks

**Comment by crstauf** [comment]
There is no function `as_run_action()` within the Action Scheduler codebase. The best way (afaik) to run an action immediately is to enqueue an async action, and then use `wp action-scheduler run` WP CLI command to execute the queue runner.

When the new version comes out, you'll be able to run an individual action using `wp action-scheduler action list` and [`wp action-scheduler action run`](https://github.com/woocommerce/action-scheduler/pull/1071/files#diff-3b39e73efd47ddbba7c568eb30d06ff5a6b1bd7315fac9e378ab1b6756d5d7d0).

**Comment by barryhughes** [comment]
Supplementing the earlier answer, if you're less interested in running a specific action and the situation is that, in general, you want to be able to enqueue an async action and have it run as quickly as possible, your first step should be to increase the number of allowed concurrent queue runners.

https://actionscheduler.org/perf/

If you have the necessary level of access and the server resources to support it, you can also keep spawning WP CLI-based queue runners such that actions are continually being picked up and processed. This could help you get to a point where delays are reduced to the maximum possible extent.
