### ISSUE TITLE
Uncaught RuntimeException

### ISSUE THREAD

**Issue by jeckman** [Prospress/action-scheduler#1224]
Also opened a thread in all-in-one-seo-pack support forum, but I think at least the exception catching ought to be happening in this action scheduler?

PHP Fatal error:  Uncaught RuntimeException: Error saving action: Error saving action: Unknown column 'priority' in 'field list' in /wp-content/plugins/all-in-one-seo-pack/vendor/woocommerce/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44

Not sure what version of action-scheduler is included in AIOSEO but the AIOSEO version is 4.7.6

**Comment by jeckman** [comment]
FYI this is on a site that does not run woocommerce but I don't know much about the action scheduler so let me know if this is the wrong place to share this

**Comment by barryhughes** [comment]
Hi @jeckman. This sounds like a problem in which the `priority` column is missing from the `wp_actionscheduler_actions` table. Are you comfortable working with SQL, and do you have access to a tool such as phpMyAdmin? If so, you might try something like this:

```sql
alter table wp_actionscheduler_actions
    add priority tinyint default 10 not null;
```

Or, if you have access to WP CLI, you could try running:

```sh
wp action-scheduler fix-schema
```

The latter may be easier/safer, but it also depends on the WP database user having the necessary privileges to make the required change, which may not be the case. Normally this isn't required but, again, it seems like it was not possible for Action Scheduler to perform the necessary update itself.

**Comment by jeckman** [comment]
Thanks Barry - will do. 

I guess my question was even if a table ends up without the right columns, shouldn't an exception be thrown and caught?

**Comment by jeckman** [comment]
Adding the column worked

**Comment by barryhughes** [comment]
In this case, that probably would make sense, yes, and we have a separate issue that outlines the need to review how these situations are handled:

https://github.com/woocommerce/action-scheduler/issues/1059
