### ISSUE TITLE
Occasional Unit Test timing failure

### ISSUE THREAD

**Issue by JPry** [Prospress/action-scheduler#140]
I've noticed that in all of the Unit Test runs, there is occasionally a failure in one of the tests that is looking at the unix timestamp as part of the test result. The issue appears to be that in the time the test has run, a single second was incremented, causing a difference in timestamp comparison:

<a href="https://cl.ly/3G0y11472135" target="_blank"><img src="https://dzwonsemrish7.cloudfront.net/items/39120X1F3B3W003v2p3u/Image%202018-05-14%20at%2008.59.13.png" style="display: block;height: auto;width: 100%;"/></a>

I don't know if it's a good idea to rewrite the tests to prevent these failures, as a manual re-run of the individual job is required to get it to pass. I thought it might be a good idea to submit  this for discussion.

Some options for changing the tests:

* When comparing Unix timestamps, allow for 1 second of difference between the two timestamps. Maybe something like this:
```php
$expected = get_some_timestamp();
$actual = get_real_timestamp();
$this->assertTrue( $expected === $actual || ( $expected + 1 ) === $actual );
```
* An alternative may be to see whether we can use the `$delta` parameter of [`assertEquals()`](https://phpunit.readthedocs.io/en/7.1/assertions.html#assertequals). However, that *may* only be able to be used for floats instead of integers. It looks like it *should* work, but we'd have to actually try it and see.

**Comment by thenbrent** [comment]
@JPry we have dealt with in the Subscriptions test suite before also. I think the solution there was basically the same as the two you've proposed here, and I’d be OK with either. But it might be worth digging up the discussion on that, as I vaguely recall some issues being encountered with `$delta` and/or the other approach.

**Comment by rrennick** [comment]
> But it might be worth digging up the discussion on that

The deltas were added as part of the 3.0 update.

**Comment by rrennick** [comment]
Fixed in https://github.com/Prospress/action-scheduler/pull/264
