### ISSUE TITLE
Major Architecture adjustments

### ISSUE THREAD

**Issue by JPry** [Prospress/action-scheduler#155]
This is something I have been thinking about for some time, but first mentioned in [this comment](https://github.com/Prospress/action-scheduler/pull/152#issuecomment-394844572).

To summarize, I'd like to work on rearchitecting Action Scheduler in the following ways:

- Utilize Namespaces for the entire plugin. I was anticipating using `Prospress\ActionScheduler` as the top level namespace, but I'd be open for other variations.
- Use [PSR-4](https://www.php-fig.org/psr/psr-4/) folder structure to facilitate a more simple autoloader.

The goal here is to bring the structure of Action Scheduler into alignment with more modern PHP practices, and also serve as an example for other Prospress plugins, such as WooCommerce Subscriptions. Because this is kind of work is generally more refactoring, I envision doing this incrementally as opportunities present themselves. A good current example is #152. In this way, this work can be done in the midst of other changes where it makes the most sense, without taking away from higher priorities.

All of the changes should maintain backward compatibility until we specifically release a breaking change. For example, if the class `ActionScheduler_Store` is migrated to `Prospress\ActionScheduler\Store`, the existing class should be marked as `@deprecated` and extend the new class. Once we release a breaking version, we can remove any `@deprecated` classes.

Here are some of the high-level todo items:

- [ ] Create a PSR-4 autoloader (currently in #152)
- [ ] Create custom Exceptions (currently in #152)
- [ ] Move all existing classes into PSR-4 namespace structure.
- [ ] Keep existing classes, marked as `@deprecated`
- [ ] Remove all `@deprecated` classes next major version

With these changes in place, we could then start looking into how we could possibly work on the overall architecture for Action Scheduler, to see how we can implement better OOP practices. As an example, I think something similar to [Alain Schlesser's AS Speaking Plugin](https://github.com/schlessera/as-speaking) would be a good target. The details of these changes would ideally be fleshed out more in another Issue, but I'm mentioning it here as a long-term idea.

**Comment by JPry** [comment]
Internal Slack conversation: https://prospress.slack.com/archives/C09TX8KHQ/p1528295145000009

**Comment by thenbrent** [comment]
Closing this as I don't think it'll ever bubble up the priorities list.
