### ISSUE TITLE
Negate the need for calling $runner->setup() multiple times.

### ISSUE THREAD

**Issue by JPry** [Prospress/action-scheduler#168]
As mentioned a few places ([here](https://github.com/Prospress/action-scheduler/pull/115#issuecomment-373201118) and [here](https://github.com/Prospress/woocommerce-subscriptions/issues/2755)), it's not ideal to need to call `$runner->setup()` multiple times when executing the WP CLI command.

We should explore a better alternative if possible.

**Comment by rrennick** [comment]
This one is fixed in #259 where `setup()` is only called once: https://github.com/Prospress/action-scheduler/blob/add/custom-tables/classes/WP_CLI/ActionScheduler_WPCLI_Scheduler_command.php#L57

Closing this. If anyone feels this should be addressed sooner than 3.0, please re-open.
