### ISSUE TITLE
Maintain backward compatibility of ActionScheduler_LogEntry::__construct() for `ActionScheduler_wpCommentLogger::get_entry()` call

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler#169]
This relates to [Slack discussion here](https://prospress.slack.com/archives/C03A22H08/p1529678344000327):

And the following error with 2.0.0-RC-1:

```
Fatal error: Uncaught TypeError: Argument 3 passed to ActionScheduler_LogEntry::__construct() must be an instance of DateTime, string given, called in /wp-content/plugins/woocommerce-follow-up-emails/includes/lib/action-scheduler/classes/ActionScheduler_wpCommentLogger.php on line 50
	and defined in /wp-content/plugins/action-scheduler-2.0.0-RC-1/classes/ActionScheduler_LogEntry.php:31
Stack trace:
#0 /wp-content/plugins/woocommerce-follow-up-emails/includes/lib/action-scheduler/classes/ActionScheduler_wpCommentLogger.php(50): ActionScheduler_LogEntry->__construct('141307', 'action created', 'action_log')
#1 /wp-content/plugins/woocommerce-follow-up-emails/includes/lib/action-scheduler/classes/ActionScheduler_wpCommentLogger.php(72): ActionScheduler_wpCommentLogger->get_entry(Object(WP_Comment))
#2 /wp-content/plugins/action-scheduler-2.0.0-RC-1/classes/Ac in /wp-content/plugins/action-scheduler-2.0.0-RC-1/classes/ActionScheduler_LogEntry.php on line 31
```

I noticed that the `ActionScheduler_LogEntry::__construct()` call in FUE's `ActionScheduler_wpCommentLogger::get_entry()` method passed `$comment->comment_type` as the 3rd param. That's what is causing the issue above.

Although `ActionScheduler_LogEntry` doesn't accept a 3rd param in the 1.4-dev version of AS in use by FUE, the `ActionScheduler_wpCommentLogger::get_entry()` method did define it in core (i.e. it's not a hack just on that version).

A quick `git bisect` shows that this change led to the above issue: https://github.com/prospress/action-scheduler/commit/950ad2c7db061cd750312ba97b2f0a2c365a88ee#diff-b6c2e1ac0771deb75b8bb9ad40dc0994L52

As seen in that large commit, it _should_ in theory be safe to add `$date` as a 3rd param to `ActionScheduler_LogEntry::__construct()`, because there was no 3rd param. However, because core code was passing a 3rd param - the comment's group - I feel this should continue to be supported and `$date` should be moved to a 4th param.

**Comment by cesar-prospress** [comment]
It's my commit, I could work on it if you want @thenbrent.
