### ISSUE TITLE
WP CLI: Add timestamps to output

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler#175]
When running Action Scheduler via WP CLI using a `crontab` task or similar automated process, it's handy to log the results into log files so you can keep track of what happened (especially if there are large queues of actions to process).

In these cases, it would be extremely helpful to have date/times displayed alongside the output.

For example, this is a log of errors running AS via WP CLI using Crontab:

![](https://cl.ly/0T1a3o312W3d/[3c7768a5db7cf32612012b01b9037a9b]_Screen%20Shot%202018-07-10%20at%208.47.12%20am.png)

And this is an example of valid logged output:

![](https://cl.ly/3N3o303P3s1k/Screen%20Shot%202018-07-10%20at%208.45.36%20am.png)

**EDIT**: I know it doesn't make a whole lot of sense to display timestamps etc. when there is a progress meter (i.e. WP CLI is being run manually). I'm not sure how to reconcile those different use cases, but I think it's far more likely in production WP CLI will be used via a schedule (i.e. Crontab) than manually.

**Comment by crstauf** [comment]
I've found that when running via WP CLI manually, a timestamp would be helpful when reviewing the output at a later time. Perhaps a flag that can turn **on** timestamp output would be preferable to defaulting its display.

**Comment by crstauf** [comment]
Submitted PR #254 with [notes](https://github.com/Prospress/action-scheduler/pull/254#issue-259715461).

**Comment by crstauf** [comment]
This was merged in #267 (https://github.com/Prospress/action-scheduler/commit/076630e7a0d5d1fb47f0d77c095e0fb86b99842a).

**Comment by rrennick** [comment]
> This was merged in #267

Closing.
