### ISSUE TITLE
Log entries displayed on list table always show current time

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler#178]
The date/time displayed against log entries on the admin list table always show current time, not the time of the actual events.

For example, here are the log events displayed for the same scheduled action on the admin page loaded about 10 minutes apart:

1. Load at 2018-07-17 04:29:15 UTC: https://cl.ly/3p0V0u430s2b
1. Load at 2018-07-17 04:38:43 UTC: https://cl.ly/0T1I0r1y0o1t

Notice the times display on each change depending on the page load time, and all entries display the times the page was loaded.

I noticed this on ticket https://secure.helpscout.net/conversation/555708450/7375?folderId=1524436

I've also seen it on other sites.

**Importantly:** I haven't been able to reproduce this locally. I also haven't seen it on all sites, so I'm not sure how to reproduce it yet. It _may_ also be only happening with [Custom Tables](http://github.com/Prospress/action-scheduler-custom-tables/).

**Comment by NickGreen** [comment]
Another one in the wild, in case it helps: https://secure.helpscout.net/conversation/669476259/17463?folderId=1524484

**Comment by thenbrent** [comment]
Closing this in favour of https://github.com/Prospress/action-scheduler-custom-tables/issues/45.
