### ISSUE TITLE
Notice when $args is an array of arrays

### ISSUE THREAD

**Issue by OriginalEXE** [Prospress/action-scheduler#189]
Hello,

First of all, thank you for maintaining this useful library.

I ran into an issue where the library triggers a notice due to an array to string conversion. The problem is easily reproducible by scheduling a single action and passing an array of arrays as a `$args` (3rd argument).

The line in question seems to be [this one](https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_ListTable.php#L245)

It seems like what's needed is checking whether an argument can be safely passed to `esc_html`, and if not, maybe passing it through `var_export` first?

Thanks,
Ante

**Comment by thenbrent** [comment]
Thanks for the report @OriginalEXE. I've just submitted a PR to fix this. See #190.

**Comment by OriginalEXE** [comment]
Thank you for a quick reaction and for fixing it!
