### ISSUE TITLE
Scheduled action $args when there is a lot of data

### ISSUE THREAD

**Issue by jonathanstegall** [Prospress/action-scheduler#199]
Hope it's okay to ask another question. I've got the library working, I think, but I'm having issues passing data to it.

Some context: my plugin passes data between WordPress and a third party API. So it might be tasked with pushing data to that API, or pulling data from it when it gets updated. Users can choose whether data should be pushed asynchronously or all at once. I was previously using the WP_Background_Task library, but it seems like it won't scale to the possible level required (*update: that is, I ran into a case where it crashed Apache with a large pull from the API*).

An example:

On a push operation, the plugin gathers all the data and determines how it should be mapped to the API's fields and puts it all into an array:

```
$data = array(
	'object_type'     => $object_type, // what type of WordPress object it is - user, post, etc.
	'object'          => $object, // the data from the individual object in an array.
	'mapping'         => $mapping, // how the two object types are mapped together (fields, allowed triggers, etc)
	'sync_trigger'    => $sync_trigger, // what happened to cause the sync (a WordPress create, update, delete, for example)
);
```

This data gets passed to a method that sends it to the API, whether it is happening immediately or whether the task scheduler has run the callback method. So it's rather comprehensive data.

Here's how I tried to use action-scheduler:

```
// this item is async and we want to save it to the queue
$this->queue->add(
	$this->schedulable_classes[ $callback_name ],
	array(
		'data' => $data,
	),
	'push'
);
```

So `$data` is potentially a very large array. I'm thinking maybe I won't be able to use action-scheduler because of this, but I thought I'd ask anyway.

When I run this method, I get the error:

> PHP Notice:  ActionScheduler_Action::$args was called <strong>incorrectly</strong>. To ensure the action args column can be indexed, action args should not be more than 191 characters when encoded as JSON. Support for strings longer than this will be removed in a future version. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 2.1.0.) in /wp-includes/functions.php on line 4161

Do you have a way you use action-scheduler to handle potentially large amounts of data like this? Would I need my callback to run all the methods to get the data that currently is stored in `$data` all over again and then pass them to the API? It's a lot of redundancy, unless I restructure the entire plugin, but maybe it's not an issue?

Thanks for any thoughts if you have them; I know there's a lot going on here.

**Comment by jonathanstegall** [comment]
@thenbrent thanks for all your help on this.

One final question, then, if I can: if I store the object ID and mapping row ID in the array and pass them to the hook, do you think I need to restructure my plugin so that it hasn't loaded all of that data once already, or would it be okay to just load it twice?

For example, currently I load all the WordPress object data and field pairs that needs to be sent to the API prior to setting up this `$data` array, based on the actions that WordPress runs for that object type (user, post, term, etc.) and then I send the contents of the array to the callback.

I could continue to do that loading based on what type of object it is, and then load it again in the hook method. Loading does involve one custom table, and that part is easy, but it also involves using the various WordPress methods to get user data, post data, meta fields, and so on.

Loading it twice would be the way to preserve all the plugin filters that control data and mapping and everything as they are. But I don't know to what extent I would be breaking my performance at this point?

**Comment by thenbrent** [comment]
Ah gotcha. So there is a performance hit in double loading. Depending on the queries, that could be trivial or non-trivial hit. There's really no way to know without at a minimum deep understanding of the queries, or ideally, tools to profile the queries, like New Relic or Query Monitor. Usually loading objects isn't much to worry about. It's only if doing things like loading the data from non-performant schemas (e.g. if you were loading things from the post table based on a few piece of matching post meta, and forcing joins to do that).

If you are really worried, about that, you can always store the instantiated object in a new store with a new ID that is used on for the scheduled action. But personally, I'd look at profiling the instantiation, making sure it is performant, and using the same API to load it when the action is scheduled and run.
