### ISSUE TITLE
Setting priority order of task processing

### ISSUE THREAD

**Issue by bennygill** [Prospress/action-scheduler#205]
I have two "chains" of scheduled actions and I need all of the tasks in the first chain to complete before processing the tasks in the second chain.

**EXAMPLE:**

I want to make sure all the `first_chain_logic_function` tasks are complete before starting any of the `second_chain_logic_function` tasks, because the tasks in `second_chain_logic_function` rely on output from the `first_chain_logic_function`.

Is this possible?

```
//First chain of scheduled actions
add_action( 'init', 'first_chain_first_loop', 10 );
function first_chain_first_loop() {
	for ( $i=0; $i < 10; ++$i ) {
		as_schedule_single_action( time(), 'first_chain_second_loop_action', array ( 'id' => $a ) );
	}
}
add_action( 'first_chain_second_loop_action', 'first_chain_second_loop', 10, 1 );
function first_chain_second_loop( $a ) {
	for ( $i=0; $i < 1000000000; ++$i ) {
		as_schedule_single_action( time(), 'first_chain_logic_function_action', array ( 'id' => $b ) );
	}
}
add_action( 'first_chain_logic_function_action', 'first_chain_logic_function', 10, 1 );
function first_chain_logic_function( $b ) {
	//Do stuff here
}

//Second chain of scheduled actions
add_action( 'init', 'second_chain_first_loop', 11 );
function second_chain_first_loop() {
	for ( $i=0; $i < 10; ++$i ) {
		as_schedule_single_action( time(), 'second_chain_second_loop_action', array ( 'id' => $a ) );
	}
}
add_action( 'second_chain_second_loop_action', 'second_chain_second_loop', 10, 1 );
function second_chain_second_loop( $a ) {
	for ( $i=0; $i < 10; ++$i ) {
		as_schedule_single_action( time(), 'second_chain_logic_function_action', array ( 'id' => $b ) );
	}
}
add_action( 'second_chain_logic_function_action', 'second_chain_logic_function', 10, 1 );
function second_chain_logic_function( $b ) {
	//Do stuff here that relies on output from the first_chain_logic_function
}
```

**Comment by thenbrent** [comment]
It's possible in a few ways, but there is no dependency management built in.

The simplest approach is to refactor your code to schedule the dependent hooks only after the other other hooks have all completed.

You could also use WP CLI as the runner instead of WP Cron, and specify the hooks to run. More details in [this doc](https://github.com/Prospress/action-scheduler#wp-cli). But you'd also need to have some kind of script setup to kick off the 2nd queue only after the first is completed. It would be more complicated than refactoring the WordPress code.

**Comment by bennygill** [comment]
Are all the tasks in the queue processed first-in-first out, so if I ensure that all `second_chain_logic_function` are sent to the queue after the `first_chain_logic_function` tasks I should be fine?

**Comment by thenbrent** [comment]
Yes. By default, they are processed in order of date/time (then ID if more than one is for the same time).

**Comment by bennygill** [comment]
Thanks, that did the trick. This plugin is amazing, really appreciate you guys releasing it!
