### ISSUE TITLE
Inconsistent date formats for timezone

### ISSUE THREAD

**Issue by menakas** [Prospress/action-scheduler#208]
In the Scheduled Actions page, the Log Date's format contains UTC whereas the Scheduled Date uses +00:00 to specify timezone

As far as I can see, I do not see Scheduled Date displayed in any other time zone. Would it be good to have a consistent format?

![](https://cldup.com/z1hCxyp8GN.png)

**Comment by thenbrent** [comment]
> Would it be good to have a consistent format?

Yes, for sure! :)

**Comment by thenbrent** [comment]
It looks like both `ActionScheduler_ListTable::get_schedule_display_string()` and `ActionScheduler_ListTable::get_log_entry_html()` are already using the same date format timezone character - `e` - as part of the full date format string `'Y-m-d H:i:s e'`.

However, it appears PHP will display different timezone identifier's, presumably depending on the value passed to the `DateTimezone` object when it is instantiated.

I tested changing the modifier to `T`, but the behaviour is similar. It will display `GMT+0000` for the scheduled date and `UTC` for the log entries: http://pic.pros.pr/c494a050fdaf

If changing the timezone format character to `O`, we get consistent results - the difference to Greenwich time (GMT) in hours, i.e. `+0000`.

This appears to stem from the same issue as #179 - we don't always have a timezone, sometimes we only have an offset, so we can only ever reliably display an offset.

Abbreviations are easier to grok IMO, but as we can't always guarantee we'll have one, we'll need to use offsets.
