### ISSUE TITLE
Full example/ tutorial?

### ISSUE THREAD

**Issue by scrobbleme** [Prospress/action-scheduler#212]
Hello,

I want to implement a recurring action. 
But from the readme I'm not sure what I have to do for this. I also can't find any examples for this.

Is calling `as_schedule_recurring_action` within an `init` hook the only thing I have todo?

Would be great to have full examples for the different actions.

Thank you

**Comment by thenbrent** [comment]
Hi @scrobbleme, 

> Is calling `as_schedule_recurring_action` within an init hook the only thing I have todo?

Yes, pretty much. Though for the action to be of any use, you'd also need a callback attached to run on that action.

> Would be great to have full examples for the different actions.

The example code below shows everything needed to schedule a function to run at (roughly) midnight each day:

```php
require_once( plugin_dir_path( __FILE__ ) . '/libraries/action-scheduler/action-scheduler.php' );

/**
 * Schedule an action with the hook 'eg_midnight_log' to run at midnight each day
 * so that our callback is run then.
 */
function eg_log_action_data() {
	if ( false === as_next_scheduled_action( 'eg_midnight_log' ) ) {
		as_schedule_recurring_action( strtotime( 'midnight tonight' ), DAY_IN_SECONDS, 'eg_midnight_log' );
	}
}
add_action( 'init', 'eg_log_action_data' );

/**
 * A callback to run when the 'eg_midnight_log' scheduled action is run.
 */
function eg_log_action_data() {
	error_log( 'It is just after midnight on ' . date( 'Y-m-d' ) );
}
add_action( 'eg_midnight_log', 'eg_log_action_data' );
```

I've added that to the _Usage_ section on the new docs site: https://actionscheduler.org/usage/#scheduling-an-action (the README was getting a little too long for one page).

**Comment by ravisoni6262** [comment]
As per your example, I did set an interval of 5 seconds and expected to update the DB value in each 5 seconds, but it is not true. it is updating DB value only after 60 seconds which is the default run schedule for AS.
