### ISSUE TITLE
Get Action ID argument in action hook

### ISSUE THREAD

**Issue by alexminza** [Prospress/action-scheduler#215]
Currently, to get the `$action_id` for the currently executing action hook (for example to output associated log messages) one has to query the store which involves queries to the database:

```
$action_id = ActionScheduler::store()->find_action('my_hook', array('status' => ActionScheduler_Store::STATUS_RUNNING));

ActionScheduler::logger()->log($action_id, __FUNCTION__);
```

This issue was discussed and worked on before (eg. #95) but looks like there is currently no proper way for an action to be able to identify itself in a proper and efficient way.

This will allow to log specific action messages visible to the admins on the Scheduled Actions admin page, review the status of the job and identify potential problems.

**Comment by thenbrent** [comment]
Some notes: hooks are agnostic of actions. It's dangerous for Action Scheduler to pass additional data, like the `$action_id` to the callbacks on hooks, because we don't know what parameters it receives already.

Instead, we could store the `$action_id` in a `global` (not ideal) or make it accessible via some method in the `ActionScheduler_Abstract_QueueRunner`, e.g. `ActionScheduler_Abstract_QueueRunner::get_current_action()`.

**Comment by thenbrent** [comment]
I'm going to close this one. Responding to the original requirement:

> This will allow to log specific action messages visible to the admins on the Scheduled Actions admin page, review the status of the job and identify potential problems.

Generally speaking, the scheduled action logs should store information relating only to the processing of the scheduled action, not information from callbacks on that action. Ideally, callbacks will use their own logging system for that purpose. This separation also keeps scheduled action logs cleaner and more consistent.

For example, scheduled payment actions run via Action Scheduler with callbacks from WooCommerce Subscriptions (and other plugins) will log data about the payment process both to the subscription notes, and to debug log files, but not to Action Scheduler.
