### ISSUE TITLE
Action execution result/status

### ISSUE THREAD

**Issue by alexminza** [Prospress/action-scheduler#216]
For a better understanding of the actions execution history results and visual evaluation of the scheduled actions health it would be great to have action execution results that can be programmatically set by the developer based on the business logic performed in the action code.

For example: SUCCESS, WARNING, FAILED, displayed with corresponding color/style in the web admin (searchable/sortable).

**Comment by thenbrent** [comment]
@alexminza agreed, this would be great. If you submit a PR that is 100% backward compatible, I'll review it with a view to merging. It's a quite unique request for your needs though, and not a priority for us or other implementations we've seen so I'm going to close this issue as it's not something we'll be investing time to build.
