### ISSUE TITLE
Schedule order and payment actions

### ISSUE THREAD

**Issue by zhex900** [Prospress/action-scheduler#220]
Hi,

I have a woocommerce site. Checkout is slow. I think order creation and payment takes too long. Your doc says it can schedule order and payment. Is it possible for someone to give an code example? 

I figured out how to use `as_schedule_single_action`. Should I use a hook like `woocommerce_pay_order_before_submit` to 
1. delete the order creation action 
2. register the order creation action through `as_schedule_single_action`

Am I on the right track?

**Comment by rrennick** [comment]
> Your doc says it can schedule order and payment.

On an initial order from a customer you need to get the customer's payment information so that cannot be scheduled. Action Scheduler is already used by WooCommerce to handle tasks that can be completed in the background.
