### ISSUE TITLE
Add scheduled action stats to WooCommerce System Status

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler#222]
The WooCommerce System Status includes a section for `### Post Type Counts ###`, which includes `scheduled-action` posts. However, it would be very helpful to also receive a breakdown of the actions by status, e.g. how many are pending? how many failed?

Action Scheduler doesn't have any other dependency on WooCommerce, so this would have to be added only when WC is found to be active.

**Comment by crstauf** [comment]
Submitted #243 which adds status counts to the WooCommerce system status report, as well as the oldest and newest action dates of each status.

**Comment by rrennick** [comment]
This is in WC core now.
