### ISSUE TITLE
Every 11th action fails with "PHP Fatal error Allowed memory size" 

### ISSUE THREAD

**Issue by jawinn** [Prospress/action-scheduler#224]
I'm processing some PDFs that can be pretty large. In a queue of 400 with the same 30MB PDF, every 11th one failed:
`unexpected shutdown: PHP Fatal error Allowed memory size of 268435456 bytes exhausted (tried to allocate 28643256 bytes)...`

1. Is there any way to make the action re-run automatically when the PHP memory is exhausted?
2. There appears to be no way to re-run a failed action via the admin interface? (plugin version of Action Scheduler, Tools->Schedule Actions)

It looks like my options are to increase the memory limit on the server, and/or reduce the number of items in the batch with action_scheduler_queue_runner_batch_size, but this is guessing at numbers. It would be helpful to handle the case of the memory limit being hit.

**Comment by rrennick** [comment]
https://github.com/Prospress/action-scheduler-low-volume would reduce the number of actions to 10.

> It would be helpful to handle the case of the memory limit being hit.

Unfortunately, it is the scheduled action vs the action scheduler itself that is exhausting memory. When AS initiates a scheduled action there isn't any way of being certain in advance whether there is enough resources available to meet the needs of the scheduled action.

**Comment by thenbrent** [comment]
> There appears to be no way to re-run a failed action via the admin interface? (plugin version of Action Scheduler, Tools->Schedule Actions)

Yes that's right, there is no UI to re-run failed actions.

If that would be helpful for you, it could be a helpful addition to core and a PR is welcome to add it. A new _Reschedule_ or _Requeue_ action on the [admin list table](https://actionscheduler.org/admin/) would be a good approach.

> Is there any way to make the action re-run automatically when the PHP memory is exhausted?

While it would technically be possible to reschedule it, as Ron said, there's not much point, as it's likely safe to assume that it'll just run out of memory again.

**Comment by jawinn** [comment]
Thanks for the responses guys, those filters will help. A reschedule action is definitely a good idea. 
Closing this issue.
