### ISSUE TITLE
Fatal error: Uncaught RuntimeException: Error saving action:

### ISSUE THREAD

**Issue by allangoncha** [Prospress/action-scheduler#232]
I'm having a problem with the action scheduler as you can see below:

```
Fatal error: Uncaught RuntimeException: Error saving action: Pedido inválido. in wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php:27
Stack trace:
#0 /wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(109): ActionScheduler_wpPostStore->save_action(Object(ActionScheduler_Action))
#1 /wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(59): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action))
#2 /wp-content/plugins/woocommerce/includes/libraries/action-scheduler/functions.php(18): ActionScheduler_ActionFactory->single('woocommerce_del...', Array, 1548352889, 'woocommerce-web...')
#3 /wp-content/plugins/woocommerce/includes/queue/class-wc-action-queue.php(44): as_schedule_single_action(1548352889, 'woocom in /wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 27
```

**Comment by rrennick** [comment]
For reference here is the Slack discussion: https://woocommercecommunity.slack.com/archives/C1K9K3UD9/p1548265189338900

@allangoncha did you have any success accessing the webhook URL with a REST client?

**Comment by allangoncha** [comment]
No, I was not successful accessing the URL.

**Comment by rrennick** [comment]
@allangoncha You can send me the details for accessing the URL in a PM in Slack.

**Comment by rrennick** [comment]
Closing this one for lack of feedback.

**Comment by Stryder777** [comment]
After a bit of digging, I managed to resolve the “RuntimeException: Error saving action” by installing Action Scheduler 3.0.

https://github.com/woocommerce/action-scheduler/releases/tag/3.0.0
Release Notes: https://woocommerce.wordpress.com/2020/01/08/action-scheduler-3-0/

Hoping the above may assist any lost souls trolling the net for answers...

**Comment by PiotrNap** [comment]
> After a bit of digging, I managed to resolve the “RuntimeException: Error saving action” by installing Action Scheduler 3.0.
> 
> https://github.com/woocommerce/action-scheduler/releases/tag/3.0.0
> Release Notes: https://woocommerce.wordpress.com/2020/01/08/action-scheduler-3-0/
> 
> Hoping the above may assist any lost souls trolling the net for answers...

Thank you Stryder777, you literally saved my u** 👍

**Comment by sawwd** [comment]
You don't need to downgrade. You can go to **WooCommerce -> Status -> Scheduled Actions** and search for **action_scheduler/migration_hook** and then run it.
