### ISSUE TITLE
'ActionScheduler_wpPostStore_TaxonomyRegistrar' error

### ISSUE THREAD

**Issue by jrick1229** [Prospress/action-scheduler#237]
#### Error:

`2019-02-13T17:10:35+00:00 CRITICAL Class 'ActionScheduler_wpPostStore_TaxonomyRegistrar' not found in /home/paynem6/public_html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 754`

#### Issue

The customer is having renewal issues, but I don't believe this to be related.
Nonetheless, in my search, I saw this error and thought I would go ahead and report it.
I'm not sure if this is a specific one-time case, but it's rare that I see action scheduler errors in the WooCommerce fatal error logs.

**Comment by jrick1229** [comment]
This error was logged at the same time that an update was made:
```
02-13-2019 @ 09:10:48 - 2.5.1 upgrade complete from Subscriptions v2.4.7 while WooCommerce WC_VERSION 3.5.4 and database version 3.4.7 was active.
02-13-2019 @ 09:10:48 - Environment info:
02-13-2019 @ 09:10:48 -     WordPress Version : 5.0.3
02-13-2019 @ 09:10:48 - Active Plugins:
02-13-2019 @ 09:10:48 -     Gravity Forms by rocketgenius – 1.9.12.1
02-13-2019 @ 09:10:48 -     Akismet Anti-Spam by Automattic – 4.1.1
02-13-2019 @ 09:10:48 -     AutomateWoo by Prospress – 4.4.2
02-13-2019 @ 09:10:48 -     Code Snippets by Shea Bunge – 2.13.2
02-13-2019 @ 09:10:48 -     Envato WordPress Toolkit (Deprecated) by Envato – 1.8.0
02-13-2019 @ 09:10:48 -     Instagram Feed by Smash Balloon – 1.10.2
02-13-2019 @ 09:10:48 -     Jetpack by WordPress.com by Automattic – 7.0
02-13-2019 @ 09:10:48 -     WPBakery Visual Composer by Michael M - WPBakery.com – 5.2.1
02-13-2019 @ 09:10:48 -     Revolution Slider by ThemePunch – 4.6.93
02-13-2019 @ 09:10:48 -     Yoast SEO Premium by Team Yoast – 5.5.1
02-13-2019 @ 09:10:48 -     UPS (BASIC) WooCommerce Shipping by PluginHive – 1.2.14
02-13-2019 @ 09:10:48 -     WooCommerce Catalog Visibility Options by Lucas Stark – 3.1.1
02-13-2019 @ 09:10:48 -     WooCommerce Print Invoice & Delivery Note by Tyche Softwares – 4.4.7
02-13-2019 @ 09:10:48 -     WooCommerce Dynamic Pricing by Lucas Stark – 3.1.13
02-13-2019 @ 09:10:48 -     WooCommerce jQuery Cookie Fix by Splashing Pixels (Roy Ho) – 1.0
02-13-2019 @ 09:10:48 -     WooCommerce Points and Rewards by WooCommerce – 1.6.17
02-13-2019 @ 09:10:48 -     WooCommerce Services by Automattic – 1.18.0
02-13-2019 @ 09:10:48 -     WooCommerce USPS Shipping by WooCommerce – 4.4.20
02-13-2019 @ 09:10:48 -     WooCommerce Subscriptions - Do Not Reduce Stock on Renewal by Prospress Inc. – Unknown version
02-13-2019 @ 09:10:48 -     WooCommerce Subscriptions by Prospress Inc. – 2.5.1
02-13-2019 @ 09:10:48 -     WooCommerce by Automattic – 3.5.4
02-13-2019 @ 09:10:48 -     Network Merchants Inc Gateway for WooCommerce by PatSaTECH – 1.7.5
02-13-2019 @ 09:10:48 -     YITH WooCommerce Wishlist by YITH – 2.2.7
```

**Comment by thenbrent** [comment]
> I'm not sure if this is a specific one-time case, but it's rare that I see action scheduler errors in the WooCommerce fatal error logs.

@jrick1229 is there any more stack trace there?

That is a very unusual error. That class is autoloaded. The file would have to be missing for the class to not be available, at least when it is called from `ActionScheduler_wpPostStore.php`, which is also autoloaded.

**Comment by jrick1229** [comment]
@thenbrent - that’s all that was written to the WC logs, but it’s possible there’s more in the PHP Error Logs. If you’d like me to ask for those, I’d be more than happy to do so.

**Comment by thenbrent** [comment]
@jrick1229 yes please ask for those. If we can get access to the full stack trace, it would be a great help!

**Comment by jrick1229** [comment]
@thenbrent - I don't believe they'll be getting back to me. I think they've quietly chosen to ignore my response. You can probably go ahead and close this if you'd like.

**Comment by thenbrent** [comment]
@jrick1229 thanks for the update. I'll close this for now. I suspect it might relate to something like a corrupted update so the file was missing or similar.
