### ISSUE TITLE
Should exclude_from_search be true?

### ISSUE THREAD

**Issue by jonathanstegall** [Prospress/action-scheduler#242]
In [the post arguments](https://github.com/Prospress/action-scheduler/blob/d275178672cf4dad0e2c9e5bbed100d281a46a2a/classes/ActionScheduler_wpPostStore_PostStatusRegistrar.php#L21), I notice that `'exclude_from_search'       => false,` is there.

Is there a reason for this? Shouldn't these posts be excluded from search? Or is it already accounted for somewhere else? I didn't see any other instances of `exclude_from_search` in this library, in any case.

Happy to submit a PR but I wanted to check on it first.

**Comment by jonathanstegall** [comment]
Alternatively, I realize I could do this:

```
function action_scheduler_post_status_args( $args ) {
	$args['exclude_from_search'] = true;
	return $args;
}
```

Is there any reason I shouldn't, regardless of whether the library changes the value here?

**Comment by jonathanstegall** [comment]
I'm remembering that there is an admin search interface for this library now, although it has always failed for me. Presumably that is why there's no exclusion.

**Comment by rrennick** [comment]
Post types that are not `public` are not included in front end searches - https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-post-type.php#L417

**Comment by jonathanstegall** [comment]
Thanks. I'll close this, then.
