### ISSUE TITLE
Queue Housekeeping

### ISSUE THREAD

**Issue by alanef** [Prospress/action-scheduler#244]
Hi,

I couldn't find it in the FAQs or elsewhere, but what is the queue housekeeping methodology? My completed tasks seem to just be growing - is there anything I should be doing?

Alan

**Comment by james-allan** [comment]
Hi @alanef

Action Scheduler will automatically clean up completed and cancelled actions after 31 days. Do you have completed actions which are older than that? 

I'll make a note to make sure we document this.

**Comment by thenbrent** [comment]
@james-allan this is mentioned here: https://actionscheduler.org/#housekeeping

It's just a little hidden and perhaps not clearly worded enough.

**Comment by alanef** [comment]
OK

Also this is quite a long time if you are doing 10,000 actions a day  - 300,000 completed actions
I found this filter   $lifespan = apply_filters( 'action_scheduler_retention_period', $this->month_in_seconds );

But I assume if I filter that then it will apply to all plugins that use action_scheduler

So lets say there is a payment plugin and my plugin and I reduce to 5 days then the payment plugin gets reduced to 5 days?

Any solution? apart from extending ActionScheduler_QueueCleaner - delete_old_actions()  to customise the purge query to include groups

**Comment by thenbrent** [comment]
No, those are the only solutions. Either filter the global value or implement a custom Cleaner for more fine-grained tweaks. There's not really any downside to extending the Cleaner if you're worried about that. Just make sure to use API methods and it should be future proof.

> if you are doing 10,000 actions a day - 300,000 completed actions

A side note, if you are doing that many actions, you should definitely be using Custom Tables plugin: https://github.com/Prospress/action-scheduler-custom-tables/ :)

**Comment by alanef** [comment]
Thanks - I was thinking of overriding the datastore methods to use tables anyway - as I'm building a plugin I don't want to make a second plugin dependency - will look at using as a composer library though
