### ISSUE TITLE
Possibility of extending AS to have multiple datastores

### ISSUE THREAD

**Issue by amans2k** [Prospress/action-scheduler#245]
Hi there,

I have been wondering if AS can in future be extended to have two datastores work in tandem. 

As of now, this does not seem to be the case. 

For my use case, we need to store data in a new datastore (could be a cloud) and yet have other native WooCommerce scheduled actions execute the way they are.

For this need, I created a new datastore (not for scheduling but for execution purpose) and did this:

1) Created a new runner.  And on the runner callback, changed the datastore on plugins_loaded (i.e., action_scheduler_pre_init hook). 

2) That's the only layer I had found through which datastore could be altered for a custom new runner (responsible for executing only our actions).

The custom runner is a  separate HTTP request. It won't impact the native Scheduled Actions.

Is this the correct approach?  Was wondering if there could be a way to register a data store and that method would also register a respective runner.

Or a static method to change the datastore before scheduling any new action.

Thanks for the great software!

**Comment by thenbrent** [comment]
@amans2k it's definitely possible to have dual data stores.

Define a single class as the canonical data store class and then have that handle the routing logic to determine which data source to use, depending on the action type, or perhaps something else, like the runner.

This is the approach we take with the Hybrid data store used in [Action Scheduler Custom Tables](https://github.com/Prospress/action-scheduler-custom-tables/). It will read from the old store and write to the new store until all actions are migrated to custom tables.
