### ISSUE TITLE
Disabling the action Scheduler for a migration

### ISSUE THREAD

**Issue by planetahuevo** [Prospress/action-scheduler#246]
Hi, 
I know that there is this plugin that disable the runner:
https://github.com/Prospress/action-scheduler-disable-default-runner/blob/master/as-disable-default-runner.php

But I have some questions and I was not able to find the answers anywhere. Maybe you can help me. 
- If I setup a htaccess redirect for the whole website to a maintenance.html file, will this stop the scheduler for running? 
- Will the maintenance mode from WordPress disable the scheduler too? 

Also related, if I have disabled the scheduler, and then complete the migration, will the actions scheduled continue where they are? Will I miss anything? 
Thanks!

**Comment by rrennick** [comment]
If you are migrating the site the best thing to do is use the plugin to disable the runner. That way it will be disabled in both sites until you have finished the migration & deactivate the plugin in the new location.

**Comment by planetahuevo** [comment]
Great. Thank you!
