### ISSUE TITLE
Invalid `post_content` causes all jobs to fail

### ISSUE THREAD

**Issue by ChuckMac** [Prospress/action-scheduler#26]
I came across a situation where there was an invalid entry in the `post_content` of a scheduled action caused the entire `do_batch` process to quit.

I have not been able to recreate what caused the issue in the first place in my dev environment, but somehow the `post_content` field (which is a serialized array) ended up being improperly encoded and the trailing quote to close the array ended up as a `&quot;` instead of a `"`.  Ex:

`["This is an invalid value &quot;]`

Regardless, it would seem to be better if the scheduler reaches an invalid entry it is able to continue processing the remaining events rather than stopping all processing.

**Comment by thenbrent** [comment]
Fixed with #27.
