### ISSUE TITLE
Tight recurring event type?

### ISSUE THREAD

**Issue by crstauf** [Prospress/action-scheduler#260]
AS supports two types of events:
1. single
1. recurring

From what i think i’ve noticed, with a recurring event, the next event is scheduled based on the time the previous event is completed. I’ll call this event type “loose recurring” for ease moving forward.

**1. Is it intentional for the next event of a recurring event to be scheduled based on the previous event’s completion time?**

I was looking at _WooCommerce Subscriptions_plugin, and noticed that it does not use recurring events for renewals. I assume this is due to the trickiness of the “last day of the month”, as well as to allow the scheduled time to be more easily filterable.

I can see purpose for loose recurring events, especially when it comes to subscription renewals. I also see benefit of a recurring event type that is based on previous event’s scheduled time. I’ll call this event type “tight recurring”.

**2. Is introducing a third event type, where events are scheduled based on the previous event’s scheduled time (tight recurrence) feasible and desirable?**

I understand that it’s impossible to guarantee an event will run exactly at its scheduled time... that’s fine. But successive events being scheduled loosely means the start time becomes later and later, until eventually, an event originally scheduled to run at midnight could be running in the middle of the day.

This came up because I was interested in scheduling recurring events to mark the begin and end of a site’s low-traffic hours.

It occurs to me now that perhaps what I’m describing is what `as_schedule_cron_action()` is for.

**3. Do “cron-like” events behave like I’ve described “tight recurring” events?**

**Comment by thenbrent** [comment]
Yes, I believe cron actions are "tight recurring" option you're looking for. They use the cron schedule, which can be specific time, e.g. `0 00 * * *` to run at midnight.

Where cron actions will be "loose", is when the scheduled action is run _after_ the next scheduled, e.g. if you are using a cron schedule like `*/1 * * * *` to recur every minute, and the first action is scheduled to run at `5:00:00`, but actually runs at `5:01:01`, then the 2nd action will be scheduled for `5:03:00`, not `5:02:00`.

**Comment by crstauf** [comment]
Thanks, @thenbrent; I'll experiment with that.

From my perspective, this ticket can be closed, and I'll comment here if the cron-like schedule doesn't work.
