### ISSUE TITLE
2.2.1 `JSON_ERROR_NONE ` PHP 5.2 incompaibility

### ISSUE THREAD

**Issue by mikejolley** [Prospress/action-scheduler#266]
Introduced in 2.2.1, this code is not compatible with PHP 5.2:

https://github.com/Prospress/action-scheduler/commit/a6dd57db06738ce8dd68f6155e7a5198dfdd59fd

Reported here:
https://github.com/woocommerce/woocommerce/issues/23121

@JPry

**Comment by DavidAnderson684** [comment]
N.B. It's not just the constant, but also the method `json_last_error()` which doesn't exist before 5.3.
