### ISSUE TITLE
Usage example defines function eg_log_action_data() twice

### ISSUE THREAD

**Issue by salcode** [Prospress/action-scheduler#288]
In the code sample from [docs/usage.md](https://github.com/Prospress/action-scheduler/blob/master/docs/usage.md) (copied below) the function `eg_log_action_data()` is defined twice.

```php
require_once( plugin_dir_path( __FILE__ ) . '/libraries/action-scheduler/action-scheduler.php' );

/**
 * Schedule an action with the hook 'eg_midnight_log' to run at midnight each day
 * so that our callback is run then.
 */
function eg_log_action_data() {
	if ( false === as_next_scheduled_action( 'eg_midnight_log' ) ) {
		as_schedule_recurring_action( strtotime( 'midnight tonight' ), DAY_IN_SECONDS, 'eg_midnight_log' );
	}
}
add_action( 'init', 'eg_log_action_data' );

/**
 * A callback to run when the 'eg_midnight_log' scheduled action is run.
 */
function eg_log_action_data() {
	error_log( 'It is just after midnight on ' . date( 'Y-m-d' ) );
}
add_action( 'eg_midnight_log', 'eg_log_action_data' );
```

**Comment by salcode** [comment]
I didn't even have time to put together a PR 😀 

Thanks @JPry

**Comment by JPry** [comment]
No worries, thanks for submitting the issue @salcode 🙂

**Comment by JPry** [comment]
@salcode This update has been deployed to the docs site.

<a href='http://pic.pros.pr/cba162c023ce' target='_blank'><img src='http://pic.pros.pr/cba162c023ce/Image%25202019-04-17%2520at%252013.10.59.png' style='display: block;height: auto;width: 100%;'/></a>
