### ISSUE TITLE
Running recurring action scheduled in the past is rescheduled for Now

### ISSUE THREAD

**Issue by rrennick** [Prospress/action-scheduler#293]
See https://github.com/woocommerce/woocommerce/issues/23414#issuecomment-485895442 for steps to reproduce.

This affects the WP post store `save_action` function when it's passed a `$scheduled_date` an interval in the future. The existing actions scheduled date is used instead of the passed `$scheduled_date`.

**Comment by thenbrent** [comment]
In line with comments on #327, I'm reopening this so I can investigate it further.

**Comment by thenbrent** [comment]
I've opened #330 to address the root issue here. I'm going to close this one now in lieu of that.
