### ISSUE TITLE
Broken schedule causes multiple instances of same hook

### ISSUE THREAD

**Issue by rrennick** [Prospress/action-scheduler#296]
This is a followup to #291. While #292 does handle the exception, the action is left in a pending state. If the scheduling function uses `next()` to determine whether to add a recurring schedule of the hook then every time the check runs another instance of the hook will be scheduled.

### To reproduce 

- Disable the SA queue runner by installing https://github.com/Prospress/action-scheduler-disable-default-runner
- Add the following plugin code to a test plugin

```
add_action( 'init', function() {
	if ( ! function_exists( 'as_schedule_recurring_action' ) ) {
		return;
	}

	if ( ! as_next_scheduled_action( 'recurring_test' ) ) {
		as_schedule_recurring_action( time(), WEEK_IN_SECONDS, 'recurring_test', array(), 'test-actions' );
	}
});
```
- Check that the pending action is created
- Update the post_content field of that post to "valid_json_encoded_string" or {"data":"invalid_json"}}.
- Refresh the pending actions screen a few times
- You should see a new recurring action for each refresh

**Comment by lkraav** [comment]
Does this mean one should hold off on upgrading to 2.2.5?

**Comment by rrennick** [comment]
> Does this mean one should hold off on upgrading to 2.2.5?

No, this is just an edge case. If you do have one with a broken schedule you can delete it via the dashboard screen bulk actions.
