### ISSUE TITLE
 Action Scheduler comment filtering never caches

### ISSUE THREAD

**Issue by deltafactory** [Prospress/action-scheduler#30]
According to query debugging, the caching implemented for comments-0 never kicks in.

* https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_wpCommentLogger.php#L123

This may be due to non-strict comparison of the cached value. I'll provide feedback if/when I look into this further.

**Comment by thenbrent** [comment]
> I'll provide feedback if/when I look into this further.

That would be great thanks. Especially if you get a chance before Wednesday when I hope to spend a bit of time on Action Scheduler. :)

**Comment by deltafactory** [comment]
It looks like this is the cause: https://github.com/WordPress/WordPress/blob/master/wp-includes/load.php#L455
```PHP
if ( function_exists( 'wp_cache_add_global_groups' ) ) {
	wp_cache_add_global_groups( array( 'users', 'userlogins', 'usermeta', 'user_meta', 'site-transient', 'site-options', 'site-lookup', 'blog-lookup', 'blog-details', 'rss', 'global-posts', 'blog-id-cache' ) );
	wp_cache_add_non_persistent_groups( array( 'comment', 'counts', 'plugins' ) );
}
```
I'd like to know why these groups are excluded in core. It's easily circumvented by using a new cache group but perhaps shouldn't be.

**Comment by thenbrent** [comment]
It looks like WC has just introduced the use of a transient to work around this: https://github.com/woothemes/woocommerce/pull/11449

Action Scheduler can/should probably do the same.

Interestingly, it also looks like WC from v2.7 onwards will also be indexing the `comment_type` column: https://github.com/woothemes/woocommerce/pull/11651

**Comment by thenbrent** [comment]
I've submitted https://github.com/Prospress/action-scheduler/pull/64/ with a fix for this now, nearly identical to the approach taken by WC as linked to in my previous comment.
