### ISSUE TITLE
Exclude `scheduled-action` post type from WordPress SEO cornerstone content processing

### ISSUE THREAD

**Issue by lkraav** [Prospress/action-scheduler#305]
During eyeballing and deleting some Failed AS jobs today, I noticed Stream unexpectedly logging meta changes for my deleted AS posts:

`Updated "is_cornerstone" of "cxl_institute_user_membership_status_changed" Scheduled Action`

I'm fairly certain AS should ship an "integration" with this filter https://developer.yoast.com/code-documentation/classes/wpseo_cornerstone_filter/ excluding `scheduled-action` post type.

OTOH I'm not 100% which direction the "integration" responsibility should flow in :)

Your thoughts?

**Comment by rrennick** [comment]
> Your thoughts?

Scheduled actions are not a public post type. I would expect cornerstone to exclude any post type that isn't public.
