### ISSUE TITLE
_action_manager_schedule data corrupted

### ISSUE THREAD

**Issue by tillkruss** [Prospress/action-scheduler#307]
I just installed the plugin and when adding jobs I see corrupted data in the post meta table.

<img width="812" alt="Screen Shot 2019-05-13 at 2 20 29 PM" src="https://user-images.githubusercontent.com/665029/57654973-585df500-758a-11e9-864a-03691e108754.png">

```php
as_schedule_single_action(time(), 'submit_ontraport_form', [
    'opf' => trim(filter_input(INPUT_POST, 'opf', FILTER_SANITIZE_NUMBER_INT)),
    'firstname' => trim(filter_input(INPUT_POST, 'firstname', FILTER_SANITIZE_STRING)),
    'email' => trim(filter_input(INPUT_POST, 'email', FILTER_SANITIZE_EMAIL)),
    'page' => trim(filter_input(INPUT_POST, 'page', FILTER_SANITIZE_URL)),
    'user-agent' => $_SERVER['HTTP_USER_AGENT'] ?? null,
], 'ontraport');
```

**Comment by rrennick** [comment]
The `meta_value` in those rows is a serialized `ActionSchedulerSimpleSchedule` object. Ref https://www.php.net/manual/en/function.serialize.php

**Comment by JPry** [comment]
@tillkruss Your data appears to be truncated. As @rrennick mentioned, the schedule data is serialized for insertion into the database. Can you further explain why you think there's a problem with your data?  Can you include the full value of the `meta_value` column?

**Comment by tillkruss** [comment]
Maybe it's TablePlus truncating it. WP CLI seems to read it correctly.

<img width="597" alt="Screen Shot 2019-05-14 at 12 52 32 PM" src="https://user-images.githubusercontent.com/665029/57727828-4f7f2900-7647-11e9-927a-2edc7f6836c2.png">
