### ISSUE TITLE
Call to undefined method ActionScheduler_CronSchedule::interval_in_seconds()

### ISSUE THREAD

**Issue by alanef** [Prospress/action-scheduler#308]
`PHP Fatal error:  Uncaught Error: Call to undefined method ActionScheduler_CronSchedule::interval_in_seconds() in /var/www/html/wp-content/plugins/test/includes/vendor/prospress/action-scheduler/classes/ActionScheduler_wpPostStore.php:25
Stack trace:
#0 /var/www/html/wp-content/plugins/test/includes/vendor/prospress/action-scheduler/classes/ActionScheduler_Abstract_QueueRunner.php(82): ActionScheduler_wpPostStore->save_action(Object(ActionScheduler_Action), Object(ActionScheduler_DateTime))
#1 /var/www/html/wp-content/plugins/test/includes/vendor/prospress/action-scheduler/classes/ActionScheduler_Abstract_QueueRunner.php(68): ActionScheduler_Abstract_QueueRunner->schedule_next_instance(Object(ActionScheduler_Action))
#2 /var/www/html/wp-content/plugins/test/includes/vendor/prospress/action-scheduler/classes/ActionScheduler_QueueRunner.php(80): ActionScheduler_Abstract_QueueRunner->process_action('105893')
#3 /var/www/html/wp-content/plugins in /var/www/html/wp-content/plugins/test/includes/vendor/prospress/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 25
`

I note that a similar issue was noted/fixed? https://github.com/Prospress/action-scheduler/issues/133

Is this related?

**Comment by rrennick** [comment]
Thanks for reporting this.

> Is this related?

No. The code triggering this error is new.

**Comment by alanef** [comment]
I will try and establish the circumstances of the error, it isn't occurring all the time, so it will be a 'combination' event.

**Comment by alanef** [comment]
The circumstances are when you manually runb a recurring event, as it has a scheduled time, this is true
`if ( ! is_null( $scheduled_date ) && $schedule->is_recurring() ) {
				$schedule = new ActionScheduler_IntervalSchedule( $scheduled_date, $schedule->interval_in_seconds() );
			}`

But ->interval_in_seconds() isn't instantiated until the construction of ActionScheduler_IntervalSchedule

**Comment by rrennick** [comment]
> But ->interval_in_seconds() isn't instantiated until the construction of ActionScheduler_IntervalSchedule

Action Scheduler uses an autoloader so you won't see the class file being `require`d.

**Comment by alanef** [comment]
I traced it through in xdebug. 

The first time ActionScheduler_IntervalSchedule is called ( I put a break in the __construct ) in this scenariono ( is repeating has a scheduled date ) it tries to instantiate itself with interval_in_seconds() which hasn't been set before => PHP error

`class ActionScheduler_IntervalSchedule implements ActionScheduler_Schedule {
	/** @var DateTime */
	private $start = NULL;
	private $start_timestamp = 0;
	private $interval_in_seconds = 0;

	public function __construct( DateTime $start, $interval ) {
		$this->start = $start;
		$this->interval_in_seconds = (int)$interval;
	}`

**Comment by rrennick** [comment]
`private $interval_in_seconds = 0;` is a property and 

`public function interval_in_seconds() {` is a method. References to the property are not calling the method.

**Comment by alanef** [comment]
Yes I think I get it, basically as never been loaded as it is autoloaded and had never been requested so the method doesn't exist.

I assume that is all a bit academic as you will just check if the method exists.

**Comment by rrennick** [comment]
> I assume that is all a bit academic as you will just check if the method exists.

Right.

**Comment by alanef** [comment]
Any fix on this?

I did try a naive attempt, but it results in permanently setting the recurrence to every 'now!' whne you manually run the job.

`if ( ! is_null( $scheduled_date ) && $schedule->is_recurring() ) {
				$interval=0;
				if ( method_exists( $schedule, 'interval_in_seconds' ) ) {
					$interval = $schedule->interval_in_seconds();
				}
				$schedule = new ActionScheduler_IntervalSchedule( $scheduled_date, $interval );
			}`

**Comment by thenbrent** [comment]
Thanks for reporting this @alanef and helping diagnose it. This was introduced with #294 and it will be fixed once #327 is merged which is to be included in the next version, which may be either 2.2.6 or 3.0.0.

**Comment by alanef** [comment]
I did try a patch myself but ended up with cron jobs creating extra jobs with interval 0 ( sort of self cloning ) due to my lack of understanding of what the value does.

**Comment by thenbrent** [comment]
Fixed with #327.
