### ISSUE TITLE
Issues with ununsanitized data creating invalid serialized data.

### ISSUE THREAD

**Issue by ChuckMac** [Prospress/action-scheduler#31]
The action scheduler does not seem to handle unsanitized data very gracefully.

Example:

`wc_schedule_single_action( time(), 'test_schedule_out', array( 'test <3' ) );`

This will create an entry with a post title of:

`["test &lt;3&quot;]`

So it replaces the final quote with a sanitized value, and makes the serialized array invalid.

Switching to calling sanitize_text_field beforehand works:

`wc_schedule_single_action( time(), 'test_schedule_out', array( sanitize_text_field('test <3')  );`

`["test <3"]`

**Comment by rrennick** [comment]
Fixed in #312.
