### ISSUE TITLE
Re-run failed actions

### ISSUE THREAD

**Issue by tillkruss** [Prospress/action-scheduler#310]
How can I re-run a failed action?

I don't seem to be able to do it under "Tools -> Scheduled Actions" and I don't see a CLI command.

**Comment by rrennick** [comment]
There isn't a way to re-run a failed action.

**Comment by tillkruss** [comment]
Is that intentional or a missing feature?

Maybe I'm using the action scheduler the wrong way? Should I catch any exceptions when performing an action and schedule a new one?

**Comment by rrennick** [comment]
> Should I catch any exceptions when performing an action and schedule a new one?

Yes, that's how you handle it if you want an action you want to retry.
