### ISSUE TITLE
Redirects attempted within the list table

### ISSUE THREAD

**Issue by johnbillion** [Prospress/action-scheduler#315]
There are a few places where Action Scheduler attempts to perform a redirect from within the list table. None of these redirects work because the headers and a bunch of HTML has already been sent at this point, and this results in a "headers already sent" warning and an abrupt `exit`.

There are redirects in:

1. `ActionScheduler_Abstract_ListTable::process_row_actions()`
2. `ActionScheduler_Abstract_ListTable::process_bulk_action()`
3. `ActionScheduler_Abstract_ListTable::prepare_items()`

None of these redirects work because the `prepare_items()` method of the list table gets called after the admin menu and admin header has been output.

The end result is that performing actions such as searching actions, running an action, cancelling an action, or bulk deleting actions all appear to fail (in fact they don't, and returning to the Scheduled Actions screen confirms this).

**Comment by alanef** [comment]
FYI same issue as https://github.com/Prospress/action-scheduler/issues/151

**Comment by alanef** [comment]
p.s.  I have been looking into this, one strange issue is that WooCommerce implementation when active doesn't have this issue an yet it seems all is the same ...

**Comment by alanef** [comment]
FYI, I have just spent this morning trying to race why it works with WooCommerce active and even when as far as creating a stripped out plugin trying to emulate whet WC does in terms of load sequence. Unfortunately I failed to discover why it works with WC and fails without.  Oh well ...

**Comment by thenbrent** [comment]
This should be fixed with #354. Actions are now processed outside preparing items.
