### ISSUE TITLE
Scope of sheduled actions

### ISSUE THREAD

**Issue by MLnick** [Prospress/action-scheduler#34]
Hey, I'm testing out using action-scheduler to schedule actions that depend on certain WooCommerce classes (e.g. mails). The actions fail with `unexpected shutdown: PHP Fatal error Class ‘WC_Email’ ...` type errors.

What is the scope of actions executed? If I want to access WooCommerce functions (like get products and get orders etc) do I need to manually import all of WooCommerce within the action that I hook into?

Thanks!

**Comment by thenbrent** [comment]
Subscriptions sends renewal order emails on scheduled actions, so those email functions should definitely work (and WC etc. is all loaded).

**Comment by MLnick** [comment]
Ok I've figured out that something else is going on -




If within my plugin class I add my scheduled action hook, and in that function I call something like:




$mail = new WC_Email




That works fine and I can use those functions.




However when I try to instantiate my custom email class which extends WC_Email, that is when I get the error. Weird because clearly the WC_Email class is in scope since I can instantiate directly... 




Any ideas? I can use the WC_Email functions and mailer functions to achieve what I need so it's ok, just really confusing!



—

**Comment by greguly** [comment]
Hmm, what if you load the mailer?

	// load email classes
	WC()->mailer();

**Comment by MLnick** [comment]
Yes that worked!

I can also do `$mail = $mailer->emails['My_Class'];` 

Thanks for the help - not quite sure why this was happening but I guess the email classes had not yet been initialised / included...

**Comment by greguly** [comment]
Glad you got it solved :-)
