### ISSUE TITLE
Fatal error 

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [Prospress/action-scheduler#35]
Fatal error: Call to undefined function wc_next_scheduled_action() in  ....classes\class-wc-subscriptions-manager.php on line 2256.I am getting this error can you please give me some idea, how I can fix it.
```php
	add_action( 'plugins_loaded', 'action_scheduler_register_1_dot_2_dev', 0, 0 );

	function action_scheduler_register_1_dot_2_dev() {
		echo "test";
		exit;
		$versions = ActionScheduler_Versions::instance();
		$versions->register( '1.2-dev', 'action_scheduler_initialize_1_dot_2_dev' );
	}
```

This is where the problem is exist .

**Comment by PrafullaKumarSahu** [comment]
In Class ActionScheduler_Versions changed 
```php
	public function register( $version_string, $initialization_callback ) {
		if ( isset($this->versions[$version_string]) ) {
			return FALSE;
		}
		$this->versions[$version_string] = $initialization_callback;
		return TRUE;
	}
```
   to

```php
	public function register( $version_string, $initialization_callback ) {
		if ( isset($this->versions[$version_string]) ) {
			return FALSE;
		}
		$this->versions[$version_string] = call_user_func ( $initialization_callback );
		return TRUE;
	}
```

**Comment by thenbrent** [comment]
Hi @PrafullaKumarSahu please use the [`bleeding_branch`](https://github.com/Prospress/action-scheduler/tree/bleeding_branch) as that `action_scheduler_register_1_dot_4_dev()` is using version 1.4. 

It also looks like you have extra code in `action_scheduler_register_1_dot_2_dev()` which is causing the function to `exit` before the version of the library is registered. That will cause this issue.

**Comment by PrafullaKumarSahu** [comment]
Hi @thenbrent  thank for your  reply , actually that was causing because my plugin was loaded with plugins_loaded hook,now I am using admin_init hook as woocommerce-subscriptions uses it.This plugin what I have developed is same as woocommerce-subscriptions having a few tweaks to know the woocommerce better .but I have noticed using call_user_function on that also not causing any problem,It is better to use call_user_function or there is some problem with it, could you please explain it.I will be thankful.
