### ISSUE TITLE
Add bulk cancel to table store

### ISSUE THREAD

**Issue by rrennick** [Prospress/action-scheduler#350]
Reference: https://github.com/woocommerce/woocommerce-admin/issues/2766

> That could be addressed in Action Scheduler core itself by introducing a new API to bulk cancel if needed. Custom tables should be much more performant than the existing store for deleting actions, so this may be less needed also.

Plugins using Action Scheduler can schedule actions using an action group associated with the plugin and should be able to bulk cancel all actions in that group or actions with the same hook on plugin deactivation.

**Comment by thenbrent** [comment]
Fixed with #351.
