### ISSUE TITLE
Is it safe to disable comments

### ISSUE THREAD

**Issue by jmau111** [Prospress/action-scheduler#362]
Hi,

we use WordPress, we need to completely disable comments, we notice you are using wp-comments table as logger place.

Will the action scheduler still work without logging or not ?

**Comment by rrennick** [comment]
The latest version is in beta and does not use the comment table.

> Will the action scheduler still work without logging or not ?

If the situation is urgent you could write some custom code that disabled the logging or wrote the log to a file.
