### ISSUE TITLE
WP 4.3 changed row actions, and thus extra actions show up

### ISSUE THREAD

**Issue by javorszky** [Prospress/action-scheduler#38]
Moved from https://github.com/Prospress/woocommerce-subscriptions/issues/619

![](https://cldup.com/cnyacqPmUJ.png)

**Comment by thenbrent** [comment]
This has been fixed with https://github.com/Prospress/action-scheduler/commit/0fe2431667a5d901438c8108f27e85713d70eadf

That will ship in Subscriptions soon once #43 is merged and the bundled AS version is updated.
