### ISSUE TITLE
Fatal error: Call to undefined function wc_next_scheduled_action()

### ISSUE THREAD

**Issue by toddlahman** [Prospress/action-scheduler#39]
I am using action_scheduler_initialize_1_dot_4_dev from the bleeding branch. In fact, I even tried the action-scheduler directory from the Subscriptions 2.0 beta as well, but I still got the Fatal error: Call to undefined function wc_next_scheduled_action() error. I reviewed the following issues:

https://github.com/Prospress/action-scheduler/issues/35
https://github.com/Prospress/action-scheduler/pull/37

I did try using `$this->versions[$version_string] = call_user_func( $initialization_callback );` rather than `$this->versions[$version_string] = $initialization_callback;`, as that made sense, however, the fatal error persisted.

https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_Versions.php#L18

Then I went back into action-scheduler.php thinking perhaps it was just a hook timing issue.

https://github.com/Prospress/action-scheduler/blob/master/action-scheduler.php#L25

I changed:

```
    function action_scheduler_initialize_1_dot_4_dev() {
        require_once('classes/ActionScheduler.php');
        ActionScheduler::init( __FILE__ );
    }
```

to

```
    require_once('classes/ActionScheduler.php');
    ActionScheduler::init( __FILE__ );
```

This allowed the required ActionScheduler.php file to load, despite whatever issue exists along the chain, and the fatal error disappeared. If I get a chance, I will do some additional troubleshooting to find the exact issue, but the fact `action_scheduler_initialize_1_dot_4_dev()` is not being called is the issue. I tested the above on PHP version 5.3.29, 5.4.42, and 5.5.26, and the results were always the same. This issue should not be closed until it is resolved.

**Comment by toddlahman** [comment]
This issue has been fixed with this pull request.

https://github.com/Prospress/action-scheduler/pull/40

**Comment by toddlahman** [comment]
Not sure what the solution is here, but unless I make the changes below, the fatal error persists. Is the version really necessary? Seems like a lot of code for no clear purpose.

````
	function action_scheduler_initialize_1_dot_4_dev() {
		require_once('classes/ActionScheduler.php');
		ActionScheduler::init( __FILE__ );
	}
```

to

```
	require_once('classes/ActionScheduler.php');
	ActionScheduler::init( __FILE__ );
```

**Comment by thenbrent** [comment]
> no clear purpose.

Multiple plugins ship the Action Scheduler library. We need to make sure the latest version of the library is always loaded. We do that with a specific function for loading it. That's the purpose of it.

Making the change you suggest means that _the first version PHP sees_ will be loaded, not the most recent version of the library. Which means if a site has some plugin running a _really old_ version of the library, it may have serious issues for code written to work against the latest version that ships with the latest version and expects that version to be loaded/available (by maintaining backward compatibility we make sure the _really old_ code for the old version works fine even with the new version).

It's possible there is a bug in AS' dependency handling logic, but removing the versioned function just removes version handling completely, which will introduce other issues.

> but the fact action_scheduler_initialize_1_dot_4_dev() is not being called is the issue.

Are you sure it's not being called? Or is it just that you're trying to access it too early? It is attached to `'plugins_loaded'`, so you need to make sure you only access it after that hook.

If it definitely isn't being called, please share the offending code.

**Comment by toddlahman** [comment]
Fixed with https://github.com/Prospress/action-scheduler/pull/41

It turns out that ```add_action( 'plugins_loaded', array( 'ActionScheduler_Versions', 'initialize_latest_version' ), 1, 0 );``` was not even loading ```initialize_latest_version()```. It expects a non-static method. After it did call ```initialize_latest_version()``` in ActionScheduler.php, it was returning ```__return_null```.

I rewrote ActionScheduler.php, and now everything loads and runs as it should with PHP 5.3.29 and above, with no errors.

**Comment by toddlahman** [comment]
Even after the rewrite it only works sometimes, and then fails again, as before. Very odd behavior even with no changes to the code. I've even looked into the autoloader, since I am also using an autoloader in my plugin. I am still getting the same error as before, but it is not clear where the issue is.

**Comment by toddlahman** [comment]
I finally had to change the action-scheduler.php file to the following. The setup I use is almost exactly what Subscriptions uses, and my setup matches other projects I've built without issues. I can't seem to find the solution today, but I can be sure ```action_scheduler_register_1_dot_4_dev()``` won't be called by more than one plugin with the same library. This seems like a suitable solution. Will this approach lead to any issues or conflicts? Here's what I had to use:

```
if ( !function_exists('action_scheduler_register_1_dot_4_dev') ) {

	if ( !class_exists( 'ActionScheduler_Versions' ) ) {
		require_once('classes/ActionScheduler_Versions.php');
		add_action( 'plugins_loaded', array( 'ActionScheduler_Versions', 'initialize_latest_version' ), 1, 0 );
	}

	add_action( 'plugins_loaded', 'action_scheduler_register_1_dot_4_dev', 0, 0 );

	function action_scheduler_register_1_dot_4_dev() {
		$versions = ActionScheduler_Versions::instance();
		$versions->register( '1.4-dev', 'action_scheduler_initialize_1_dot_4_dev' );
	}

	function action_scheduler_initialize_1_dot_4_dev() {
		require_once('classes/ActionScheduler.php');
		ActionScheduler::init( __FILE__ );
	}

	action_scheduler_initialize_1_dot_4_dev();

}
```

**Comment by thenbrent** [comment]
@toddlahman can you send through a WooCommerce System Status log (if you have one)? If you don't have one for the site, can you send through some server config details (like these: https://cloudup.com/c-DwlZDSsHn)?

I'd love to reproduce this, but can't for the life of me see how it would happen atm (I suspect there may be some PHP version dependant quirk at play).

**Comment by toddlahman** [comment]
@thenbrent Would it be okay if I emailed you a copy of the plugin the action scheduler is integrated into, to see if you can figure out what the issue is? I am just not seeing a solution.

**Comment by thenbrent** [comment]
@toddlahman yeah sure. Email it to support@prospress.com so it goes to the group inbox and I'll take a look. If you can include a System Status log that will help a lot too.

**Comment by toddlahman** [comment]
Sent. Thank you @thenbrent

**Comment by thenbrent** [comment]
@toddlahman sorry I didn't get to follow up with this. I'm going to close it now given it's been over a year. If you're still having the issues, feel free to reopen and we can investigate with the newer versions. 🙂
