### ISSUE TITLE
Querying for subscription key and user id is not good enough

### ISSUE THREAD

**Issue by javorszky** [Prospress/action-scheduler#42]
There are a number of really vexing issues with it. Consider this function call: 

```
$actions = wc_get_scheduled_actions( array(
	'args' => array(
		'user_id' => '3',
		'subscription_key' => '202_200'
	),
	'hook' => 'scheduled_subscription_expiration'
) );
```
The resulting SQL query here: https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_wpPostStore.php#L296 will be the following:

```
SELECT p.ID
FROM wp_posts p
WHERE post_type='scheduled-action'
    AND p.post_title='scheduled_subscription_expiration'
    AND p.post_content='{\"subscription_key\":\"202_200\",\"user_id\":\"3\"}'
ORDER BY p.post_date ASC LIMIT 0, 5;
```
The problem? It's the wrong way around! This is stored in the database:
![](https://cldup.com/q9dL7hWpd8.png)

But okay, let's switch it, so now the function call is:

```
$actions = wc_get_scheduled_actions( array(
	'args' => array(
		'user_id' => '3',
		'subscription_key' => '202_200',
	),
	'hook' => 'scheduled_subscription_expiration'
) );
```
The resulting query is:
```
SELECT p.ID
FROM wp_posts p
WHERE post_type='scheduled-action'
    AND p.post_title='scheduled_subscription_expiration'
    AND p.post_content='{\"user_id\":\"3\",\"subscription_key\":\"202_200\"}'
ORDER BY p.post_date ASC LIMIT 0, 5;
```
Still not good.

The user ID is stored as a number, but `json_encode` here: https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_wpPostStore.php#L227 turns `user_id` into a string. It will never match it.

**Comment by javorszky** [comment]
Actually, nevermind the second part. Passing in an actual integer works:

```
$actions = wc_get_scheduled_actions( array(
    'args' => array(
        'user_id' => 3, // so removing the quotes from around this
        'subscription_key' => '202_200',
    ),
    'hook' => 'scheduled_subscription_expiration'
) );
```

**Comment by thenbrent** [comment]
> Actually, nevermind the second part

So can I close this?

**Comment by javorszky** [comment]
The issue that the order is important is still there, ie:

`array( 'user_id' => 3, 'subscription_key' => '123_456' )` will work, but `array( 'subscription_key' => '123_456', 'user_id' => 3 )` will not.

Is that something we want to address?

**Comment by thenbrent** [comment]
> Is that something we want to address?

No. We want to honour the order of the the array as it is passed in.
