### ISSUE TITLE
`wp_unique_post_slug()` overhead on large sites

### ISSUE THREAD

**Issue by jconroy** [Prospress/action-scheduler#44]
Keeping this short and sweet, more as a note / for documentation.

`wp_unique_post_slug()` is called on some action scheduler related wp-cron.php calls when actions are marked complete etc.

On sites with a large number of items in the posts table this adds a substantial overhead  e.g.  

![new relic trace](http://f.cl.ly/items/1l3x1H1n0i413d253c15/Screen%20Shot%202015-12-09%20at%206.43.49%20AM.png)

Looks like its bit of a known bottleneck for large sites http://wordpress.stackexchange.com/questions/119738/can-we-have-a-post-without-a-slug

As the actions aren't really public, calculating a slug/name is not really necessary.

Unfortunately there is no easy way to get around it as it is used within `wp_update_post()` e.g. https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_wpPostStore.php#L563 and the only filters within in are at [the end](https://github.com/WordPress/WordPress/blob/5031ca5c23f68b20fd63fd8370c05e9b0e1af164/wp-includes/post.php#L3675)

An action or filter at the beginning around [here](https://github.com/WordPress/WordPress/blob/5031ca5c23f68b20fd63fd8370c05e9b0e1af164/wp-includes/post.php#L3553) would potentially allow us to hijack and ignore what happens after.

[This trak ticket](https://core.trac.wordpress.org/ticket/21112) may or may not be useful/interesting. Its certainly related.

For more discussion see https://github.com/Prospress/woocommerce-subscriptions/issues/1355

**Comment by toddlahman** [comment]
@jconroy What are you using to measure performance, and generate that chart?

**Comment by javorszky** [comment]
@toddlahman, it's [new relic](http://newrelic.com/) installed on our test server. We have a web pro annual subscription to it.

**Comment by thenbrent** [comment]
This is now being done via `Hybrid_Store` and `Migration_Scheduler` in the custom tables plugins: https://github.com/prospress/action-scheduler-custom-tables/

Any changes to it should be addressed on that repo until #77 is completed, and that code is merged into AS core (which isn't due to happen in the near future).

**Comment by thenbrent** [comment]
Reopening this one, as https://core.trac.wordpress.org/ticket/21112 is now merged so Action Scheduler core can now just tell the slug to be the same as the hook-name and return early while Custom Tables are still in testing.
