### ISSUE TITLE
The screen monitoring in Tool no longer exist

### ISSUE THREAD

**Issue by lflorezgravoc** [Prospress/action-scheduler#49]
I set the WP_DEBUG and it doesn't display the submenu under tools.

**Comment by javorszky** [comment]
Hi @lflorezgravoc!

Can you provide more information about this? We're using action scheduler internally, and it does work with `WP_DEBUG` set to `true`.

* what version of action scheduler are you using?
* what version of wordpress?
* any plugins?

**Comment by lflorezgravoc** [comment]
Actually I stumble upon this repository by checking the Woocommerce Subscription. 
I downloaded (zip file) the files of this repository and I found that there is no ActionScheduler_AdminView.php file under /classes, and no initialization of that class in ActionScheduler.php

I added those from the plugin and it works now.

Action Scheduler: Version: 1.2-dev

Woocommerce Subscriptions: Version: 2.0.4

**Comment by javorszky** [comment]
The version that's included with Subscriptions is on the branch https://github.com/Prospress/action-scheduler/tree/bleeding_merge_master.

**Comment by lflorezgravoc** [comment]
Oh, thanks for immediate answer.

Awesome plugin.
