### ISSUE TITLE
Action status gets lost

### ISSUE THREAD

**Issue by javorszky** [Prospress/action-scheduler#50]
Actions currently can have 4 (5) statuses:
- pending
- completed
- in-progress
- failed
- (trashed)

When you try to fetch and then resave the actions, it will be either of these two:
- pending
- completed

This is because the `ActionScheduler_Action` base class has no concept of `status`, and it's either just not finished, or finished, if the class is extended and overwritten, as is the case with `ActionScheduler_FinishedAction`. That's all handy, but from a migration point of view absolutely useless, as `failed` actions would be marked `completed`.

The question is whether this needs to be amended in the base class, or whether it should be handled in a new compatibility layer on top of the `wpPostStore` class when saving / fetching actions.

**Comment by thenbrent** [comment]
> whether it should be handled in a new compatibility layer on top of the wpPostStore class when saving / fetching actions.

Yep, it should be handled there, though this is obviously a very old question so not sure it still applies. 🙂
