### ISSUE TITLE
scheduler create four pending schedule action when i run single time. 

### ISSUE THREAD

**Issue by ganeshpawarck** [Prospress/action-scheduler#52]
hello 

i have just installed action scheduler plugin and simply run the following code but my problem is that , i can  see database post table there are four entry for same action ?

`$action_hook="next_payment_membership";
$action_args    = array( 'post_id' => "123" );
$next_payment_date = date( 'Y-m-d H:i:s',strtotime('+1 year'));
wc_schedule_single_action( $next_payement_date,$action_hook, $action_args );`

please suggest me ?

![github](https://cloud.githubusercontent.com/assets/19894475/15993720/57bc2d8a-310c-11e6-897d-c99a1269293b.png)

**Comment by javorszky** [comment]
Hi @ganeshpawarck!

Where do you call `wc_schedule_single_action` from? If you look at the `post_date` and `post_date_gmt` fields, you can see that they are a few seconds apart, which means whatever hook you have it running on runs 4 times?

**Comment by ganeshpawarck** [comment]
hello @javorszky  
Thank you very much for your reply , i am running  wc_schedule_single_action on wordpress template page but if run on function file its working fine . leave it my issue has resolved .
