### ISSUE TITLE
Dublicate Payment generated (2 times).

### ISSUE THREAD

**Issue by rvpatel** [Prospress/action-scheduler#58]
Your code used in woocommerce_subscription. (I have checked with your latest code action-scheduler)

I have purchase 2 subscription **1191,1993** now recurring payment execute after 1 month.
Issue occurred  "1993" number order in created 2 times payment. 

http://imgur.com/a/TVjic

**This issue occurred when any user 2 subscriptions recurring same time generated.** 

WooCommerce Authorize.net CIM Gateway 2.0.2
WooCommerce Subscriptions 2.0.18
WooCommerce 2.4.6

**Comment by thenbrent** [comment]
Hi @rvpatel. Please open an issue at WooCommerce and we can help you there: https://woocommerce.com/my-account/create-a-ticket/

This repository is for Action Scheduler Issues only, not issues relating to its use in Subscritpions or other plugins.

**Comment by rvpatel** [comment]
@thenbrent  Recurring payment execution flowed by Action-scheduler.
