### ISSUE TITLE
Duplicate action scheduled after processing an action that was originally scheduled when PHP's timezone was being incorrectly changed to be in the past

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler#68]
When scheduling a single action:

1. `wc_schedule_single_action()` calls
1. `ActionScheduler_ActionFactory::single()`, which
1. creates an instance of `ActionScheduler_SimpleSchedule`, then sends that to
1. `new ActionScheduler_Action()` as the action's schedule
1. `ActionScheduler_ActionFactory::store()` then calls
1. `ActionScheduler_wpPostStore::save_action()` which calls
1. `ActionScheduler_wpPostStore::save_post_schedule()` which stores a serialized version of this schedule object in post meta with the meta key `'_action_manager_schedule'`
1. because the `ActionScheduler_SimpleSchedule` uses a timestamp to store its date value, when the timezone has changed, the timestamp's value is effectively corrupted (FWIW, based on the comments on `ActionScheduler_SimpleSchedule::__sleep()`, it looks like this issue could be simply because of PHP 5.2 compatibility… because otherwise `ActionScheduler_SimpleSchedule::$date` would be serialised, which includes the timezone, instead of saving/loading a timestamp, which doesn't)
1. Later on, when `ActionScheduler_QueueRunner` runs the action via `ActionScheduler_QueueRunner::process_action()`, it calls
1. `ActionScheduler_QueueRunner::schedule_next_instance()`, which checks for a next scheduled time using `$action->get_schedule()->next( as_get_datetime_object() )`;  however,
1. `ActionScheduler_SimpleSchedule::next( $after )` will return the `_action_manager_schedule` value if it’s `<` the `$after` param, and because `ActionScheduler_QueueRunner::schedule_next_instance()` passes the current (UTC) time as the `$after` param, whenever the `_action_manager_schedule` value is `<` the current time, a new action will be rescheduled, which means
1. **If the timezone has been changed to result in a UTC timestamps being less, a duplicate action will always be scheduled**

### Example `_action_manager_schedule` Value

```
O:30:"ActionScheduler_SimpleSchedule":1{s:41:"ActionScheduler_SimpleScheduletimestamp";s:10:"1480682770";}
```

### Possible Fixes

1. change the [`$next = $action->get_schedule()->next( as_get_datetime_object() )` call](https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_QueueRunner.php#L108) to check against the scheduled time with something like: `$next = $action->get_schedule()->next( $action->get_schedule()->next() )` (the issue is that we're currently checking against the current time, which causes problems when the timezone has been changed. It feels redundant, but it looks like the only way to have “control” over the comparisons used, anything else, and we’re comparing to a date/time in a different timezone if the timezone is changed). This will likely break actions which actually having a recurring schedule.
1. just don’t give single actions a schedule (the `next()` function feels meaningless on a single action), but I’m 99% sure this will break other things

**Update 7 December:** I realised @mattallan identified this exact issue during the initial timezone PR review: https://github.com/Prospress/action-scheduler/pull/43#issuecomment-218951166

**Comment by krbvroc1** [comment]
Why not just store timestamps in UTC? Using universal coordinated time handles issues of comparing things in different timezones. Comparisons between dates can be made using the local timezone.

**Comment by thenbrent** [comment]
@krbvroc1 timestamps are stored in UTC.

**Comment by krbvroc1** [comment]
@thenbrent And DateTime objects are also saved using UTC also? If so then then I guess I am not following what the issue, sorry.

I always create DateTime objects by passing ``` new DateTimeZone( 'UTC' ) ```
And when I want to compute with it, I use ```setTimezone( new DateTimeZone( get_option( 'timezone_string' ) ) );``` so things are computed with the local timezone.

**Comment by thenbrent** [comment]
> If so then then I guess I am not following what the issue is, sorry.

@krbvroc1 it's a complex issue that has a lot of backstory I haven't included here for the sake of brevity. It's very unlikely this issue is affecting your site, and it doesn't affect 99.99% of sites running Subscriptions/Action Scheduler.

The root problem is that some WordPress sites have 3rd party code calling `date_default_timezone_set()` and changing the PHP timezone (which is normally UTC). This lead  (past tense) to some date/times being incorrectly calculated because they would include a UTC offset when they were already in UTC (the code causing this has now been fixed up in Subscriptions v2.1 which safeguards against timezone changes). So even though we _think_ we have the unchanging, UTC timestamp for a specific schedule, we actually have a UTC timestamp which will be different to the current UTC timestamp if the site is no longer calling `date_default_timezone_set()`, or is calling it to change PHP to a different timezone again, at the time the action is run.

> I always create DateTime objects by passing new DateTimeZone( 'UTC' )

Yep, which is the most robust way to do it, and the way Action Scheduler does it now (see #43), and Subscriptions v2.1+. But the `'_action_manager_schedule'` timestamp could well have been set before this, so we need to work with that timestamp somehow.

I had a 3rd item in the _Possible Fixes_ that I now realise wouldn't be a fix at all and may have been confusing the matter, so I've removed that. I'm still looking into the other two for feasibility.

**Comment by krbvroc1** [comment]
@thenbrent - Ahh I see, thanks for the explanation. I wasn't really concerned it was going to affect my site, I was just trying to understand and maybe be helpful. Dealing with all the legacy/compatibility use cases is always a hassle. I think some older versions of Wordpress/PHP may have even required setting the timezone but shouldn't any longer. 3rd party developers search the net for programming examples and perpetuate these bad habits. Again, thanks the explanation.

**Comment by thenbrent** [comment]
@krbvroc1 no problem, thanks for looking to help. 🙂

**Comment by james-allan** [comment]
@thenbrent I can't think of another alternative solution to this apart from the 2nd possible fix you listed or something similar. 

From our discussion in slack the other day, I think we pretty much ruled out the 1st possible fix because it wouldn't work for interval schedules. I haven't actually tested it, but following it through I think it would only ever return the scheduled start and then the first recurring (`start + interval`) and it will then continue doing this in future. 

For `next()` to work for all schedule objects (as they are) we basically need to pass a date that represents the current time but, like you said, because we don't know the timezone the timestamp is in, we can't be sure how it will interact with it.  

So we either have to change the simple schedule version of `next()` like you suggested or we add a filter so third parties can prevent `next()` from scheduling a new instance.

**Comment by thenbrent** [comment]
@james-allan looking into it, 2 won't work either, because things like `wc_next_scheduled_action()` rely on `$job->get_schedule()->next()` to get the next scheduled date, so it needs to return that.

Taking a step back, the root of the problem is that a _Single_ action is rescheduled by the queue runner. Regardless of the cause of that here, which is timezone changes, that shouldn't happen. An action created as a _Single_ action should only ever be run once by the queue runner.

So a much simpler solution is to make sure `schedule_next_instance()` never reschedules a _Single_ action. That deals with this issue while ignoring the complexity of `next()` & timezones.

We can do that by checking if `$action->get_schedule()` is a `ActionScheduler_SimpleSchedule` instance. It breaks some of the nice architecture of AS, because it's explicitly checking an object type in a class which previously has no knowledge of that object type, but it will fix this issue and potentially others (including for example, the way [2 actions are created when manually triggering an action via the admin UI](https://docs.woocommerce.com/document/testing-subscription-renewal-payments/#section-4)).

I'll push up a test version of that now and we can test it out. I've run the unit tests on it locally and they got the 💚 .
