### ISSUE TITLE
Migrate existing scheduled actions to custom tables

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler#78]
Figure out how to migrate to the new data stores from #77, taking existing scheduled actions in the old custom post type schema into account.

This could involve either a database migration, and/or running the two data stores side-by-side indefinitely, both of which have pros and cons, so also open to other ideas.

We're also aiming to migrate Subscriptions data to custom tables within 12 months, so it probably makes sense to align that migration. WooCommerce core will also be migrating to custom tables, so there's a few balls to juggle on this item.

**Comment by thenbrent** [comment]
Some additional notes on this topic to share lessons learned I've learned and also an important change to my above comment.

### Speed vs. Reliability

Database migrations that can move a large amount of data quickly on any host are extremely difficult to do reliably.

In my first attempts to migrate data, I tried to migrate everything as quickly as possible in a background request. That meant resource intensive queries, with large data sets being read/written. This didn't work on cheap hosts.

I can't recall the exact issues, but it was a specific MySQL configuration rather than the obvious PHP memory limit or script timeout problems. I can dig up the problem if it will help. But after those attempts, I generally tried to avoid doing migrations in a few very complex, large but fast queries.

In later migrations, I used Ajax loops to migrate smaller chunks of data. This worked on all hosts, but had the obvious implication of being extremely slow on very large sites (migration could take more than 12 hours on some sites... though to its credit, the ajax loop would continue to work for that long). Importantly, the UI on these had feedback both on expected time to complete the migration, and time it was taking to complete each batch. Example UI: https://cl.ly/153Y37241v27

To overcome limitations with both of the above approaches, the best options I see (neither of which are tested, nor perfect) are:

1. offer a _default_ migration path using an Ajax loop so that there is a slow, but reliable option for smaller stores with cheaper hosting, but also offer a **WP-CLI command** to run the migration as quickly as possible for large hosts where Ajax loops are unfeasibly slow (obviously a WP-CLI command isn't feasible for most small site admins, but larger sites usually access to developers and/or budget who could run the commands)
1. avoid migration, and instead run the two data stores side-by-side indefinitely, perhaps eventually running a migration a year or more in the future after _most_ data would have been migrated to the new store. This is a terrifying prospect, especially for Action Scheduler where items may be scheduled years in advance, as it doubles maintenance. It does reduce the risks inherent in database migrations in the short term though.

### Disabling WP-Cron and Admin Access

When migrating subscription data, it was always important to make sure no renewals were initiated before the migration had completed. The same issue is present with Action Scheduler. No queues should be initiated until all the data is migrated (if it needs to be migrated).

To do this, Subscriptions will [block WP-Cron for 9 minutes using the `'doing_cron'` transient](https://github.com/Prospress/woocommerce-subscriptions/blob/master/includes/upgrades/class-wc-subscriptions-upgrader.php#L124). This is done _every time the Subscriptions plugin is loaded with an out-of-date version_. That ensures its lock is refreshed constantly and WP-Cron is not allowed to run until the upgrade has completed.

### Versioning of Data

An important consideration I didn't include above is that Action Scheduler is a library, and therefore, may have multiple different versions of the codebase installed on any site.

So far, it handles this gracefully by only loading the latest version. But what happens if:

1. Plugin _X_ is activated on a site, it uses Action Scheduler v1.5
1. 12 months later, after many actions have been scheduled for plugin _X_ in Action Scheduler v1.5, Plugin _Y_ is activated on the site, it uses Action Scheduler v2.0, so  **data is migrated to custom tables**
1. a few days later, Plugin _Y_ is deactivated on the site, but plugin _X_ remains activate and expecting to be able to use Action Scheduler v1.5's data store

### Migrating Subscriptions to Custom Tables 

I said in the initial description:

> We're also aiming to migrate Subscriptions data to custom tables within 12 months, so it probably makes sense to align that migration

This is no longer the case. Instead, we are planning to develop and release a separate plugin that implements a custom data store (which uses custom tables) for subscription data. We plan to run that on a number of large sites before migrating the code in Subscriptions core, so that migration won't happen within 12 months. It's likely to be 2 or more years.

One advantage of this approach is that we can exclusively use WP-CLI to migrate the data on those large sites because we can offer a concierge service to migrate to it.

This sort of implements a hybrid of the options outlined above for balancing speed/reliability, but it avoids having two separate data stores on the one site.

It would be possible to use the Action Scheduler custom tables _only_ in that plugin. But as Action Scheduler is also used in other plugins, for things like scheduled emails, I think it probably makes sense to treat it separately.

**Comment by jbrinley** [comment]
Thanks for all the info. For the migration, my initial inclination was to set up actions in the action scheduler itself. It could migrate small batches in the background, with a priority on migrating actions that are due or nearly due so that they are available in the new tables when their scheduled time arrives. Possibly with a WP CLI command to expedite the whole process should a site administrator be so inclined. We could certainly build a migration UI and run it through admin-ajax, but I'm not really sure what it would add when we already have this lovely job scheduling system.

> Plugin Y is deactivated on the site, but plugin X remains activate and expecting to be able to use Action Scheduler v1.5's data store

That's quite a pickle. Some other options, on top of maintaining two data stores with a store defined per action...

* Migrate the data, but provide a standalone plugin that can revert the migration
* Release custom tables as a standalone plugin. Action scheduler can continue as-is for most users, but for sites interested in improved performance, this add-on would create the new tables and migrate the data, in a way that would continue to work with version 1.5 (other than the admin UI, which is not using the API)
* Make the new data store strictly opt-in, via a filter or a constant
* Create this as a new library, and make sure not to step on any names from the old library

**Comment by thenbrent** [comment]
> my initial inclination was to set up actions in the action scheduler itself. It could migrate small batches in the background

I think that will work nicely. 👍 

There is one hurdle to address though...

> We could certainly build a migration UI and run it through admin-ajax, but I'm not really sure what it would add when we already have this lovely job scheduling system

The reason we did that with Subscriptions is because the data couldn't accurately be displayed or modified until the migration was complete. We even went so far as to block admins from accessing all `/wp-admin/` screens to avoid those issues.

I agree, that is not necessary with Action Scheduler.

That said, blocking the admin (as well as blocking WP-Cron) did give us one other major benefit - it **avoided data being corrupted halfway through migration due to events changing that data**. That is something that will need to be addressed in other ways here.

Specifically, consider the following use case:

1. Action Scheduler begins migration to custom tables
1. before that data is fully migrated, the store owner suspends subscription with ID 123, which means its `scheduled_subscription_payment` and `scheduled_subscription_expiration` actions need to be unscheduled
1. Subscriptions calls `wc_unschedule_action()` to unschedule them, this attempts to unschedule them from the new data store (because the code using the new data store is active), but they are not found in there, so they are not unscheduled
1. the migration query finishes migrating the data from the old tables, including the scheduled actions for subscription 123, even though they should no longer be scheduled

A similar, though rarer, case arises if the scheduled actions change at the same time they are in the process of actually being migrated (i.e. a batch of actions is claimed for migration, before that batch is completely migrated, the actions are modified).

> Release custom tables as a standalone plugin.

I think that's probably the best approach for v1.0 of this for all the same reasons we're going to do it with Subscriptions itself (I'll avoid listing them for now to reduce the size of this already long response, but happy to share if it would help 🙂 ).

> (other than the admin UI, which is not using the API)

We will fix that up to make sure the admin UI is updated to use the data store instead of default UI for CPTs. I haven't asked you to do that because it's my fault it doesn't use the datastore already. Its my mess so I'll clean it up! 🙂

**Comment by jbrinley** [comment]
> > Release custom tables as a standalone plugin.
> I think that's probably the best approach for v1.0 of this

👍  I'll work towards that, then. I'll likely find a handful of adjustments I'll need to make to the main library, where it's not so extensible as I had intended. But I'll isolate as much as I can in a separate plugin. Do you want to create a separate repository here for that?

**Comment by thenbrent** [comment]
> I'll likely find a handful of adjustments I'll need to make to the main library

No problem. We'll definitely be releasing an updated version to the main library for other reasons anyway (like updating the admin UI).

> Do you want to create a separate repository here for that?

I've just created: https://github.com/Prospress/action-scheduler-custom-tables/

You can view an invite to be a collaborator on it with _Admin_ permissions here: https://github.com/Prospress/action-scheduler-custom-tables/invitations (feel free to rename or make any other changes too).

It's a public repo for now, but if you'd prefer to develop in Private feel free to change it.

**Comment by thenbrent** [comment]
Work on this now underway in https://github.com/Prospress/action-scheduler-custom-tables/, in particular, the `migration` branch: https://github.com/Prospress/action-scheduler-custom-tables/tree/migration

**Comment by thenbrent** [comment]
Closing this as it is being handled nicely in custom tables via both a `Hybrid_Store` and migration routine.
