### ISSUE TITLE
Detect and Handle "Abandoned Actions"

### ISSUE THREAD

**Issue by barryhughes** [Prospress/action-scheduler#805]
Scenario:

* Plugin Foo adds a recurring/cron action with the hook `bar`.
* Plugin Foo is removed (and either does not perform clean-up or does not have the opportunity to do so).
* Action Scheduler will continue to execute and complete action `bar` and, each time, will create a replacement action (according to the specified schedule), *even though Plugin Foo is no longer present and no callbacks for 'bar' are being called.*

✍🏽 [Relevant queue runner code](https://github.com/woocommerce/action-scheduler/blob/3.4.0/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php#L50-L80) | Internal link for further context: p9o2xV-1UT-p2

---

### Possible solution

- WP functions `do_action()` and `do_action_ref_array()` return void: they don't let us know if any callbacks were actually called.
- We can however test before hand if any callbacks are registered, using `has_action()`.
- By using this to detect an absence of callbacks, we could skip triggering the action and instead mark it as failed.
- From there, some logic (which could be added to the [Queue Cleaner](https://github.com/woocommerce/action-scheduler/blob/3.4.0/classes/ActionScheduler_QueueCleaner.php)) could identify recurring/cron actions where the most recent _x_ attempts were marked as failures and then cancel the action completely.

I don't know exactly what threshold makes sense for _x_ ... but it can anyway be made configurable or filterable. 

This would potentially solve problems where recurring actions continue to be perpetuated even when the code that created them no longer exists (a problem that is exacerbated by the fact that race conditions, documented elsewhere, may in some cases lead to duplicate recurring actions building up over time).

**Comment by johnbillion** [comment]
One problem I noticed when implementing this same detection in [WP Crontrol](https://wordpress.org/plugins/wp-crontrol/) is some plugins only call `add_action( ... )` for their cron event when `DOING_CRON` is true, which means it can look like a hook has no actions but in fact there is when the event runs. There's no way to handle this situation, just worth bearing in mind (and reporting to plugin authors if you spot any instances of this).

**Comment by barryhughes** [comment]
Thanks—yes, that's a good call-out.
