### ISSUE TITLE
Table Order by Default

### ISSUE THREAD

**Issue by kc9ryt** [Prospress/action-scheduler#808]
Is there a way to change the admin page so that the table info orders by the scheduled date or the most recent job instead of the order in which the jobs were ran by default?

**Comment by peterfabian** [comment]
Hi @kc9ryt !

You can change the order of the actions by clicking on the table header for the column you want the sorting to apply to, as you can see in the picture below:
![Screenshot 2022-04-05 at 13 13 05](https://user-images.githubusercontent.com/2207451/161741906-395d3d31-16b3-4adb-ac3f-c30610e38104.png)

Please note that once you click to change the default order, this also changes the URL, so you can bookmark this page and it will remember the ordering when you visit it via your bookmark. Hope that helps!
