### ISSUE TITLE
action_scheduler/migration_hook (action-scheduler-migration) is reverting setting

### ISSUE THREAD

**Issue by FATCHIP-GmbH** [Prospress/action-scheduler#809]
Hi,

as mentioned in the Wordpress forum, I need to get rid of action_scheduler/migration_hook (action-scheduler-migration). 
Every time this action is called and completed, setting are reverted and the logo disappears. Since under recurrence I see “Non-repeating”, I thought this will just be done once and that was it. But sadly no. At the moment I have 15 pages full with entries in Scheduled Actions.
I know this is probably not a bug but a settings issue, but I can't find any solution.
WooCommerce: Version 6.3.1
Wordpress: Version 5.9.3

Help is really appreciated!

Kind regards,
Mark

**Comment by Konamiman** [comment]
Hi @FATCHIP-GmbH, thanks for your report. Could you please post a [WooCommerce status report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/) so that we have more information about your setup? This will help us in troubleshooting your issue.

**Comment by FATCHIP-GmbH** [comment]
Hi @Konamiman,
thanks for the reply. 

This is the status report:
`
### WordPress Environment ###

WordPress address (URL): https://www.tradebyte.io
Site address (URL): https://www.tradebyte.io
WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 6.9.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.28
PHP Post Max Size: 50 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.15-MariaDB-0+deb11u1
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.3.1
WC Database Prefix: wp_
Total Database Size: 62.29MB
Database Data Size: 48.71MB
Database Index Size: 13.58MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_borlabs_cookie_consent_log: Data: 0.42MB + Index: 0.14MB + Engine InnoDB
wp_borlabs_cookie_content_blocker: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_borlabs_cookie_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_borlabs_cookie_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_borlabs_cookie_script_blocker: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_submissions: Data: 0.05MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 3.52MB + Index: 4.55MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.09MB + Index: 0.30MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_icwp_wpsf_at_logs: Data: 2.02MB + Index: 0.34MB + Engine InnoDB
wp_icwp_wpsf_at_meta: Data: 2.02MB + Index: 0.39MB + Engine InnoDB
wp_icwp_wpsf_botsignal: Data: 0.41MB + Index: 0.06MB + Engine InnoDB
wp_icwp_wpsf_events: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_icwp_wpsf_ips: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
wp_icwp_wpsf_ip_lists: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_icwp_wpsf_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icwp_wpsf_reports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icwp_wpsf_req_logs: Data: 4.02MB + Index: 0.59MB + Engine InnoDB
wp_icwp_wpsf_resultitems: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icwp_wpsf_resultitem_meta: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_icwp_wpsf_scanitems: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icwp_wpsf_scanresults: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icwp_wpsf_scans: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_icwp_wpsf_sessions: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_icwp_wpsf_user_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lightbox_photoswipe_img: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.02MB + Index: 0.06MB + Engine InnoDB
wp_options_220323: Data: 2.52MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 17.52MB + Index: 3.03MB + Engine InnoDB
wp_posts: Data: 5.52MB + Index: 0.39MB + Engine InnoDB
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_update_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.22MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 5
acf-field-group: 3
attachment: 298
custom_css: 1
customize_changeset: 3
documentation: 179
elementor_font: 1
elementor_library: 13
nav_menu_item: 35
oembed_cache: 1
page: 33
post: 2
postman_sent_mail: 250
product: 17
revision: 1299
sp_wps_shortcodes: 2
woocarousel: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

TB.One: by rb-media.com – 0.1
Advanced Custom Fields PRO: by Delicious Brains – 5.11.4
AJAX Thumbnail Rebuild: by junkcoder
ristoniinemets – 1.13

Borlabs Cookie - Cookie Opt-in: by Benjamin A. Bornschein
Borlabs – 2.2.35

Breadcrumb NavXT: by John Havlik – 7.0.2
Classic Editor: by WordPress Contributors – 1.6.2
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.2.3
Disable Comments: by WPDeveloper – 2.3.4
Elementor Pro: by Elementor.com – 3.2.2
Elementor: by Elementor.com – 3.5.6
Essential Addons for Elementor: by WPDeveloper – 5.0.10
Filenames to latin: by webvitaly – 2.7
Lightbox with PhotoSwipe: by Arno Welzel – 3.4.2
Max Mega Menu: by megamenu.com – 2.9.5
Popup Trigger URL for Elementor Pro: by Suki WordPress Theme – 1.0.5
Post SMTP: by Yehuda Hassine – 2.0.24
WooCommerce Product Carousel Slider: by wpWax – 3.3.5
PublishPress Authors: by PublishPress – 3.16.0
rb media Core Plugin: by rb-media.com – 1.5.2
rb media DSGVO-Plugin: by rb-media.com – 0.4.10
Zalando Usercentrics by rb media: by Bo / rb media – 1.1
Simple Author Box: by WebFactory Ltd – 2.45
Simple Custom Post Order: by Colorlib – 2.5.6
User Role Editor: by Vladimir Garagulya – 4.61.2
WebP Express: by Bjørn Rosell – 0.25.0
WooCommerce Shipping & Tax: by WooCommerce – 1.25.25
WooCommerce: by Automattic – 6.3.1
WP Client Reports: by SwitchWP – 1.0.12
Shield Security: by Shield Security – 14.1.7
WP Super Cache: by Automattic – 1.7.7
XML Importer: by rb-media.com – 0.1

### Inactive Plugins (1) ###

Duplicate Page: by mndpsingh287 – 4.4.8

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #2780 - /shop/
Cart: #2781 - /warenkorb/
Checkout: #2782 - /kasse/
My account: #2783 - /mein-konto/
Terms and conditions: ❌ Page not set

### Theme ###

Name: tbio-child Fatchip
Version: 1.0.0
Author URL: https://www.fatchip.de/
Child Theme: ✔
Parent Theme Name: Tradebyte tb.io
Parent Theme Version: 1.0
Parent Theme Author URL: https://www.rb-media.com
WooCommerce Support: ✔

### Templates ###

Overrides: tbio-child/woocommerce/archive-product.php version - is out of date. The core version is 3.4.0
tbio-child/woocommerce/cart/cart.php
tbio-child/woocommerce/content-single-product.php
tbio-child/woocommerce/single-product/meta.php
tbio-child/woocommerce/single-product/short-description.php
tbio-child/woocommerce/single-product/tabs/description.php
tbio-child/woocommerce/single-product/tabs/tabs.php
tbio-child/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 92
Oldest: 2022-03-08 10:20:12 +0100
Newest: 2022-04-07 13:18:01 +0200


### Status report information ###

Generated at: 2022-04-07 13:18:21 +02:00
`
Hopefully this helps!

Thanks for looking into this.

Kind regards,
Mark

**Comment by peterfabian** [comment]
Hey, thanks for the status report.

Based on that, it seems that all actions have been migrated, thus it should be safe to unschedule the migration action. However, based on what you describe, it seems quite strange that these symptoms ("setting are reverted and the logo disappears") would be caused by the hook.

What I'd suggest is that you try to manually unschedule those actions, if they are still pending. You can use the following code snippet for it (and use the [code snippet plugin](https://wordpress.org/plugins/code-snippets/) to run it):
```
as_unschedule_all_actions( 'action_scheduler/migration_hook' )
```

Then, please try to [resolve conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/) by deactivating other plugins and activate them one by one to see if you notice the settings getting reverted.

If this still doesn't help, please send us a screenshot of the most recent completed actions and also pending/planned actions. Thanks.

**Comment by peterfabian** [comment]
Also, may we know which settings do you see reverted? All of them, or only some? Thanks!

**Comment by FATCHIP-GmbH** [comment]
Hi, 
sorry for the late reply but I was sick.

I asked a colleague of mine to look into your suggestion and to try it.

Regarding the settings:
Every time the action_scheduler/migration_hook is executed the logo disappears, settings for Security Shield is reverted, setting for customer report ist reverted, all keys for pro plugins are gone. These are the things which are the main concern.

**Comment by peterfabian** [comment]
Thanks for those details. However, that doesn't really bring us closer to reproduction. We see no real reason why the migration hook would change any settings, that makes very little sense. So if you have the capacity to investigate and get to the bottom of this in your setup, we'd be happy to fix any bugs you can reproduce. Otherwise it seems like an isolated incident and we'll probably need to close the issue (and we're happy to reopen if we get more reports/more specific info).

**Comment by FATCHIP-GmbH** [comment]
Hi,
Thank you very much for your support. I am closing the issue. The developer was able to exclude the action-scheduler. The execution of the migration-hook and the resetting of the settings just happened to happen at the same time. We still don't know what triggers the reset, but at least it's not the migration-hook.
