### ISSUE TITLE
Fatal error if timestamp passed to datetime is accidentally a float and not an integer

### ISSUE THREAD

**Issue by unfulvio** [Prospress/action-scheduler#81]
This is not really a bug in Action Scheduler but it's an interesting one, you might want to evaluate whether to introduce some type casting to help preventing it.

I had a case where the timestamp was calculated as a median between two timestamps `(a + b) / 2`. This resulted in a timestamp ending in a `.5` which generated the error `DateTime::__construct(): Failed to parse time string (@1497950844.5) at position 12 (5): Unexpected character`

Full stack below:

<pre>
 DateTime::__construct(): Failed to parse time string (@1497950844.5) at position 12 (5): Unexpected character - /srv/www/skyverge/htdocs/wp-content/plugins/woocommerce-memberships/lib/prospress/action-scheduler/functions.php:183 
#13 /srv/www/skyverge/htdocs/wp-content/plugins/woocommerce-memberships/lib/prospress/action-scheduler/classes/ActionScheduler_ActionFactory.php:16 - as_get_datetime_object(1497950844.5)
#12 /srv/www/skyverge/htdocs/wp-content/plugins/woocommerce-memberships/lib/prospress/action-scheduler/functions.php:18 - ActionScheduler_ActionFactory->single('wc_memberships...', Array[1], 1497950844.5, 'woocommerce-me...')
#11 /srv/www/skyverge/htdocs/wp-content/plugins/woocommerce-memberships/includes/class-wc-memberships-user-membership.php:730 - wc_schedule_single_action(1497950844.5, 'wc_memberships...', Array[1], 'woocommerce-me...')
#10 /srv/www/skyverge/htdocs/wp-content/plugins/woocommerce-memberships/includes/class-wc-memberships-user-membership.php:335 - WC_Memberships_User_Membership->schedule_expiration_events(1497974400)
#9 /srv/www/skyverge/htdocs/wp-content/plugins/woocommerce-memberships/include…dmin/meta-boxes/class-wc-memberships-meta-box-user-membership-data.php:581 - WC_Memberships_User_Membership->set_end_date('2017-06-20 16:...')
#8 /srv/www/skyverge/htdocs/wp-content/plugins/woocommerce-memberships/includes/admin/meta-boxes/abstract-wc-memberships-meta-box.php:658 - WC_Memberships_Meta_Box_User_Membership_Data->update_data(6312, WP_Post)
#7 /srv/www/skyverge/htdocs/wp-includes/class-wp-hook.php:300 - WC_Memberships_Meta_Box->save_post(6312, WP_Post)
#6 /srv/www/skyverge/htdocs/wp-includes/class-wp-hook.php:323 - WP_Hook->apply_filters(NULL, Array[3])
#5 /srv/www/skyverge/htdocs/wp-includes/plugin.php:453 - WP_Hook->do_action(Array[3])
#4 /srv/www/skyverge/htdocs/wp-includes/post.php:3510 - do_action('save_post', 6312, WP_Post, true)
#3 /srv/www/skyverge/htdocs/wp-includes/post.php:3583 - wp_insert_post(Array[67], false)
#2 /srv/www/skyverge/htdocs/wp-admin/includes/post.php:378 - wp_update_post(Array[65])
#1 /srv/www/skyverge/htdocs/wp-admin/post.php:193 - edit_post()
</pre>

I can easily rectify this by casting the float resulting from the median into an integer. I was wondering if you'd prefer to harden Action Scheduler as well to prevent these cases from ever showing. Feel free to close as well.

Cheers!

**Comment by thenbrent** [comment]
hey @unfulvio, I'm not sure what we could do to address this in AS. The only thing I'd really be willing to do is throw an exception for invalid arguments, which is going to end up with the same result. There's no way for AS to know based on a float or other invalid timestamp what time you actually want to schedule for, so there's no way for AS to gracefully handle it. A valid timestamp needs to be passed in, or else an error should be triggered.
