### ISSUE TITLE
Ability to retry Non-repeating action

### ISSUE THREAD

**Issue by kc9ryt** [Prospress/action-scheduler#810]
Hello,

I looked through some of the past issues and couldn't find this answer so thought I would ask here. Is there a hook to have a Non-repeating action try to run itself again say in 1hr if the action fails/an exception is thrown? I am using action-scheduler to make requests to an api and when the api returns an error or if it is not available I would like it to automatically try again after some time.

Thanks!

**Comment by barryhughes** [comment]
Hi @kc9ryt,

Some work to support automated retries was started [(see here)](https://github.com/woocommerce/action-scheduler/pull/612) but isn't ready yet and may need some additional work.

In your particular case, though, would it be viable for your code to simply self-schedule a follow-up action to handle those occasions where the API you are consuming returns an error?

Semi-pseudo code:

```php
function my_callback() {
    $response = wp_remote_get( 'https://fetch-data.web' );

    if ( is_wp_error( $response ) ) {
        as_schedule_single_action( time() + MINUTE_IN_SECONDS, 'my_hook' );
        return;
    }

    // Other code
}
```
