### ISSUE TITLE
Question: Next Release ETA?

### ISSUE THREAD

**Issue by thomasplevy** [Prospress/action-scheduler#816]
My plugin, [LifterLMS](https://github.com/gocodebox/lifterlms) leverages this library, thank you thank you!

I've been following the PHP 8.1 related updates in the [3.4.1 Milestone](https://github.com/woocommerce/action-scheduler/milestone/20) and I'm curious when we might expect to see this released as a stable version I could upgrade to.

Thanks again, I'm a big fan of this lib and I'm grateful it exists for devs like myself to use :heart:

**Comment by barryhughes** [comment]
Hi @thomasplevy—that's great to hear! I don't have a specific date for 3.4.1 to offer you right at this moment, but it's on our radar :+1:

**Comment by thomasplevy** [comment]
Thanks @barryhughes

**Comment by barryhughes** [comment]
Circling back, [3.4.1 has been released](https://downloads.wordpress.org/plugin/action-scheduler.3.4.1.zip) (and [is tagged](https://github.com/woocommerce/action-scheduler/releases/tag/3.4.1) here in GitHub).

**Comment by thomasplevy** [comment]
Thanks @barryhughes <3
