### ISSUE TITLE
How to increase from 1 subscription rebill per minute

### ISSUE THREAD

**Issue by cwhockey31** [Prospress/action-scheduler#818]
Hi - I believe a developer added a script somewhere to limit subscriptions to 1 per minute but I can't find this script anywhere.  I recently setup a new server with an Apache/NGINX hybrid stack and would like to speed up our subscriptions rebills.  They all rebill on the same day and we have a few thousand that currently take 2-3 days to rebill.

Most of the developer's scripts were added to the functions.php file - is there anywhere else I should look?

Is there a script I can use that would override whatever they implemented to slow down subscription rebills?

The only script I can find related to action scheduler in the functions.php file is: 

//Added by CC date-9/10/2020 to remove the actionschedular error 
add_filter( 'action_scheduler_allow_async_request_runner', '__return_false' );

**Comment by cwhockey31** [comment]
After reading through most all  of the issues listed here on the action-scheduler GitHub - I can see most everyone is posting bugs or improvement suggestions.  I apologize for my inexperience as I'm not a developer but I understand the basics.  However, there's a few things in my research that I don't fully understand and do not want to increase limits or add concurrent queues without fully being confident that the changes won't mess something up.

I believe the new server has room for an increase in load and I can tweak the php-fpm settings if needed or increase the server's RAM from 16GB to 32GB.

Our subscription rebills started running today and will continue to run for another day and a half so if we make any changes we could see the improvement in real time.  Any help or insight is much appreciated.  Someone could delete this post if it doesn't belong here but I'm really looking forward to hearing suggestions and learning how to ramp up the processing of scheduled actions.

**Comment by barryhughes** [comment]
Hi @cwhockey31,

A good starting point could be the [Action Scheduler High Volume](https://github.com/woocommerce/action-scheduler-high-volume) plugin. This tweaks a few things to allow, for example, more actions to be processed in parallel. If you are not a developer, it's a straightforward way to make some reasonable changes.

Do note however that while this can facilitate increased throughput, it does not mean that scheduled actions will be processed ahead of time (so, it really is only useful if some % of your scheduled actions are being processed later than expected).

```php
//Added by CC date-9/10/2020 to remove the actionschedular error
add_filter( 'action_scheduler_allow_async_request_runner', '__return_false' );
```

↑ I assume this is needed to prevent a conflict of some kind, and that Action Scheduler is running via WP Cron or WP CLI. In that case, it's worth highlighting that you may also need to tweak the frequency with which those things run.

**Comment by cwhockey31** [comment]
Thanks for the quick response Barry.  The scheduled actions are backed up about 14 hours so I'll try adding the high volume plugin now that the website is on the new server.  I had it enabled on the last server and I didn't notice any difference in processing of scheduled actions... which makes me think a dev added a script somewhere that I can't locate.

And Action Scheduler is running via WP Cron every 1 minute... not sure if that's what is holding back the subscription rebills to 1 minute?  I would love to get WP CLI set up but similar to server side commands with Action Scheduler, I don't want to attempt to set something up where I only understand 70% of what I'm doing.  Changes to front-end code I can quickly revert... but mistakes on the server side make me nervous if I were not able to quickly undo them.  Maybe I'll get a new staging environment setup soon and test it out there.

**Comment by cwhockey31** [comment]
Oh awesome!  The high volume plugin worked and rebills are processing about 4 per minute now.  Thank you!!

**Comment by barryhughes** [comment]
Great!
