### ISSUE TITLE
When Action Scheduler runs, how to tell it not to process actions with a specific hook name?

### ISSUE THREAD

**Issue by skunkbad** [Prospress/action-scheduler#820]
I'd like to make it so Action Scheduler doesn't process actions with a specific hook name, "woocommerce_scheduled_subscription_payment".  This is part of the WooCommerce Subscriptions plugin. Can this be done?

**Comment by roykho** [comment]
Hi @skunkbad - thanks for opening the issue however this is a place for confirmed bugs only and not for support requests. I would suggest you post your question here instead https://wordpress.org/plugins/action-scheduler/

Thanks!
