### ISSUE TITLE
Incorrect version in the 3.4.1 tag

### ISSUE THREAD

**Issue by seredniy** [Prospress/action-scheduler#823]
Now in https://github.com/woocommerce/action-scheduler/tree/3.4.1, we have the `3.4.0` version declared. But the code is from 3.4.1.

https://github.com/woocommerce/action-scheduler/blob/9ce261d7055650331d6d433c03bf188e6dd2b259/action-scheduler.php#L8
 And other places (changelog, readme.txt etc)

Please, bump the version to `3.4.1`

**Comment by roykho** [comment]
@seredniy - thanks for reporting this. This should be resolved in `3.4.2` seen here https://github.com/woocommerce/action-scheduler/tree/3.4.2

We will also bump the version in WooCommerce for 6.6 release.

UPDATE: It will now go in 6.7 of WooCommerce release.
