### ISSUE TITLE
Support creation of unique actions

### ISSUE THREAD

**Issue by barryhughes** [Prospress/action-scheduler#828]
### The problem

The following snippet is a fairly common example of creating a recurring action, where at any given time we only want there to be *a single pending (or in progress) action of this type.* The idea is that this snippet can run during `init` on every request and, in ideal circumstances, duplicate actions will be prevented by the `as_has_scheduled_action()` check inside the callback:

```php
function eg_schedule_midnight_log() {
	if ( false === as_has_scheduled_action( 'eg_midnight_log' ) ) {
		as_schedule_recurring_action( strtotime( 'tomorrow' ), DAY_IN_SECONDS, 'eg_midnight_log' );
	}
}
add_action( 'init', 'eg_schedule_midnight_log' );
```

The above is, in fact, taken from [our own docs](https://actionscheduler.org/usage/) *[[source]](https://github.com/woocommerce/action-scheduler/blob/17250b493dc14bece2ae5f11b663227bb09efcef/docs/usage.md?plain=1#L106-L115)*. In practice, it falls a little short—because it's a race condition: two concurrent processes could each test for an existing action at approximately the same time, and both could go on to schedule a future action (causing duplication). Because of this, some users of the library adapt the above into the following form:

```php
function eg_schedule_midnight_log() {
	if ( false === as_has_scheduled_action( 'eg_midnight_log' ) ) {
		as_unschedule_all_actions( 'eg_midnight_log' );
		as_schedule_recurring_action( strtotime( 'tomorrow' ), DAY_IN_SECONDS, 'eg_midnight_log' );
	}
}
add_action( 'init', 'eg_schedule_midnight_log' );
```

This is still suboptimal, at best it narrows the race condition a little and prevents the excessive build-up of duplicates.

### Proposal

Introduce new public API functions or update our existing ones (implementation TBD) to support the creation of unique pending actions (in the sense that, only one pending action for the specified hook is allowed to exist). 

If we introduce new functions for this purpose, they could be closely modelled on our existing ones:

- `as_enqueue_unique_async_action( $hook, $args = array(), $group = '' )`
- `as_schedule_unique_cron_action( $timestamp, $schedule, $hook, $args = array(), $group = '' )`
- `as_schedule_unique_recurring_action( $timestamp, $interval_in_seconds, $hook, $args = array(), $group = '' )`
- `as_schedule_unique_single_action( $timestamp, $hook, $args = array(), $group = '' )`

Or, we could revise our existing functions and add an optional `$unique` param:

- `as_enqueue_async_action( $hook, $args = array(), $group = '', $unique = false )`
- `as_schedule_cron_action( $timestamp, $schedule, $hook, $args = array(), $group = '', $unique = false )`
- `as_schedule_recurring_action( $timestamp, $interval_in_seconds, $hook, $args = array(), $group = '', $unique = false )`
- `as_schedule_single_action( $timestamp, $hook, $args = array(), $group = '', $unique = false )`

This would remove the burden of enforcing uniqueness from the library consumer to the library itself, which can then develop an optimized means of meeting this need.

**Comment by bahiirwa** [comment]
Modification of the existing with the false default is a positive action for me in this case.

Thank you for tabling this.
