### ISSUE TITLE
Fatal error: plugins\woocommerce\packages\action-scheduler\classes\data-stores\ActionScheduler_DBStore.php on line 86

### ISSUE THREAD

**Issue by sathamcreator123** [Prospress/action-scheduler#829]
CAN YOU SOLVE THIS ISSUES

Uncaught RuntimeException: Error saving action: Table 'wordpress.wp_actionscheduler_actions' doesn't exist in F:\Wordpress Website Offline Sources\xamp new\htdocs\wordpress\wp-content\plugins\woocommerce\packages\action-scheduler\classes\data-stores\ActionScheduler_DBStore.php:86 Stack trace: #0 F:\Wordpress Website Offline Sources\xamp new\htdocs\wordpress\wp-content\plugins\woocommerce\packages\action-scheduler\classes\ActionScheduler_ActionFactory.php(177): ActionScheduler_DBStore->save_action(Object(ActionScheduler_Action)) #1 F:\Wordpress Website Offline Sources\xamp new\htdocs\wordpress\wp-content\plugins\woocommerce\packages\action-scheduler\classes\ActionScheduler_ActionFactory.php(105): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) #2 F:\Wordpress Website Offline Sources\xamp new\htdocs\wordpress\wp-content\plugins\woocommerce\packages\action-scheduler\functions.php(54): ActionScheduler_ActionFactory->recurring('woocommerce_cle...', Array, false, 86400, '') #3 F:\Wordpress Website Offline Sources\xamp new\htdocs\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-blocks\src\Domain\Services\DraftOrders.php(65): as_schedule_recurring_action(false, 86400, 'woocommerce_cle...') #4 F:\Wordpress Website Offline Sources\xamp new\htdocs\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-blocks\src\Domain\Services\DraftOrders.php(57): Automattic\WooCommerce\Blocks\Domain\Services\DraftOrders->maybe_create_cronjobs() #5 F:\Wordpress Website Offline Sources\xamp new\htdocs\wordpress\wp-includes\class-wp-hook.php(307): Automattic\WooCommerce\Blocks\Domain\Services\DraftOrders->install('') #6 F:\Wordpress Website Offline Sources\xamp new\htdocs\wordpress\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #7 F:\Wordpress Website Offline Sources\xamp new\htdocs\wordpress\wp-includes\plugin.php(476): WP_Hook->do_action(Array) #8 F:\Wordpress Website Offline Sources\xamp new\htdocs\wordpress\wp-admin\admin.php(175): do_action('admin_init') #9 F:\Wordpress Website Offline Sources\xamp new\htdocs\wordpress\wp-admin\plugins.php(10): require_once('F:\\Wordpress We...') #10 {main} thrown in F:\Wordpress Website Offline Sources\xamp new\htdocs\wordpress\wp-content\plugins\woocommerce\packages\action-scheduler\classes\data-stores\ActionScheduler_DBStore.php on line 86

**Comment by barryhughes** [comment]
I'm sorry you're encountering problems.

Unless all access to the admin environment is blocked by the error, you could try navigating to the **Tools ▸ Scheduled Actions** admin screen: this will automatically attempt to create any tables that might be missing and I would recommend trying this first of all.

If that does not work, you would need to create the missing tables manually. Some DDL statements for this can be found below (note you will need to update the database prefix from `wp_` to whatever you actually use on your site).

<details>
<summary>Table creation queries</summary>
<pre>
create table wp_actionscheduler_actions (
    action_id            bigint unsigned auto_increment primary key,
    hook                 varchar(191)                                  not null,
    status               varchar(20)                                   not null,
    scheduled_date_gmt   datetime        default '0000-00-00 00:00:00' null,
    scheduled_date_local datetime        default '0000-00-00 00:00:00' null,
    args                 varchar(191)                                  null,
    schedule             longtext                                      null,
    group_id             bigint unsigned default '0'                   not null,
    attempts             int             default 0                     not null,
    last_attempt_gmt     datetime        default '0000-00-00 00:00:00' null,
    last_attempt_local   datetime        default '0000-00-00 00:00:00' null,
    claim_id             bigint unsigned default '0'                   not null,
    extended_args        varchar(8000)                                 null
)
</pre>

<pre>
create table wp_actionscheduler_claims (
    claim_id         bigint unsigned auto_increment primary key,
    date_created_gmt datetime default '0000-00-00 00:00:00' null
)
</pre>

<pre>
create table mywc_actionscheduler_groups (
    group_id bigint unsigned auto_increment primary key,
    slug     varchar(255) not null
)
</pre>

<pre>
create table mywc_actionscheduler_logs (
    log_id         bigint unsigned auto_increment primary key,
    action_id      bigint unsigned                        not null,
    message        text                                   not null,
    log_date_gmt   datetime default '0000-00-00 00:00:00' null,
    log_date_local datetime default '0000-00-00 00:00:00' null
)
</pre>
</details>
