### ISSUE TITLE
how to pass argument

### ISSUE THREAD

**Issue by solucionesmipc** [Prospress/action-scheduler#83]
i have a file.php  in root wordpress installation   it works ok without arguments with your plugin

i have a file2.php in root wordpress installation it requieres argument "device=3000" to work

ex  file2.php?device=333333

i have tried with argument      device=333333  in argument box but not lucky

please help

luis

**Comment by thenbrent** [comment]
HI @solucionesmipc I'm not exactly sure what you're asking, but it sounds like the question is more a PHP related question than anything to do with Action Scheduler. Action Scheduler will schedule an action in WordPress. What you do on that action is entirely up to you. If you want to call a file, you can load it with `include()` or `require()`, just like any other code. If you want to pass the file being included an argument, you can just define it as a variable before including it, and it will be available within the scope of the file (again, that has nothing to do with Action Scheduler, its core PHP programming).

> ex file2.php?device=333333

That makes it sound like you want to pass a URL request parameter. That is only needed if you are calling the file via a HTTP request using something like `wp_remote_get()`.

I'm going to close this though as I don't think it has anything particularly relevant to Action Scheduler and instead is a request for basic PHP programming help (which isn't provided on this repository, though I hope the above does help point you in the right direction).
