### ISSUE TITLE
How to reliably execute async tasks without disabling wp cron

### ISSUE THREAD

**Issue by markgabinete** [Prospress/action-scheduler#832]
We have an issue with the default WP cron when it is not disabled scheduled actions does not run properly, but when we disable wp cron it runs smoothly.
How can we set this up so that we only use actionscheduler to handle all our tasks? We are using as_enqueue_async_action to schedule our tasks.
Thank you

**Comment by jorgeatorres** [comment]
Hi @markgabinete! 👋 

In order to debug this further, could you please share some more details about the issue with us? Like steps to replicate or some context on how many cron jobs/scheduled actions you have, their schedule, etc.

Thanks!

**Comment by markgabinete** [comment]
Thank you for your response.

Currently, the scheduled actions are dynamic, which are set via as_enqueue_async_action.
This initial function for example will generate batched async actions. set_batched_index_rebuild, will generate around 150 build_batched_index async actions.
It is working fine only when we disable wordpress default WP cron like this.

![download1](https://user-images.githubusercontent.com/184724/176182474-262568eb-03a6-40b0-b447-aa7ff00f6255.png)

When it is called via async request it works

![download2](https://user-images.githubusercontent.com/184724/176182517-a5d42134-22e8-4749-8a77-ee9658c98257.png)


But when it is called by wp-cron it does not execute the function it justs change the status of the action to complete.

Our workaround is to disable WP cron, but we don't want users to disable manually disable wp cron on their websites wp configs.
How can we reliably depend on the action scheduler without it not missing an action when we don't disable wp-cron?
We tried to add this (ActionScheduler::runner()->run('Async Request');) in the beginning of the build_batched_index function 
and enabled WP cron again. It seems to work for 10-20 actions and then the rest will be called by wp-cron and just don't execute the function.

Thank you

**Comment by barryhughes** [comment]
Can you provide some minimal sample code we can look a to try and replicate the problemt? 

One possibility is that the action is successfully triggered by Action Scheduler but, when running under WP Cron, the callbacks have not yet been registered when this happens (in other words, an order of operations issue). Prior to [this change](https://github.com/woocommerce/action-scheduler/pull/806) (which hasn't been released) that would result in the actions being set to complete even though no callbacks were triggered, which matches your description of events.

**Comment by markgabinete** [comment]
I think that is what happened, as it gets completed without any actions or any error_logs output(which I tried outputting text for testing)
This is a sample of our implementation:
//Register actions
    add_action( "initiate_batch_rebuild", [$this, "initiate_batch_rebuild"], 10);
    add_action( "set_batched_index_rebuild", [$thiset_batched_index_rebuild"], 10);
    add_action( "build_batched_index", [$this, "build_batched_index"], 10, 1);

    function initiate_batch_rebuild() {
        if ( true === as_has_scheduled_action( 'set_batched_index_rebuild' ) || true === as_has_scheduled_action( 'build_batched_index' )){
            as_unschedule_all_actions('set_batched_index_rebuild');
            as_unschedule_all_actions('build_batched_index');
        }
        as_enqueue_async_action("set_batched_index_rebuild");
    }

    function set_batched_index_rebuild(){
        ActionScheduler::runner()->run('Async Request');
        $start = microtime(true);
        $batch_size = 100;
        $post_batches = IndexAsset::getPosts();

        $batch_counter = 0;
        foreach ($post_batches as $index => $batch) {
            as_enqueue_async_action("build_batched_index", array(array("batched_data"=>$batch, "type"=>"post")));
            $batch_counter++;
        }

        $term_batches = IndexAsset::getTerms__premium_only();
        $batch_count += count($term_batches);

        foreach ($term_batches as $index => $batch) {
            as_enqueue_async_action("build_batched_index", array(array("batched_data"=>$batch, "type"=>"term")));
            $batch_counter++;
        }
    }
    
    function build_batched_index($data){
        ActionScheduler::runner()->run('Async Request');

        $index_builder = new IndexBuilder();
        $index_builder->buildBatchedIndex();
       
    }




Thank you

**Comment by barryhughes** [comment]
Can you tell me where that code lives/when it runs?

For instance, if the code responsible for registering those callbacks itself runs within an action (or is located within the theme, or something like that), perhaps it is running too late in some cases, such as when WordPress processes scheduled events.

**Comment by markgabinete** [comment]
It is inside a plugin I'm working on.
All the functions and the add_actions are registered in the plugin's core.
It is currently working actually, but it is only reliable when we disable wp cron.
For example: "initiate_batch_rebuild" is being called by updated_option hook when our settings are updated.

**Comment by barryhughes** [comment]
OK. There still probably isn't enough for us to replicate based on what you've shared. Consider this minimal plugin, though:

```php
<?php
/**
 * Plugin name: Test A/S and WP Cron
 * Description: Test running Action Scheduler under WP Cron.
 */

const TEST_HOOK = 'test-123';

add_action( 'init', function() {
	if ( ! function_exists( 'as_has_scheduled_action' ) ) {
		return;
	}

	if ( as_has_scheduled_action( TEST_HOOK ) ) {
		return;
	}

	as_schedule_recurring_action( time(), 30, TEST_HOOK );
} );

add_action( TEST_HOOK, function() {
	if ( ! defined( 'DOING_CRON' ) || ! DOING_CRON ) {
		return;
	}

	$cron_count_key = 'count_wpcron_' . TEST_HOOK;

	update_option(
		$cron_count_key,
		(int) get_option( $cron_count_key, 0 ) + 1
	);
} );
```

The idea is simple:

- On `init`, it creates a recurring scheduled action (unless it already exists).
- When the action is fired, the callback doesn't doing anything unless it is triggered in the context of WP Cron.
- It updates a counter each time this happens.

<img width="1461" alt="as-cron-test" src="https://user-images.githubusercontent.com/3594411/176247200-b18f3595-7fbf-45a3-a541-ae1b2f29a0d0.png">

☝🏽 This shows the first entries in the actions table. Note the log: the completed action was processed via WP Cron. I then ran `wp option get 'count_wpcron_test-123'` to get the value of the counter:

```sh
$ wp option get 'count_wpcron_test-123'
1
```

This indicates the callback really did run, else the value of the counter would be `0` or undefined. I then let things run for a little longer, so I had a mix of actions being completed via WP Cron, WP CLI and Async Request: the value of the counter again tallied perfectly with the number of instances completed under WP Cron.

---

So, I'm not exactly sure what is happening for you locally, but so far as I can tell this does not appear to be a bug in Action Scheduler.

**Comment by markgabinete** [comment]
Thank you for your support.
We will continue to double-check our code and let you know how it goes.

**Comment by markgabinete** [comment]
Thank you for your help we are able to resolve our issue.

**Comment by barryhughes** [comment]
Excellent, thanks for confirming and good luck with the project :+1:
