### ISSUE TITLE
as_schedule_recurring_action is drifting over time

### ISSUE THREAD

**Issue by skinnycat-software** [Prospress/action-scheduler#837]
I have a recurring cron set to run daily at 9pm CST. Crons are triggers by the OS cron using `wp action-scheduler run`, so I can verify that the cron ran at the expected time.

The site is set to CST timezone as well as the server.
I set up the recurring action like this:
`as_schedule_recurring_action( $cron_datetime, $cron_interval, 'some_name', array(), 'some_group' );`
where 
- $cron_datetime is the timestamp for the first occurence
- $cron_interval is 24 hours expressed in seconds

The first time, the crons run perfectly on schedule at 9PM CST but reschedule itself 2 hours earlier than the correct time at 7PM CST. The drift happens everyday. When using Wordpress Cron out of the box, the drift seems to be random and I thought this was due to the cron maybe not running at the expected time due to the low/no traffic on the site at that time. But now the crons are triggers by the OS cron and everything is triggered on time. I still have this issue. 
If I cancel the next run, the new one is created at the right time. So the creation of the first run is working great, but there is something going with the next scheduling after the cron has run.

I'm running WP 5.9.3 and Action Scheduler 3.4.0

Anyone else is running into a similar issue?

**Comment by barryhughes** [comment]
I'm sorry to hear you are running into difficulties. Some things we wondered initially:

- Is it possible the callbacks are taking a long time (several hours, for instance) to run (and do you see the same problem if you test with empty callback functions that return instantly)?
- Could you share the actual cron expression and interval value you are using?
- Can you share the system (server), PHP and WP timezone settings?

Thanks!

**Comment by skinnycat-software** [comment]
- Some callback are taking a long time but less than an hour. However I do have several cron and in particular, I do have one that runs every 5 min and can take more than 5 min to complete but definitively less than an hour. 
Some of the cron just run a simple update query and typically run in less than a minute. They also do drift over time. 
- I'm calling `as_schedule_recurring_action( $cron_datetime, $cron_interval, 'some_name', array(), 'some_group' );` where
$cron_datetime = 1660012200
$cron_interval = 86400

Server: timedatectl
      Local time: Mon 2022-08-08 15:47:01 CDT
  Universal time: Mon 2022-08-08 20:47:01 UTC
        RTC time: Mon 2022-08-08 20:47:01
       Time zone: America/Chicago (CDT, -0500)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: yes
 Last DST change: DST began at
                  Sun 2022-03-13 01:59:59 CST
                  Sun 2022-03-13 03:00:00 CDT
 Next DST change: DST ends (the clock jumps one hour backwards) at
                  Sun 2022-11-06 01:59:59 CDT
                  Sun 2022-11-06 01:00:00 CST


PHP: UTC Timezone (not set in php.ini, so using default)

WP: Chicago Timezone

I also noted that this is happening on my local Wordpress instance (Macbook pro)

I hope this helps

**Comment by barryhughes** [comment]
Thanks for those details! I've set up a test and will monitor to see how that unfolds.

**Comment by skinnycat-software** [comment]
I have been monitoring my server as well and this doesn't seem to be happening systematically. I can have 2-3 days where things are fine and then the drifting occurs. I wonder if there is a condition such as the job starting way after the scheduled start time because of a previous job still in progress or if at time the job itself takes too long to finish for some reason.

**Comment by barryhughes** [comment]
I think that's entirely possible, and I have had similar results so far: there is either no drift (best case) or marginal drift, which seems to depend on what else is ahead of the test action in the queue (because, the replacement action is scheduled after completion of the action currently being processed).

Would [`as_schedule_cron_action()`](https://actionscheduler.org/api/#function-reference--as_schedule_cron_action) be a viable alternative in your case? For instance, with:

```php
as_schedule_cron_action( time(), '0 */3 * * *', 'callback' );
```

Then, each time the scheduled action is processed, the next action ought to be scheduled for precisely 0 minutes past the next 3rd-hour-of-the-day (in my example). There is still the possibility that actions will not be processed on time, of course, but it ought to ensure the next action is scheduled strictly in accordance with the pattern you specify.

(I should also note, there are some [different challenges](https://github.com/woocommerce/action-scheduler/issues/765) you may encounter when using this approach.)

**Comment by skinnycat-software** [comment]
Yes `as_schedule_cron_action` should solve my problem (somehow I missed it that one). As the timezone is going to always be the same, worse case, I will have an hour difference due to daylight saving time and I can live with this. 
I understand better now why `as_schedule_recurring_action` is behaving the way it is. It is probably better suited for running more often (ie hourly or less) as drifting would them matter a lot less.
Thanks
