### ISSUE TITLE
as_enqueue_async_action shows error

### ISSUE THREAD

**Issue by alewolf** [Prospress/action-scheduler#839]
Checking in my WooCommerce extension if an action has already been scheduled using `as_has_scheduled_action` like this `as_has_scheduled_action('run_my_function')` shows the following error: 

```
Notice: Undefined property: wpdb::$actionscheduler_actions in /Users/install/dev/apps/wordpress/wp-includes/wp-db.php on line 740
WordPress database error: [Table 'wordpress.a' doesn't exist]
SELECT a.action_id FROM a WHERE 1=1 AND a.hook='run_my_function' AND a.status IN ('in-progress', 'pending') LIMIT 0, 1
```

**Comment by jorgeatorres** [comment]
Hi @alewolf,

Thanks for reaching out. Would you mind sharing a bit more about when this is happening? For example, when exactly are you calling `as_has_scheduled_action()`)? That is, during which WordPress action/filter (if any)? Also, some context such as Action Scheduler version might be useful here.

We think this issue might be related to invoking AS too early, before it has completed initialization.

Thanks!

**Comment by alewolf** [comment]
Hi @jorgeatorres 

Sure. 

I'm running it on the `woocommerce_init` hook. 

Also `as_enqueue_async_action` works just fine. It's only `as_has_scheduled_action` that provokes the error.

**Comment by barryhughes** [comment]
Thanks for the information, @alewolf.

We can replicate and will look at possible solutions. For now, can you run your code on a later hook such as `init` itself (at default priority `10` or higher)?

✍🏽 Note for when we pick this up: it appears that `woocommerce_init` is very early (`init:0`) and the corresponding code in Action Scheduler used to register its table names is not quite early enough (`init:1`).

**Comment by alewolf** [comment]
> For now, can you run your code on a later hook such as init itself (at default priority 10 or higher)?

Thanks, I already found a different workaround for now.
