### ISSUE TITLE
Action Scheduler: Release Process and Automations

### ISSUE THREAD

**Issue by barryhughes** [Prospress/action-scheduler#840]
When we release Action Scheduler, it would be great to have automations that update the following places:

- Any references to the current version number within `action-scheduler.php`, which contains 8 such references—all of which need to be bumped. With reference to the 3.4.0 release, you can see the relevant code on lines [8](https://github.com/woocommerce/action-scheduler/blob/3.4.0/action-scheduler.php#L8), [29](https://github.com/woocommerce/action-scheduler/blob/3.4.0/action-scheduler.php#L29), [36](https://github.com/woocommerce/action-scheduler/blob/3.4.0/action-scheduler.php#L36), [41](https://github.com/woocommerce/action-scheduler/blob/3.4.0/action-scheduler.php#L41), [43 (version string)](https://github.com/woocommerce/action-scheduler/blob/3.4.0/action-scheduler.php#L43), [43 (func name)](https://github.com/woocommerce/action-scheduler/blob/3.4.0/action-scheduler.php#L43), [49](https://github.com/woocommerce/action-scheduler/blob/3.4.0/action-scheduler.php#L49), and [61](https://github.com/woocommerce/action-scheduler/blob/3.4.0/action-scheduler.php#L61).
- Update the version field in `package.json`.
- Update the plugin version in `readme.txt` and also bump the `tested up to` field to whatever the current stable version of WordPress happens to be.
- Updates any `@since TBD` tags in our docblocks.

Since we strive to use SemVer, it is probably best that the development team takes care of indicating what the next version number should be (that way, we can revise it if necessary as we add and remove functionality through successive PR merges). What would the best way be for us to communicate this to the release team—for instance, we could manually update the version number in `package.json`, or else we could manage the next milestone number?
 
Internal links:

- p1656370445222829/1656368154.316829-slack-C025EHY377G
- p7bje6-4gR-p2

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/action-scheduler/pull/864
