### ISSUE TITLE
Question: How to make as_enqueue_async_action run in order?

### ISSUE THREAD

**Issue by markgabinete** [Prospress/action-scheduler#841]
For example this part:
![image](https://user-images.githubusercontent.com/60727346/185594235-e0c9d096-416f-4830-867a-a7b1dc5a6030.png)
The last one how to configure that it always runs last?
Thank you

**Comment by crstauf** [comment]
Instead of enqueueing the actions all at once, within each action you would enqueue the next. This means you have to pass along the values for the logic check, but that's the best way to ensure an order.

**Comment by markgabinete** [comment]
Ok, so there is a possibility that one could run first than the other this way right?
Thank you for confirming

**Comment by crstauf** [comment]
That's correct. The next action in the sequence isn't enqueued until the previous action completes, which ensures the proper order.
