### ISSUE TITLE
Feature Request : action_scheduler_lock_duration Filter for specific action groups 

### ISSUE THREAD

**Issue by markgabinete** [Prospress/action-scheduler#845]
I am writing this feature request as if possible there could be a filter for "action_scheduler_lock_duration" meaning we would be able to reduce the waiting time between the completed action and the next. By default, we see it set to 60 sec, and it already has a filter available. Still, as we see it, it will apply globally, which would also change the behavior of other plugins using the action scheduler.

If possible, to have a filter for action_scheduler_lock_duration and specify it to a specific action group so that whenever a plugin chooses to filter the duration, it would not affect the other plugin's scheduled actions. 
I see this would be very beneficial for plugins that have actions that have large batches of actions that are needed as soon as possible, take our plugin for example, building large batches of internal links and being able to complete the whole process as soon possible without disrupting the default behavior/schedule of the other plugin's actions.

Hoping you would consider adding in the near future, I think it would benefit other's projects as well.

Thank you

**Comment by barryhughes** [comment]
Related discussion [over here](https://github.com/woocommerce/action-scheduler/issues/842). Some key points:

- The hook `action_scheduler_lock_duration` already exists, and it can be used to change the duration of different lock-types.
- In practice, the only lock-type we currently use is `async-request-runner` and it exists to help stop HTTP requests (used to trigger queue runners) from being dispatched too frequently.

The existing lock implementation is pretty general purpose, and doesn't have any particular knowledge of how scheduled actions work—so I'm not sure the proposed change works well at that level. Might a better strategy here (for plugins that want to do this sort of thing) be to implement a custom queue runner, inheriting from `ActionScheduler_QueueRunner`, that:

- Uses a different lock (ie, `custom-prefix-async-request-runner`) which can then have a different default duration.
- Implements its own `do_batch()` method, so the claim can be adjusted to target a specific group (or other criteria).

We could also potentially modify `ActionScheduler_QueueRunner` to make it easier to subclass:

- Make the lock-type a class constant.
- Make the claim criteria overrideable, without overriding the entire `do_batch()` method.

**Comment by barryhughes** [comment]
Closed this since:

- As already covered, filtering the lock to change the delay on a group-by-group basis doesn't currently fit with the way things are architected.
- We have other [group-related enhancements in the pipeline](https://github.com/woocommerce/action-scheduler/issues/911).
