### ISSUE TITLE
Find out if is last task in queue using `as_next_scheduled_action`

### ISSUE THREAD

**Issue by mischnu** [Prospress/action-scheduler#848]
Hi there,

I have a bunch of one-time tasks tied to a callback. Within my callback function I want to know if this is the last run for this kind of task. How would I do this?

I tried using `as_next_scheduled_action( 'callback_name' )`, but during my testing this always returned `1` in any case if called within the in-progress callback. Is this meant to be like that? Couldn‘t find anything about this in the docs.

**Comment by barryhughes** [comment]
Hi @mischnu,

> I tried using as_next_scheduled_action( 'callback_name' ), but during my testing this always returned 1 in any case if called within the in-progress callback. Is this meant to be like that?

Sort of ... it should behave like this:

- If the next instance is in progress, it returns `(bool) true`.
- If the next instance is pending, it returns the timestamp as an integer.
- If there is no next instance, it returns `(bool) false`.

Possibly you are getting `(string) '1'` because you are implicitly casting the result (which would be `(bool) true` in this scenario) to a string. In any case, I'm not sure this function is ideal for your use case.

> Within my callback function I want to know if this is the last run for this kind of task. How would I do this?

Would something like the following work for you?

```php
// Within the callback for YOUR_HOOK:
$future_actions = ActionScheduler::store()->query_action( [
    'hook'   => 'YOUR_HOOK',
    'status' => ActionScheduler_Store::STATUS_PENDING,
] );

if ( ! $future_actions ) {
    // This is the last currently scheduled instance of YOUR_HOOK.
}
```

**Comment by mischnu** [comment]
Hi @barryhughes,

thank you so much, your code does exactly what I need!

I would suggest to add this case:

> If the next instance is in progress, it returns `(bool) true`.

… to the [API function reference](https://actionscheduler.org/api/#function-reference--as_next_scheduled_action), as this one is missing there somehow.

Once again, thanks!

**Comment by barryhughes** [comment]
> to the [API function reference](https://actionscheduler.org/api/#function-reference--as_next_scheduled_action), as this one is missing there somehow.

Thanks for flagging that: you're right, and it also appears it's being rendered a little weirdly (seems the return type is being transformed into a table, for some reason). I'll make a note to fix that up :+1:

**Comment by mischnu** [comment]
Just an idea: How about adding a fourth parameter (boolean) to exclude in-progress actions from the return value? Would be an easy way for the scenario described above. Default value could be `FALSE` to have backward compatibility.

That way it would also better match the function name 'next scheduled action' (IMHO there is no _next_ scheduled action when the last action is already running). 🤓

**Comment by barryhughes** [comment]
Yes, that would seem like a safe and reasonable change, and would make both functions (`as_has|next_scheduled_action()`) a little more flexible.
