### ISSUE TITLE
Update admin view to use data stores

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler#85]
When introducing the [admin view](https://github.com/Prospress/action-scheduler/blob/1.5.3/classes/ActionScheduler_AdminView.php) with SHA: cbe65a2bd, I leveraged WordPress's code for creating a list table for a custom post type. That was the quickest way to make an admin view available. However, that meant the admin view was tightly coupled to the built-in data store. One of the great design decisions of Action Scheduler was to abstract the data store.

Now that [highly scalable custom tables](https://github.com/Prospress/action-scheduler-custom-tables/) are coming to Action Scheduler, the core admin view needs to be updated to use the data store.

To this will require:

- [x] Create new [list table](https://www.sitepoint.com/using-wp_list_table-to-create-wordpress-admin-tables/) for scheduled actions which sources data from the data store/public APIs
- [x] Implement feature parity with the existing list table, including:
    - [x] Display the same columns and content
    - [x] **Filter** actions by _status_
    - [x] View log entries (the UI for this could be changed to provide a better UX, specifically by avoiding an additional page load just for a few rows of data. A JS popup opening the log in a lightbox like dialog would be better.)
    - [x] Display claim ID for actions with a claim (like `in-progress` or `completed` actions
    - [x] **Search** for scheduled actions by: hook name or arguments (like a subscription ID)
    - [x] **Sort** scheduled actions by hook name, scheduled, start or completed date, claim ID or number of log entries
    - [x] Allow actions to be _Run_ or _Trash_ed via the inline actions, e.g. https://cl.ly/0k011i0N1f3H
- [x] Move table to new tab under **WooCommerce > System Status** page rather than **Tools** menu, this wasn't previously possible with the way WC requires tabs to be setup, but it should be possible once we have our own list table. S#29  for background.

**Comment by crodas** [comment]
@thenbrent I did something generic in here which covers most things (and I'm planning on adding all features on Tricorder and in here).

I did a [generic library](https://github.com/Prospress/Tricorder/blob/7fb4cbf079a25aaf0bc8b3fb0a427093c5986a01/libraries/class-pp-list-table.php) which is [super easy to use](https://github.com/Prospress/Tricorder/blob/7fb4cbf079a25aaf0bc8b3fb0a427093c5986a01/src/class-tricorder-admin-table.php).  If this look like a good idea I will continue adding the last missing bit which is the filter by something else.

So far this generic library can do:

  * [X] Search (although this can be improved to produce a better SQL underneath)
  * [X] Bulk actions (and comes with the code for "delete" by default, although bulks are off by default) 
  * [X] Sorting by columns 
   * [X] Pagination
   * [X] Automatic translations of texts.
   * [ ] Filtering (I'm working on it now).

And the usage is quite simple, basically [just describing](https://github.com/Prospress/Tricorder/blob/7fb4cbf079a25aaf0bc8b3fb0a427093c5986a01/src/class-tricorder-admin-table.php#L8-L32) your table is enough but it is quite customisable.

**Comment by lkraav** [comment]
PS I recently discovered https://github.com/WP-API/new-list-tables perhaps fun to look at if you didn't know yet.

**Comment by crodas** [comment]
Interesting @lkraav, I will take a look at it.

**Comment by thenbrent** [comment]
@crodas I've created a new `1-6-dev` branch. Once you have a PR for this, please submit it against that branch instead of `master`.

**Comment by crodas** [comment]
> @crodas I've created a new 1-6-dev branch. Once you have a PR for this, please submit it against that branch instead of master.

I guess the correct branch should be against `custom_table`, right?
