### ISSUE TITLE
How can I fail the action-scheduler scheduled process during processing?

### ISSUE THREAD

**Issue by k-zafar** [Prospress/action-scheduler#850]
I want to set the status as fail of a process when any exception is raised in the call-back function. 

`try{
     //some code
  }catch (\Exception $e) {
        //here I need to end the process and set as failed
 }`

If any exception catch during the process, the action scheduler process must set as failed not as completed.

**Comment by barryhughes** [comment]
Hi @k-zafar,

If you throw the exception from your catch block (after you have done any clean-up, logging etc) then Action Scheduler should mark the action as failed.

**Comment by k-zafar** [comment]
Hi @barryhughes,

I try it as you guide me but the schedule process is still set as completed.

`try {
   //Some code and exceptions 
    } catch (\Exception $e) {
      throw new \Exception($e);
      }`

**Comment by barryhughes** [comment]
I'm not sure why you are seeing that result, but perhaps you could share more of your code? Here's what I set up:

```php
add_action( 'do_work', function () {
	try {
		perform_sub_task();
	} catch ( Exception $e ) {
		throw $e;
	}
} );

function perform_sub_task() {
	throw new Exception;
}
```

Then I enqueued a scheduled action via WP CLI (`wp eval "as_enqueue_async_action('do_work');"`) and waited until the next queue runner finished. On inspecting the list of scheduled actions, I could see that the action for `do_work` was marked as having failed.

What version of Action Scheduler are you using?

**Comment by k-zafar** [comment]
Hi @barryhughes 
It's done. The action scheduler schedule failed successfully. 

Thanks for the support
