### ISSUE TITLE
Is it possible to reschedule failed job?

### ISSUE THREAD

**Issue by k-zafar** [Prospress/action-scheduler#858]
Hi!
Can I re-schedule a failed job with new args? 
One more thing, Can I get the progress bar of any In-progress job by code?

Thanks

**Comment by barryhughes** [comment]
Hi @k-zafar,

> Can I re-schedule a failed job with new args?

We don't currently support retries as a feature (but see this [proposed change](https://github.com/woocommerce/action-scheduler/pull/612), which is on-hold). Generally speaking, though, there is no reason you cannot reschedule a replacement action. How and when to do this would depend on your specific use case.

> Can I get the progress bar of any In-progress job by code?

This is not directly supported: you would need to add this via your own code.

**Comment by k-zafar** [comment]
@barryhughes  Thanks for support
