### ISSUE TITLE
Using "action_scheduler_pastdue_actions_check_pre" causes PHP warnings

### ISSUE THREAD

**Issue by balazspiller** [Prospress/action-scheduler#865]
Using the following filter hook:

https://github.com/woocommerce/action-scheduler/blob/c2aaea225ac47d5654418223cbd4b0fdfc3910b5/classes/ActionScheduler_AdminView.php#L151

Returning a non-null, non-falsey value results in a PHP warning:

`Warning: Undefined variable $num_pastdue_actions in *****/action-scheduler/classes/ActionScheduler_AdminView.php on line 189`

This is happening because `$num_pastdue_actions` is defined **only if the filter is not in use**, but later in the code the variable is used regardless of the filter being used or not.

Can we have a fix for this? Thanks in advance.

**Comment by barryhughes** [comment]
I see the same: thank you for flagging. We'll address this in an upcoming release.

**Comment by iamankits** [comment]
The bug has still not been fixed. How much more time will it require to be fixed?

**Comment by barryhughes** [comment]
We consider this to be a low priority bug, and are focused on other areas right now. So, unfortunately, we cannot commit to a timeline. However, we would certainly be receptive to a PR from the community.
