### ISSUE TITLE
Documentation:  Object based / named parameters?

### ISSUE THREAD

**Issue by EliW** [Prospress/action-scheduler#867]
Hey there, on the documentation page here:   https://actionscheduler.org/admin/

It shows the parameters that are being saved as appearing to be an object and/or named parameters in general.  But the rest of the documentation for how to set up hooks and pass data, ends up causing numerically indexed parameters.  Which work, but are less useful when scanning:
<img width="1091" alt="Screen Shot 2022-10-07 at 5 43 55 PM" src="https://user-images.githubusercontent.com/1153183/194664153-bfd72ba5-1b22-4201-b812-09587f7216c8.png">

Is the documentation missing something and/or out of date?  Or am I missing something myself.   Thanks.

**Comment by barryhughes** [comment]
Hi @EliW,

Both are valid. It really depends on what is supplied when the action is scheduled:


```php
// Numerically indexed.
as_schedule_single_action( time(), 'abc', [ 'foo', 'bar' ] );

// Associative.
as_schedule_single_action( time(), 'abc', [ 'type' => 'foo', 'quality' => 'bar' ] );
```

Note also that named parameters will indeed mesh with PHP's named params functionality, so long of course as a suitable version of PHP is running.

**Comment by EliW** [comment]
Thanks @barryhughes !
