### ISSUE TITLE
Huge table size for wp_actionscheduler_logs

### ISSUE THREAD

**Issue by vasimevincedev** [Prospress/action-scheduler#869]
I have installed version of WooCommerce 7.0 and wp_actionscheduler_logs table too bigger.  

`
### WordPress Environment ###

WordPress address (URL): http://localhost/freshwp
Site address (URL): http://localhost/freshwp
WC Version: 7.0.0
REST API Version: ✔ 7.0.0
WC Blocks Version: ✔ 8.5.1
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.0.17
PHP Version: 8.0.17
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.76.1
OpenSSL/1.1.1m

SUHOSIN Installed: –
MySQL Version: 10.4.24-MariaDB
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: wp_
Total Database Size: 69.60MB
Database Data Size: 45.32MB
Database Index Size: 24.28MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.23MB + Index: 0.11MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.52MB + Index: 0.84MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_custom_options_plus: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_digital_dining: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_driver_delivery_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_driver_rejectorder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_driver_review: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_event_booking_enabled: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_event_booking_info: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_event_info: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_event_order_details: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_event_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 6.52MB + Index: 10.05MB + Engine InnoDB
wp_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_string_positions: Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 2.52MB + Index: 1.81MB + Engine InnoDB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.30MB + Index: 0.83MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.50MB + Index: 0.13MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 6.52MB + Index: 1.98MB + Engine InnoDB
wp_posts: Data: 3.52MB + Index: 0.61MB + Engine InnoDB
wp_product_restaurant: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_product_restaurant_branch: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_restaurant_amenity: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_restaurant_cuisines: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_restaurant_facilities: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_restaurant_gallery: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_restaurant_general_user_notification: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_restaurant_menu: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_restaurant_report: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_restaurant_sales: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_restaurant_user_specific_notification: Data: 0.27MB + Index: 0.08MB + Engine InnoDB
wp_review_to_driver: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_temp_digital_dining: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_user_login_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_visitor_ips: Data: 0.33MB + Index: 0.10MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.13MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.50MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.25MB + Index: 0.08MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.42MB + Index: 0.16MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.22MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 2526
clients: 1
custom_css: 2
customize_changeset: 1
elementor_library: 1
etance_zone_editor: 10
faq: 3
food-recipes: 10
home_banner: 7
location: 3
mc4wp-form: 3
nav_menu_item: 68
offer: 7
page: 50
post: 21
product: 71
restaurant: 1
revision: 356
shop_coupon: 4
shop_order: 3
viwec_template: 14
wooframework: 51
wp_block: 1
wp_global_styles: 2
wp_navigation: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (23) ###

Action Scheduler: by Automattic – 3.5.2
Remove Search from admin: by ITeam – 5.1.4
Aquila Admin Theme: by Guy Primavera – 3.1.1
Contact Form 7: by Takayuki Miyoshi – 5.6.3
Delivery Zone Manager: by ITeam – 1.0.1
Restaurant Driver Management: by ITeam – 5.1.1
Eatace Theme Kit: by ITeam – 5.1.1
Twillio : by John Smith – 1.10.3
Recipes: by ITeam – 5.1.4
WP Armour - Honeypot Anti Spam: by Dnesscarkey – 2.0.1
Restaurant Address Book: by ITeam – 5.1.1
Restaurant Bookmark Addon: by ITeam – 5.1.1
Restaurant Order Cancel Addon: by ITeam – 5.1.1
Restaurant Order Type Addon: by ITeam – 5.1.1
Restaurant Report: by ITeam – 5.1.1
Super Socializer: by Team Heateor – 7.13.36
UPI QR Code Payment Gateway: by Sayan Datta – 1.2.3
Payment Plugins Braintree For WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.2.37

Print Invoice & Delivery Notes for WooCommerce: by Tyche Softwares – 4.6.5
WooCommerce: by Automattic – 7.0.0
WP Mail SMTP: by WPForms – 3.5.1
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.6

Sequential Order Numbers for WooCommerce: by WebToffee – 1.4.8

### Inactive Plugins (22) ###

Advanced Product Fields for WooCommerce: by StudioWombat – 1.5.1
Paytm WooCommerce Payment Gateway: by Paytm – 2.7.0
Query Monitor: by John Blackbourn – 3.10.1
Restaurant Admin Pro: by ITeam – 5.1.2
Restaurant Bogo Coupons: by ITeam – 5.1.1
Restaurant Digital Dining: by ITeam – 5.1.1
Restaurant Event Booking: by ITeam – 5.1.1
Restaurant Management: by ITeam – 5.1.1
Restaurant Menu AddOns: by ITeam – 5.1.1
Restaurant Notification: by ITeam – 5.1.1
Restaurant POS System: by ITeam – 5.1.1
Restaurant Restricted Product Manager: by ITeam – 5.1.1
WooCommerce Square: by WooCommerce – 3.1.0 (update to version 3.2.0 is available)
WooCommerce Stripe Gateway: by WooCommerce – 6.5.1
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 3.3.3
WP All Import Pro: by Soflyy – 4.6.9
WPML All Import: by OnTheGoSystems – 2.3.0
WPML Multilingual CMS: by OnTheGoSystems – 4.5.8
WPML Sticky Links: by OnTheGoSystems – 1.5.4
WPML String Translation: by OnTheGoSystems – 3.2.1
WPML Translation Management: by OnTheGoSystems – 2.10.8
Yoast SEO: by Team Yoast – 19.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #152143 - /shop/
Cart: woocommerce/woocommerce-blocks#62 - /cart/
Checkout: woocommerce/woocommerce-blocks#63 - /checkout/
My account: #28585 - /my-account/
Terms and conditions: woocommerce/woocommerce-blocks#21 - /terms-and-conditions/

### Theme ###

Name: Storefront
Version: 4.1.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-10-13 08:45:18 +05:30
Options: ✔
Notes: 59
Onboarding: completed

### Action Scheduler ###

Complete: 11
Oldest: 2022-10-12 12:14:38 +0000
Newest: 2022-10-12 12:15:13 +0000

Failed: 1
Oldest: 2022-10-12 12:14:38 +0000
Newest: 2022-10-12 12:14:38 +0000

Pending: 1
Oldest: 2022-10-13 12:14:38 +0000
Newest: 2022-10-13 12:14:38 +0000

### Status report information ###

Generated at: 2022-10-12 17:49:48 +05:30
`
Fresh wp, WooCommerce and store front theme. Complete new setup still action called `wc-admin_import_orders` thousand of time. 

I would like remove schedular for the draftOrder status. I dont want to delete my order by schedular. 

As I check there is new release for action scheduler while WooCommerce still older version.

**Comment by barryhughes** [comment]
Hi @vasimevincedev,

If I am understanding you correctly, there are two actions in particular that are problematic (in that you are seeing a *lot* of these):

- `wc-admin_import_orders`
- `draftOrder` 

If that is correct, I would recommend:

- Creating an issue (or updating a suitable existing issue) on the [core WooCommerce issue tracker](https://github.com/woocommerce/woocommerce/issues) since the creation of `wc-admin_import_orders` happens via code in that plugin.
- Consider following [this issue](https://github.com/woocommerce/action-scheduler/issues/870) in the WooCommerce Blocks issue tracker. I'm not absolutely sure, based on the information you shared, but it sounds like this might be the source of the draft order issue you referenced.

**Comment by vasimevincedev** [comment]
Duplicate of #870
