### ISSUE TITLE
Action scheduler stops when machine is left idle

### ISSUE THREAD

**Issue by Sidsector9** [Prospress/action-scheduler#871]
When importing 2000+ products using WooCommerce Square on shared hosting servers, if the computer is left unattended for a long time, the import stops after 1.5k - 2k products.

**Note**: The products are already imported in batches.

To counter this, I added a `setInterval()` that reloads the page after each batch is imported. With this method, WooCommerce Square is able to import all 4000 products successfully.

The other way to solve this is by manually reloading the webpage every 20-30 seconds, that works as well.

However, this doesn't feel like the best strategy to solve this problem.

Is this something anyone has come across, or knows how to solve it? Any pointers would be greatly appreciated.

**Comment by barryhughes** [comment]
Hi @Sidsector9,

Action Scheduler essentially has the same limitation as [WP Cron](https://developer.wordpress.org/plugins/cron/) (in fact, by default, Action Scheduler actually makes use of and depends upon WP Cron) in that if there is no traffic, nothing will happen. 

Similarly, just as is the case with regular WordPress scheduled events, if this is problematic and you need to make sure that the queue is processed even when there is *no* traffic, the best strategy is to take advantage of a [system scheduler](https://developer.wordpress.org/plugins/cron/hooking-wp-cron-into-the-system-task-scheduler/).

**Comment by Sidsector9** [comment]
That makes sense. Thanks @barryhughes for explaining in such detail. I'll see what approach we can take so that we can pull all the data from Square.
