### ISSUE TITLE
Keep execute actions one by one as per the action queue

### ISSUE THREAD

**Issue by maheshwaghmare** [Prospress/action-scheduler#873]
![image](https://user-images.githubusercontent.com/4434582/196795846-bcb2d7f4-263b-43e4-bb1a-3276f23bac48.png)

| Action | Scheduled | Action Created | Action **Started** via WP Cron | Action **Complete** via WP Cron |
| ------------- | ------------- | ------------- | ------------- | ------------- | 
| Action 1 | Non-repeating 2022-10-19 17:50:51 +0000 (2 hours 25 minutes ago) | 2022-10-19 20:13:50 +0000 | 2022-10-19 20:14:03 +0000 | 2022-10-19 20:14:03 +0000 | 
| Action 2 | Non-repeating 2022-10-19 17:51:01 +0000 (2 hours 24 minutes ago) | 2022-10-19 20:13:50 +0000 | 2022-10-19 20:14:03 +0000 | 2022-10-19 20:14:03 +0000 |
| Action 3 | Non-repeating 2022-10-19 17:51:11 +0000 (2 hours 24 minutes ago) | 2022-10-19 20:13:50 +0000 | 2022-10-19 20:14:03 +0000 | 2022-10-19 20:14:03 +0000 |
| Action 4 | Non-repeating 2022-10-19 17:51:21 +0000 (2 hours 24 minutes ago) | 2022-10-19 20:13:50 +0000 | 2022-10-19 20:14:03 +0000 | 2022-10-19 20:14:04 +0000 | 

Above is the scheduled actions log.

All of these actions are completed successfully.

The issue is all the actions started and completed on same time.

Actions Scheduled in Unique timestamp with the 10+ seconds of difference.

E.g.

- Action 1 - Non-repeating 2022-10-19 17:50:51 +0000
- Action 2 - Non-repeating 2022-10-19 17:51:01 +0000 (after 10+ seconds)
- Action 3 - Non-repeating 2022-10-19 17:51:11 +0000 (after 10+ seconds)
- Action 4 - Non-repeating 2022-10-19 17:51:21 +0000 (after 10+ seconds)

All of these actions are created on SAME time which is **OK**.

- Action 1 | 2022-10-19 20:13:50 +0000 (same time)
- Action 2 | 2022-10-19 20:13:50 +0000 (same time)
- Action 3 | 2022-10-19 20:13:50 +0000 (same time)
- Action 4 | 2022-10-19 20:13:50 +0000 (same time)

But, The issue is some action started on the EXACT same time.

E.g.

- Action 1 | 2022-10-19 20:14:03 +0000 (same time)
- Action 2 | 2022-10-19 20:14:03 +0000 (same time)
- Action 3 | 2022-10-19 20:14:03 +0000 (same time)
- Action 4 | 2022-10-19 20:14:03 +0000 (same time)

Here, The issue is:

- I have schedule the API request which should not trigger on same time.
- If API trigger in exact time then the target server break the API call.
- To avoid this, I have scheduler the actions in 10+ seconds.

But, As WordPress Cron execute it trigger some actions on the EXACT time.

To avoid this, I have tried to use below filter:

```php
add_filter( 'action_scheduler_queue_runner_batch_size', function( $batch_size = 25 ) {
    return 1;
} );
```

But, This not works.

I have tried to find it in code level, and also searched on the https://actionscheduler.org/ but not getting the right information.

If this is a improvement then you may keep this issue open for the fix.

How to execute actions on EXACT scheduled time?

As WordPress not use Linux Cron, so, What should be the fix in this situation.

Is there any filter which execute the actions in the queue instead of parallel.

Maybe execute other actions in parallel but execute the actions from specific group into the queue to avoid such issues?

**Comment by barryhughes** [comment]
That's a tricky problem to solve because, at least if you rely on WP Cron alone, then queue runners will be spawned once every minute in the best case—but that is not *guaranteed.* There may also be other scheduled events ahead of Action Scheduler and, of course, once Action Scheduler starts to process the queue then speed with which things progress is dictated by how quickly each callback executes.

Given the problem you are trying to solve, though, I wonder if a recurring scheduled action (you would use the `as_schedule_recurring_action()` function to set these up) would be a better fit? This would at least enforce some sort of delay between individual calls to your callback function.

Would that work for you?

**Comment by barryhughes** [comment]
> As WordPress not use Linux Cron, so, What should be the fix in this situation.

Just to be clear, if you are unable to take advantage of a system scheduler (be that Linux Cron or a close equivalent), and are wholly dependent on web traffic to initiate WP Cron/Action Scheduler, things become much more unpredictable. This isn't really a problem that WordPress or Action Scheduler can solve by themselves.
