### ISSUE TITLE
Is there a way to delete an action directly? [REQUEST FOR INFO]

### ISSUE THREAD

**Issue by TomBallagh** [Prospress/action-scheduler#875]
Searching through the api docs, I can see 

as_unschedule_all_actions()

When i do this the actions technically still exist as ActionScheduler_CanceledAction, ideally i would like them gone completely, I can get in the DB to erase them but is there an api method to delete them? I can't find it.

Apologies if I haven't read the docs correctly.

**Comment by barryhughes** [comment]
Hi!

Though it's not listed in the public docs, it should be possible to do something like this:

```php
ActionScheduler_Store::instance()->delete_action( $action_id );
```

Does that work for you?

**Comment by TomBallagh** [comment]
Hi @barryhughes , thanks for the prompt reply and yea that worked for me, thanks!
