### ISSUE TITLE
[REQUEST FOR INFO] - Cannot get events to fire without ALTERNATE_WP_CRON

### ISSUE THREAD

**Issue by TomBallagh** [Prospress/action-scheduler#876]
Hi, currently, all my events will sit in pending unless i define( 'ALTERNATE_WP_CRON, true );

Ideally I think this is not something I should be doing I think? I've checked the issues / docs and tried to define the actions in all sorts of places but can't get around the issue(is it an issue do I have to do this? Not sure).

When I go into the action scheduler admin controller and manually run the events they run correctly, it's the timestamp they are not triggering on.

Thanks in advance for any help, but yea, events just sit in pending until I define the alternate cron.

**Comment by barryhughes** [comment]
Hi @tomball123,

There are essentially four ways in which scheduled actions run:

- Manually (through the admin UI) ... and it sounds like this is working
- Via WP CLI (which I appreciate may not be available, depending on where you host your website)
- Via the WordPress scheduled events API (let's just refer to that as WP Cron)
- Through async HTTP requests created by Action Scheduler itself

WP Cron itself can be triggered in various different ways, but the default method is by spawning async HTTP requests. If that doesn't work in your environment (and the fact that you need to define `ALTERNATE_WP_CRON` suggests it does not) then Action Scheduler will be similarly unable to spawn its own async requests and, assuming WP CLI is not available to you, it will depend on you finding some other way to run WP Cron.

In this case, it sounds like `ALTERNATE_WP_CRON` is your solution. If you are unhappy with that for any reason, though, you would need to work with your hosting provider to figure out why that is needed, and/or investigate further alternatives (like directly invoking things via the command line, or via the system scheduler).

Please don't hesitate to let me know if I can clarify any of the above.

**Comment by TomBallagh** [comment]
Thanks again @barryhughes , it's pretty clear from what you're saying that this will be a thing for us to solve not you guys!

Closing because it's not an Action Scheduler issue, thanks for clarity.
