### ISSUE TITLE
Fatal Error Uncaught RuntimeException: Error saving action

### ISSUE THREAD

**Issue by mguoPA** [Prospress/action-scheduler#884]
Hi,

I am getting the following errors which results in my whole website crashed. 

Fatal error: Uncaught RuntimeException: Error saving action: Error saving action: Database is limited in /home/customer/www/mysite/public_html/wp-content/plugins/woocommerce-/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44.

on the debug log it seems the query cannot be written to the ActionScheduler file. I tried to update the wordpress to lastest version and this errors has stopped me to do so.

**Comment by barryhughes** [comment]
Hi @mguoPA,

Sorry to hear you are facing difficulties. We don't recognize the specific 'database is limited' error, unfortunately. Some questions/information to gather:

- Do you know which version of Action Scheduler are you using?
- Do you know if the expected database tables (such as `wp_actionscheduler_actions`) are already present?
- Are you able to share the version of MySQL or MariaDB you are using (you host may be able to help you with this information)?
- Can you check with the host if you might have reached a limit in terms of allowed database size, or similar?

Thanks!

**Comment by barryhughes** [comment]
Closing, as we would need more information to figure out if this is a bug within Action Scheduler or a conflict. Feel free to open a fresh issue if you wish to re-visit this. Thanks!
