### ISSUE TITLE
Fatal error when using version 3.5.3 with MariaDB

### ISSUE THREAD

**Issue by BronsonQuick** [Prospress/action-scheduler#887]
Hey folks,

Firstly, thanks for maintaining this plugin. I often use it on a lot of client sites!

I recently upgraded a site that's hosted on WordPress VIP which uses MariaDB and the upgrade causes a fatal error. Version 3.5.2 works as expected. We're using PHP 8.0.25 and WP 6.0.3. I believe the issue is coming from this [logic](https://github.com/woocommerce/action-scheduler/blob/trunk/classes/data-stores/ActionScheduler_DBStore.php#L398) as it appears to be returning `null`.

I haven't had a chance to spin up a local installation that's using MariaDB yet so I haven't bug into a fix but I thought I should open an issue now in case anyone else happens to hit this issue. Here's a few supporting screenshots for additional information:

![image](https://user-images.githubusercontent.com/1377956/202049889-41c938ac-c575-44d4-b8be-cf4f895a95d3.png)
<img width="848" alt="Site_health__Info__KEEPUP__WordPress_2022-11-16_09-48-58" src="https://user-images.githubusercontent.com/1377956/202049913-0e79f67a-796b-4a8d-9d72-f53e3a06ae0d.png">
<img width="814" alt="Site_health__Info__KEEPUP__WordPress_2022-11-16_09-56-06" src="https://user-images.githubusercontent.com/1377956/202049936-acb406ec-85e1-468d-a724-71cc5d103776.png">
<img width="836" alt="Site_health__Info__KEEPUP__WordPress_2022-11-16_09-55-25" src="https://user-images.githubusercontent.com/1377956/202049952-f3097f2a-2832-44cd-a78b-0186e0493da0.png">

If I find some time in the next couple of weeks I'll try and spin up a local install with MariaDB and Xdebug setup so I can try and get a patch written for it.

**Comment by peterfabian** [comment]
Thanks for reporting! Based on the error reported, it seems like `wpdb` is missing the database handle. Looking at the code, that should be initialized from wp-settings.php quite early on during `require_wp_db()` which constructs the `wpdb` instance... (or it was unassigned on db disconnect). Either way, a strange error, please keep us posted!

**Comment by WPprodigy** [comment]
When on hyperdb (which VIP is), this explains what is happening: https://github.com/Automattic/HyperDB/pull/114.

**Comment by BronsonQuick-APL** [comment]
@WPprodigy Thanks for fixing that upstream in HyperDB! 🙏  I'm happy for this to be closed seeing that was the source of this issue.

**Comment by peterfabian** [comment]
Thanks for reporting the findings back!
