### ISSUE TITLE
Multisite compatibility

### ISSUE THREAD

**Issue by mikey242** [Prospress/action-scheduler#888]
Hello,

I am soon looking to deploy ActionScheduler in a plugin on a multisite environment, and was just wondering if there has been any change on support for this before getting started. Any advice you can offer on this would also be great.

**Comment by mikey242** [comment]
Just to update this question, it looks like someone has created a plugin which adds additional tables when a site is created in multisite.
https://github.com/rankmath/_repair-action-scheduler-multisite

**Comment by jorgeatorres** [comment]
Hi @mikey242!

Thanks for reaching out. [Per our FAQ](https://actionscheduler.org/faq/#how-does-action-scheduler-work-on-wordpress-multisite), AS doesn't explicitly include any special support for multisite, but it should work on each individual site if a plugin on the sub-site is using it.

Can you provide more details on what you were expecting here or what you'd like to see?
Is AS breaking something for you a MU setup?

Please let us know!
