### ISSUE TITLE
Not safe to process an action if the "in-progress" status update fails

### ISSUE THREAD

**Issue by WPprodigy** [Prospress/action-scheduler#896]
The `log_execution()` db store method doesn't throw an error if the update fails: https://github.com/woocommerce/action-scheduler/blob/trunk/classes/data-stores/ActionScheduler_DBStore.php#L989-L996

Logic inside of `process_action()` and throughout the plugin really depend on actions having their status updated to `in-progress`. Otherwise, some of the checks and balances fall apart and it's possible for the same action to be processed twice if you are running an action whilst its status is still `pending`.

One of the safest ways to ensure concurrency is working as intended would be to run a query like:

 ```
 UPDATE wp_actionscheduler_actions SET status = 'in-progress' WHERE action_id = 123 AND status = 'pending':
 ```
 
 If it passes, your thread has won any sort of race and is the sole owner of this action. If it fails though, the thread is not safe to proceed because another may have won.
 
 ___
 
 As an aside, it may be smart to retry the query if it failed due to a deadlock here:
 
 ```
$result = $wpdb->query( $sql );
if ( false !== strpos( $wpdb->last_error, 'Deadlock found' ) ) {
  // Try query again. 
}
```

**Comment by jorgeatorres** [comment]
Hi @WPprodigy!

This is a good catch. Thanks for reaching out! We're discussing the best way to approach the fix for this, but in any case, we're marking this as a high priority bug in the meantime.

Thanks again!
