### ISSUE TITLE
`as_has_scheduled_action()` returns true for currently running single event

### ISSUE THREAD

**Issue by BrianHenryIE** [Prospress/action-scheduler#903]
Let's say I schedule an event (in my case, [a payment update check](https://github.com/BrianHenryIE/bh-wc-bitcoin-gateway/blob/950f7e2df6ebd7ed25510463f257f1114559c9e2/src/woocommerce/class-bitcoin-gateway.php#L306-L313)):

`as_schedule_single_action( $timestamp, $hook, $args );`

While it is running, I want to [conditionally reschedule it](https://github.com/BrianHenryIE/bh-wc-bitcoin-gateway/blob/950f7e2df6ebd7ed25510463f257f1114559c9e2/src/action-scheduler/class-background-jobs.php#L87-L90), but only if there is no future event for it already scheduled.

`as_has_scheduled_action()` returns `true` when checking for the the same job with the same arguments, but the action it has identified is the currently running action, not an action that is scheduled for the future. It is an action that is scheduled for the past but has not finished running.

I dove in a bit and got the currently running `action_id`:

```php
$action_id = null;
if ( doing_action( 'action_scheduler_run_queue' ) ) {
  $backtrace = debug_backtrace( DEBUG_BACKTRACE_PROVIDE_OBJECT, 6 );
  foreach ( $backtrace as $frame ) {
    if ( isset( $frame['class'] ) &&
      ActionScheduler_Abstract_QueueRunner::class === $frame['class']
      && isset( $frame['function'] )
      && 'process_action' === $frame['function']
      && isset( $frame['args'] ) ) {
      $action_id = $frame['args'][0];
      break;
    }
  }
}
```

And the `action_id` of the event being found by `as_has_scheduled_action()`:

```php
$query_args = array( 'hook' => $hook, 'args' => $args );
$action_id = ActionScheduler::store()->query_action( $query_args );
```

And they are the same.

i.e.`as_has_scheduled_action()` returns true for currently running single event.

Expected: `as_has_scheduled_action()` should check the time of the event is in the future (the currently running on is presumably a few seconds past).

Desirable: It would be useful to be able to find the `action_id` of the currently running action (see also: https://github.com/woocommerce/action-scheduler/issues/733). Then I could check ~ `as_has_scheduled_action() && $action_id !== $current_action_id)`. I also want to log the currently running action.

Or maybe I'm not fully considering the mechanics of Action Scheduler's retries etc. and there is a more appropriate way. E.g. should I create a recurring event and cancel that recurring event when I get the result I want? (can I have multiple recurring events on the same hook with different arguments?!).

**Comment by coreymckrill** [comment]
Hey @BrianHenryIE, what about using `as_get_scheduled_action` and specifying `'status' => ActionScheduler_Store::STATUS_PENDING`? Is there a reason that wouldn't work in this case?

**Comment by BrianHenryIE** [comment]
Thank you Cory. That is a nice simple solution I should've figured out myself!
