### ISSUE TITLE
Properly kick-off action-scheduler queue handling

### ISSUE THREAD

**Issue by StSaens** [Prospress/action-scheduler#906]
Hi,
I've looked through the documentation site a lot, but alas.

I'm using the code below to sync stock across 2 sites. 
I've noticed that when I do a stock change there's a difference in performance in the wp-admin side of things. 

I'm using a custom screen to make stock changes across products.
When I trigger a change it gives me a green flash to inform me stock has been properly set.

Using spawn_cron() the stock change is almost instantly set. (on the source site ofc.)
Using do_action( 'action_scheduler_run_queue', ''); there's a delay (~1 sec).

To test further if the syncStockAction is properly async I put a sleep(10) in there.
Using spawn_cron() the UI informs me almost instantly that stock has been properly set on the source side. And at the same time I'm seeing the job in the background working to sync the stock status to the other site.
Using the other option it oviously is delayed by 10sec.

So I'm most likely not kicking off the action-scheduler in the proper manner for a proper async handling of the queue. But am struggling to find out why.

`add_action('woocommerce_variation_set_stock', 'cronSyncStock');`
`function cronSyncStock($product) {`
`	as_enqueue_async_action( 'syncStockAction', array( $product->get_id() ) );`
`	spawn_cron();`
`	//if( as_has_scheduled_action('syncStockAction') ) {`
`	//	do_action( 'action_scheduler_run_queue', '');`
`	//}`
`}`

`add_action( 'syncStockAction', 'syncStock', 10, 1 );`
`function syncStock( $productId ) {`
	`// do REST calls etc.`
`}`

**Comment by rrennick** [comment]
> Using spawn_cron() the stock change is almost instantly set. (on the source site ofc.)

[`spawn_cron`](https://developer.wordpress.org/reference/functions/spawn_cron/) spins up a separate worker thread. The current thread does not wait for that process to run/complete.

> Using do_action( 'action_scheduler_run_queue', ''); there's a delay (~1 sec).

Doing the sync this way pauses the current thread while the sync processes. If you are going to do the sync inline, it would be simpler to just run the sync directly:

```
add_action('woocommerce_variation_set_stock', 'syncStockAction');
```

Assuming you don't have a backlog of pending actions and you have not disabled the async runner, the async action created by your snippet should run as soon as your dashboard request is complete. If you have disabled the async runner then the `spawn_cron` call should accomplish the same thing.

**Comment by StSaens** [comment]
Thanks for your quick response.

> [spawn_cron](https://developer.wordpress.org/reference/functions/spawn_cron/) spins up a separate worker thread. The current thread does not wait for that process to run/complete.

Is `spawn_cron` the proper and fastest way to inititialize action-scheduler to run the queue in a seperate worker thread?

**Comment by rrennick** [comment]
> Is spawn_cron the proper and fastest way to inititialize action-scheduler to run the queue in a seperate worker thread?

Unless you have disabled the async runner for some other reason, I'd recommend letting the async runner process the action. Cron is only going to process the action if the action scheduler task is the next scheduled cron task and the AS async runner is not currently running. If either of those conditions are not met then the async runner will process it at the end of the current thread anyway.

Added note: The AS async runner runs in a separate thread.

**Comment by StSaens** [comment]
Thanks! Case closed.
