### ISSUE TITLE
Name of statuses in filters does not display translated

### ISSUE THREAD

**Issue by DAnn2012** [Prospress/action-scheduler#919]
In the list table, the name of statuses in filters does not display translated, as does the "All" element:

![action-scheduler](https://user-images.githubusercontent.com/1197819/222089471-4b9a2af7-7998-4c20-98a9-82190a4c8706.png)

I think the list is generated by this line:

https://github.com/woocommerce/action-scheduler/blob/833f3bde9dac71d78559a756670fd329151fc47b/classes/abstracts/ActionScheduler_Abstract_ListTable.php#L693

Thanks.

**Comment by barryhughes** [comment]
Thanks for reporting. You're right, it seems we're formatting the status slug instead of using the translated status label.
