### ISSUE TITLE
Is there a GUI add-on that would easily allow showing calendars ?

### ISSUE THREAD

**Issue by crouti** [Prospress/action-scheduler#93]
Hi and thanks for this great job!
Is there a GUI add-on that would easily allow showing calendars based on scheduled events ?
My goal is to use this plugin to create per-user calendars for appointements i would create with the available API. Each WP user could be able to manage its own appointments calendar, moving time slots and cancelling them, changing the scheduled tasks accordingly ?
Thanks a lot for your help

**Comment by thenbrent** [comment]
@crouti there is no GUI for adding a calendar.

This only UI we provide the crude administration UI, as see here: https://github.com/Prospress/action-scheduler#managing-scheduled-actions

> My goal is to use this plugin to create per-user calendars for appointements i would create

The main purpose of this library is to provide a scalable action/hook scheduling system to allow 3rd party code to run large queues or batches of code with WordPress/WooCommerce.

That's quite a different thing to user calendars/appointments, so I'm not sure how suitable this library would be for that. Other plugins specifically for that purpose are likely a better option to start with.

**Comment by crouti** [comment]
Thanks for your answer. Don't you think i could integrate your library with a calendar view (like https://fullcalendar.io/) in order to create a customizable appointment system ? An apointement is an event, but mostly a few scheduled actions in order to notify each part of the meeting, no?
If you know any open-source library for managing apointments and calendar, thanks for sharing.

**Comment by thenbrent** [comment]
> Don't you think i could integrate your library with a calendar view (like https://fullcalendar.io/) in order to create a customizable appointment system ? 

Yes, you could definitely do that. It's not what Action Scheduler is designed to do, but there's not reason it's not clearly unsuitable for that tasks. It's just likely there are better options. Though I don't know much about the appointments and calendar space so can't recommend them.
