### ISSUE TITLE
Run many queues with different actions

### ISSUE THREAD

**Issue by lucas-barbosa** [Prospress/action-scheduler#933]
Is it possible to start many queues at once (I've been using Action Scheduler High Volume for it) but with different action groups? Simply put, I'd like to start a queue with the group 'A' actions; another queue with the group 'B' actions, and so on.

**Comment by barryhughes** [comment]
Hi @lucas-barbosa,

If you are able to take advantage of [WP CLI](https://make.wordpress.org/cli/) then you could set up multiple queue runners [targeting specific groups](https://actionscheduler.org/wp-cli/):

```sh
wp action-scheduler run --group=abc
```

Though you are already using the high volume plugin, which takes care of this, you may wish to refer to the documentation regarding increasing the [allowed number of concurrent batches](https://actionscheduler.org/perf/#increasing-concurrent-batches).
