### ISSUE TITLE
Action Scheduler Action is missing.

### ISSUE THREAD

**Issue by herng77** [Prospress/action-scheduler#934]
Wrote a short script to test out the new version of action scheduler 3.5.4.

I write a small function inside, whenever it is processed, it will write to log once.
as_enqueue_async_action()

tried to call the code 10 times, but its like 70% of the schedules are missing.

I tried this after $result = as_enqueue_async_action();

and notice there are random 0 being returned, and when 0 shows ,the schedule is not recorded.

am I doing something wrong here? It is working perfectly fine on the previous AS

**Comment by rrennick** [comment]
@herng77 Can you provide us with the code snippet to help us reproduce the issue?

**Comment by herng77** [comment]
```php
function test_as() {

        $time = time();
        $result = as_enqueue_async_action( 'test', array( $time ), 'auto_top_up' ,10,1);

        wp_send_json($result);

}

add_action('test','test');
function test(){

    sleep(1);

   // LOAD THE WC LOGGER
   $logger = wc_get_logger();
    
   // LOG THE FAILED ORDER TO CUSTOM "failed-orders" LOG
   $logger->info( wc_print_r( time(), true ), array( 'source' => 'as-orders' ) );

}
```


It is something like this


Edit:

Just tried with the previous package: V: 3.4.2

Run the function 100 times, 100% of the time it returns me a claim id.

**Comment by rrennick** [comment]
@herng77 Are you running that inside of another hook? If not, you need to have it run in the `init` hook with a priority of `10` or later.

Edit to add: This function call may be contributing to your issue as well. [See the docs](https://actionscheduler.org/api/)

```
as_enqueue_async_action( 'test', array( $time ), 'auto_top_up' ,10,1);
```

**Comment by herng77** [comment]
I am using a button to invoke this function to run. Code is exactly similar, just package difference but the new package of action scheduler is not working.

**Comment by herng77** [comment]
Any help?

**Comment by vedanshujain** [comment]
hey, @herng77 , seems like the last param you added in `as_enqueue_async_action` sets the `unique` flag to true. This is a new param that AS now supports, if you don't send it your action will always be scheduled. See the documentation for `unique` here: https://actionscheduler.org/api/

Let me know if this answers your question. I am closing this issue for repo maintenance, but feel free to respond back if you have any further question and we will re-open.
