### ISSUE TITLE
Queue Runner error - wp_cache_flush_routine called incorrectly

### ISSUE THREAD

**Issue by DaveWP** [Prospress/action-scheduler#941]
Hi

There is an unprotected call to wp_cache_flush_routine in clear_caches method which results in a PHP Notice error in Wordpress 6.1.0 installations where in-memory caching is not supported.

`[15-Apr-2023 11:42:20 UTC] PHP Notice:  Function wp_cache_flush_runtime was called <strong>incorrectly</strong>. Your object cache implementation does not support flushing the in-memory runtime cache. Please see <a href="https://wordpress.org/documentation/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.1.0.) in /var/www/web/wp-includes/functions.php on line 5865`

Propose line is replaced with:

`		$memory_caching=(`
`                    function_exists( 'wp_cache_flush_runtime' ) ?`
`                        wp_cache_supports('flush_runtime') :`
`                        false);`
`                if ( $memory_caching ) {`

**Comment by barryhughes** [comment]
Thanks, @DaveWP. This was [reported earlier](https://github.com/woocommerce/action-scheduler/issues/909), and a [fix has been merged](https://github.com/woocommerce/action-scheduler/pull/915) (which will go out in the next release).

**Comment by steffen25** [comment]
Hi @barryhughes 

I was looking into this error and can see this has been fixed - very nice.
However Woocommerce is locked to 3.5.4 as I see it. https://github.com/woocommerce/woocommerce/blob/7.7.2/plugins/woocommerce/composer.json#L23
Any chance this will get bumped in the near future?

**Comment by barryhughes** [comment]
Hi @steffen25,

Yes, it is likely to be updated following the release of Action Scheduler 3.6.1. In the meantime, installing the standalone version of [Action Scheduler](https://wordpress.org/plugins/action-scheduler/) will allow you to utilize the latest stable version of the library.

**Comment by steffen25** [comment]
> Hi @steffen25,
> 
> Yes, it is likely to be updated following the release of Action Scheduler 3.6.1. In the meantime, installing the standalone version of [Action Scheduler](https://wordpress.org/plugins/action-scheduler/) will allow you to utilize the latest stable version of the library.

Thank you for a quick reply.
Do I need to tell it to use the separate plugin or how will Woocommerce know which one to use? 
Im a big fan of trusting the source and not mess around with separate versions of the bundled plugins to make it easier to maintain in the future. Im updating a old code base...
I guess the version in Woocommerce is locked for a reason or?

**Comment by barryhughes** [comment]
> Do I need to tell it to use the separate plugin or how will Woocommerce know which one to use?

Short answer: it will "know".

It's possible for several versions of Action Scheduler to co-exist (for instance, you might have 10 plugins active of which 3 contain a copy of Action Scheduler and one is the standalone Action Scheduler plugin itself). The way this is resolved, in simple terms, is that each copy of Action Scheduler registers itself and its version number, then the instance with the highest version number is the one that becomes active.

So, if you install Action Scheduler 3.6.0 (standalone), that will take precedence over the version currently included in WooCommerce. No further configuration should be needed.

> I guess the version in Woocommerce is locked for a reason or?

We were being cautious. One of our teams detected the [problem described here](https://github.com/woocommerce/action-scheduler/issues/951) and, though it seems it may be pretty low impact (in fact, might not even occur, depending on how the library is being used), the timing of the bug discovery meant we erred on the side of caution and did not ship the update within WooCommerce.
