### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by erwanregnier** [Prospress/action-scheduler#943]
Hi,
Some important changes have been added to the trunk since the last [release](https://github.com/woocommerce/action-scheduler/releases) (the WP CLI clean command is the one I was looking  for), is there a reason why the last release available doesn't match the main branch? Is a new version release planned soon?
It's quite confusing because the doc mentions these features but they're not included in the last release and so a few WP plugins using it (like Rank Math plugin) doesn't embed them.

thanks

**Comment by barryhughes** [comment]
Hi @erwanregnier—that's great feedback. 

We are trying to contain other changes to the documentation in a feature branch until the next release ships [(example)](https://github.com/woocommerce/action-scheduler/pull/938) but, yes, one or two items may have slipped through which isn't ideal. We'll definitely aim to do better going forward.

> Is there a reason why the last release available doesn't match the main branch? Is a new version release planned soon?

For this project, the main branch is often ahead of the published release (similar to WooCommerce). A new release is indeed planned soon—I don't have a precise release date to offer up but it's coming :-)

Sorry for the delay, and thank you for reaching out.

**Comment by barryhughes** [comment]
Closing, as we have now released [3.6.0](https://github.com/woocommerce/action-scheduler/releases/tag/3.6.0).
