### ISSUE TITLE
Fatal error: Uncaught Exception: Error saving action: Table _data.wp_actionscheduler_actions' doesn't exist 

### ISSUE THREAD

**Issue by Lorenzo83-bit** [Prospress/action-scheduler#955]
Hello. I have this issue:  Fatal error: Uncaught Exception: Error saving action: Table '_data.wp_actionscheduler_actions' doesn't exist. It happened after i deleted all the database files of action scheduler, but the plug-in was already cancelled from my site. Now i cannot enter into the dashboard, when i try page told me this issues:
in /home/lamore/domains/*****.com/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 118

Call stack:

ActionScheduler_DBStore::save_action_to_db()
wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:62
ActionScheduler_DBStore::save_action()
wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php:244
ActionScheduler_ActionFactory::store()
wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php:151
ActionScheduler_ActionFactory::recurring_unique()
wp-content/plugins/woocommerce/packages/action-scheduler/functions.php:122
as_schedule_recurring_action()
wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Domain/Services/DraftOrders.php:65
Automattic\W\B\D\S\DraftOrders::maybe_create_cronjobs()
wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Domain/Services/DraftOrders.php:57
Automattic\W\B\D\S\DraftOrders::install()
wp-includes/class-wp-hook.php:308
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:332
WP_Hook::do_action()
wp-includes/plugin.php:517
do_action()
wp-admin/admin.php:175
require_once()
wp-admin/index.php:10

How can i do? I made a backup witth totalupkeep but i cannot restore from website. Can you help me how to restore this backup manually and how to fixthe issues? Thank you.

**Comment by barryhughes** [comment]
I think this is essentially the same problem documented in the following issues:

- https://github.com/woocommerce/woocommerce/issues/34497
- https://github.com/woocommerce/action-scheduler/issues/856

Some possible courses of action: 

- You could recreate the missing tables manually, using a tool like [phpMyAdmin](https://www.phpmyadmin.net/) (see also [this page](https://github.com/woocommerce/action-scheduler/wiki/Schema-Definitions) for table definitions).
- You could temporarily disable WooCommerce by renaming the plugin directory name (ie, to `__woocommerce`). This should allow you to access the WordPress dashboard, from which you can either install the latest version of Action Scheduler, to trigger a rebuild of the missing tables, or take advantage of your database backup (then, restore the original name of the WooCommerce plugin directory and re-activate it).

**Comment by Lorenzo83-bit** [comment]
Thank you Barry. I choose the simpler way, changing the name of woocommerce folder. Now i resolved everything. This was really helpful, you deserve all my gratitude. Kind regards!!

**Comment by barryhughes** [comment]
I'm glad we could help; sorry you had to go through that. I'll close this issue now—but the issues I linked to earlier are still open so we can think about ways of guarding against this scenario in the future.
