### ISSUE TITLE
Cron don't start the associated function

### ISSUE THREAD

**Issue by alexmaiazalox** [Prospress/action-scheduler#962]
I have a cron that is initialized with this code:

```
function wc_sync_create_cronjobs() {
    if ( function_exists( 'wc_sync_products' ) && false === as_next_scheduled_action( 'cron_wc_sync_products_main' ) ) {
        // Start time in Unix timestamp
        as_schedule_recurring_action( 1687215600, 172800, 'cron_wc_sync_products_main', );
    }
}
add_action( 'init', 'wc_sync_create_cronjobs' );
```

Until where is ok, it creates the cron and it was pending until the date; when start the cron the function associated is not running. This is the code:

```
function wc_sync_products() {

    error_log( 'WC SYNC ERROR - Star Cron => ' . date( 'Y-m-d H:i:s' ) );
 
   // the rest of the code goes where...

}
add_action( 'cron_wc_sync_products_main', 'wc_sync_products' );
```

The cron don't get to that error_log, so the function don't start and the cron is mark as failed and I get this log:
2023-06-20 08:21:40 +0000
acción creada
2023-06-20 08:21:41 +0000
acción empezada vía WP Cron
2023-06-20 08:27:26 +0000
acción marcada como fallida después de 300 segundos. Se ha producido un error desconocido. Revisa los registros de errores del servidor, de PHP y de la base de datos para diagnosticar el motivo.

I check the php log from the server and theres nothing there ... 

What can i do to fix this?

Thanks.

**Comment by barryhughes** [comment]
Unfortunately, there isn't really enough data to figure out why this is happening. If I put both your snippets together, into a single plugin file, a recurring action is created and successfully executed:

<div align="center"><img width="900" alt="test-962" src="https://github.com/woocommerce/action-scheduler/assets/3594411/8c31bcbb-a30f-40ba-9602-e3b65ec26b2d"></div>

Some information that may be helpful:

- What version of Action Scheduler are you using?
- What is the maximum allowed execution time for PHP in your environment (if you are not sure, you may wish to work with your web host to figure this out)?
- Can you replicate on a new WordPress site, with no other plugins running except for the latest version of Action Scheduler and a minimal version of your code?
- If you wait until the action is pending, then run it manually (via the **Tools ▸ Scheduled Actions** admin screen), does it work successfully then?
- Do you have any other actions (whether created by your code, or by another plugin) and are those working as expected?

Thanks!
