### ISSUE TITLE
Past due actions more then 17 lac

### ISSUE THREAD

**Issue by SabeelMansoof** [Prospress/action-scheduler#965]
Past due actions more then 17 lac, It slows down may website's dashboard, what can i do to faster it or handle these action scheduler?

**Comment by barryhughes** [comment]
Hi @SabeelMansoof,

[:link: FAQ: My site has past-due actions, what can I do?](https://actionscheduler.org/faq/#my-site-has-past-due-actions-what-can-i-do)

These are often nothing to worry about and will either clear with time or else you can visit the **Tools ▸ Scheduled Actions** screen and run the past-due actions manually, to help clear the blockage.

If however it *continues* to happen, then there may be a problem with the way your site is configured (and, if this is the case, you may also find that WP Cron is not running as expected).

[This plugin](https://wordpress.org/plugins/wp-crontrol/) may be useful if you want to check if WP Cron is running successfully. If it is not, you should probably start by resolving that problem, perhaps by working with your web host.

I hope that helps!

**Comment by SabeelMansoof** [comment]
Can i empty the table “wp_actionschedular_actions” as a whole from database? Is there will be any effect on my site? because after doing this all actions will be empty form database and site will load faster. So give me suggestion about this.

**Comment by SabeelMansoof** [comment]
I empty this table "wp_actionschedular_actions”in databse, now my site's backend is working faster. Issue resolved

**Comment by SabeelMansoof** [comment]
I empty this table "wp_actionschedular_actions”in databse, now my site's backend is working faster. Issue resolved
