### ISSUE TITLE
Cron reschedule event error for hook: action_scheduler_run_queue

### ISSUE THREAD

**Issue by akashhyap** [Prospress/action-scheduler#968]
Hi,

Please check the following log:

[04-Jul-2023 11:02:22 UTC] Cron reschedule event error for hook: action_scheduler_run_queue, Error code: invalid_schedule, Error message: Event schedule does not exist., Data: {"schedule":"every_minute","args":["WP Cron"],"interval":60}

WordPress:  Version 6.2.2 
WooCommerce: Version 7.7.0

I am building a Headless WooCommerce store using Next.js and WPGraphql. 

All the plugins get deactivated everyday around 11:02:22 UTC and I get this error log on debug.log

Has anyone faced anything like this before? 

Can someone please help me to figure out the issue or at least the possible solutions for this?

Thank you.

**Comment by barryhughes** [comment]
Hi @akashhyap,

WordPress natively supports 4 different cron schedules:

- `hourly`
- `twicedaily`
- `daily`
- `weekly`

Action Scheduler registers a 5th, called `every_minute`. Action Scheduler needs to be loaded for this to work but, if you deactivate every plugin, that won't be the case.

So, given the situation you have described, the error is expected and is probably something you can safely ignore—unless you find it is leading to other problems?

**Comment by akashhyap** [comment]
Hello @barryhughes,

Thank you for the reply. 

Actually like I mentioned earlier all the other plugins get deactivated automatically whenever WordPress logs this error. I have to manually activate all the plugins again to run the store. Is there a way to avoid or bypass this error as it won't be ideal for a live ecommerce site getting crashed everyday around 11:02:22 UTC.

**Comment by barryhughes** [comment]
I'm sorry, I misread your original message: so you mean, this error is *causing* all of your plugins to be deactivated? 

That's rather unusual, and I assume you are using a plugin or service that causes this (WordPress, by itself, will not deactivate all plugins on encountering an error of this kind). What plugins are you using, and can you replicate the same thing on a test site where only Action Scheduler is running and nothing else (or, in this case, where only WooCommerce is running)?

[woocommerce.com/document/woocommerce-self-service-guide](https://woocommerce.com/document/woocommerce-self-service-guide/)

The above guide describes how to test for plugin and theme conflicts, would you be able to give that a try?

**Comment by barryhughes** [comment]
Based on the information you have shared so far, it's most likely that something else (not WooCommerce, and not Action Scheduler) is deactivating the plugins on your site. That in turn leads to the error you cited.

**Comment by akashhyap** [comment]
I think it has something to do with WPGraphql. When I deactivated it, everything was fine. I have reached out to them now.

Thanks again Barry.

**Comment by barryhughes** [comment]
Welcome: I'll go ahead and close this issue, but of course if it resurfaces, or if specific problems in Action Scheduler are identified after speaking to that team, please don't hesitate to create new issues as needed 👍🏼
