### ISSUE TITLE
wp_actionscheduler_actions' doesn't exist.

### ISSUE THREAD

**Issue by ruicruzpt** [Prospress/action-scheduler#982]
Hello,

I am having an issue where the plugin does not see a table. I have created a blank WordPress site and copy the tables and struture to the main site, but it still does not see that it's there.

CLI. 
[root@server public_html]#  wp --allow-root action-scheduler run
Error: There was an error running the action scheduler: Unable to claim actions. Database error: Table 'ruicruz_blog.wp_actionscheduler_actions' doesn't exist.
[root@server public_html]#

wp-admin.
It justs says that tasks are pending, the message do not disappear: 
Action Scheduler migration in progress. The list of scheduled actions may be incomplete.

Also I've seen this thread https://github.com/woocommerce/action-scheduler/issues/534 and there are no conflicts.

**Comment by barryhughes** [comment]
1. Can you try visiting the **Tools ▸ Scheduled Actions** admin screen? This may trigger the creation of the necessary tables.
2. If you have access to [WP CLI](https://wp-cli.org/), can you try running the following command?

```sh
wp action-scheduler fix-schema
```

**Comment by ruicruzpt** [comment]
Hello,
Visiting the page has no effect.

CLI command.
[root@server public_html]# wp --allow-root action-scheduler fix-schema
Success: Registered schema for ActionScheduler_LoggerSchema
Success: Registered schema for ActionScheduler_StoreSchema
[root@server public_html]# wp --allow-root action-scheduler run
Error: There was an error running the action scheduler: Unable to claim actions. Database error: Table 'ruicruz_blog.wp_actionscheduler_actions' doesn't exist.


However, the databases *are* presents in phpMyAdmin.

**Comment by barryhughes** [comment]
Definitely a little puzzling. Do you have any other databases besides `ruicruz_blog` (could it be that we're connecting to different databases depending on the context of the request)? 

Is there any other information that might be useful to us (are you operating a multisite installation, or using HyperDB, etc)?

**Comment by ruicruzpt** [comment]
Hello,

Nothing special about this, not even a multisite, permissions on MySQL are fine, so I am also confused. The only thing I can remember that could make an impact, or not, is that the site is running since 2010 so it's quite an old database from the 2.x version of WordPress, being updated regularly. Apart from that, no idea on anything special from my end.

I did install a fresh WordPress and the plugin, so this is not something from the server, just this particular installation, the new installation works as expected.

**Comment by barryhughes** [comment]
Could some custom code, or code in another plugin be interfering? That might explain why it cannot be replicated outside of this particular site.

**Comment by ruicruzpt** [comment]
Hello,

I eventually fixed the issue - sorry for not posting earlier.

The solution was to create some random actions in a test site and import the tables to the old one. My previous atempt was to import a blank table after installation, without any records on it.

Sorry for not having much details, hopefully this was something that will never happen again to anyone. :)

**Comment by barryhughes** [comment]
No problem, glad you solved it and thank you for sharing this note :+1:
