### ISSUE TITLE
Incorrect Argument Count

### ISSUE THREAD

**Issue by aaronware** [Prospress/action-scheduler#989]
I have a scheduled event that is failing and it's saying the amount of arguments is incorrect. However, the arg count listed is correct.

action shopify_app_update_order_status

status Failed

args
```php
[
0 => 79, 
1 => 19164, 
2 => 'DE-52145',
3 => 'https://internal.packagetracking.dev?shipmentid=6817B21A-5196-4A9F-8C04-576C9215CA98',
]
``` 

Non-repeating | 2023-09-14 13:28:08 +0000(24 seconds ago) | 2023-09-14 13:28:08 +0000
action created2023-09-14 13:28:18 +0000
action started via Async Request2023-09-14 13:28:19 +0000

action failed via Async Request: 4 arguments are required, 3 given

Strangely, 4 arguments are being passed and no errors within the debug log. I was wondering if it has something to do with needing to escape the URL possibly?

```php
	/**
	 * Update the order status of any queued orders
	 *
	 * @param int $integration_id The Post ID of the Integration
	 * @param int $post_id The Post ID of the order
	 * @param string $order_number The PO Number from Shopify/ERP
	 * @param string $tracking_link The tracking link
	 *
	 * @return void
	 */
	public function update_order_status( $integration_id, $post_id, $order_number = '', $tracking_link = '' ) {
```

**Comment by aaronware** [comment]
I also just tried escaping the url in case it was some sort of formatting w/ `wp_json_encode`

"https%3A%2F%2Finternal.packagetracking.dev%3Fshipmentid%3D3114E14D-8BF5-414C-9229-B9BACAD05FC7"

**Comment by aaronware** [comment]
Here is the original single action being registered

```php
							as_schedule_single_action(
								time(),
								"shopify_app_update_order_status",
								[
									$integration_id,
									$post_id,
									$order_number,
									$tracking_link ?? '', // add default if empty, try to catch AS failure
 								],
								'order_status'
							);
```

**Comment by aaronware** [comment]
This is not related to https://github.com/woocommerce/action-scheduler/issues/798. I am declaring 4 args when registering the hook for the action

**Comment by aaronware** [comment]
`add_action( "shopify_app_update_order_status", [ __CLASS__, 'update_order_status' ], 10, 4 );`

**Comment by barryhughes** [comment]
Hi @aaronware,

I can't seem to replicate. Here's what I tried:

```php
add_action( 'init', 'register_989' );
add_action( 'as-989', 'do_something_989', 10, 4 );

function register_989() {
	as_schedule_single_action( time(), 'as-989', [ 'apple', 'banana', 'cat', 'dog' ], 'group', true );
}

function do_something_989( $a, $b, $c, $d ) {
	error_log( "$a $b $c $d" );
}
```

Using `trunk` and no other plugins, this is fine: the action runs successfully. Are you sure this is not a conflict, or can you provide me with a snippet that would let me replicate using just WordPress and Action Scheduler without any other plugins being present?

**Comment by aaronware** [comment]
Hey @barryhughes I just wanted to close the loop on this so if anyone comes across this issue. This issue was actually due to some of our logging. Our codebase utilizes `sprintf()`. In our scenario. it was only passing 2 variables when the string within the sprintf actually had 3 placeholders resulting in the cryptic error. The challenge was that the error displayed wasn't related to the scheduled action itself, but it was a function that was being used within it. The strange thing is that there was nothing in the debug log regarding it
