### ISSUE TITLE
wp cron spawn not wanted

### ISSUE THREAD

**Issue by Basiglio** [Prospress/action-scheduler#991]
Hello there,
i deactivated the wp-cron from the wp-config file via define('DISABLE_WP_CRON', true); 
and activated the reading of the wp-cron.php file through the server by setting it to 2 minutes

I then inserted a scheduled action using the action scheduler plugin, everything runs correctly if the scheduled action is handled by "action started via Async Request" but it can happen that the action is scheduled by "action started via WP Cron", this causing my scheduled action to no longer run correctly and get fatal for low memory on wp-includes files. how can i do?

I expect the scheduled action to always be executed by action started via Async Request

**Comment by barryhughes** [comment]
Hi @Basiglio,

You could hook into the `action_scheduler_init` action and then do any of (or a combination of) the following:

- [Unschedule](https://developer.wordpress.org/reference/functions/wp_unschedule_event/) [`action_scheduler_run_queue`](https://github.com/woocommerce/action-scheduler/blob/3.6.3/classes/ActionScheduler_QueueRunner.php#L7).
- Remove the [queue runner's callback](https://github.com/woocommerce/action-scheduler/blob/3.6.3/classes/ActionScheduler_QueueRunner.php#L69) from the `action_scheduler_run_queue` hook.
- Less ideal, set up a filter for `option_cron` and remove the queue runner that way.

**Comment by lsinger** [comment]
There has been no further activity on this issue and it seems to me like the question was answered. I'll close this issue for now. Please feel free to reopen if your question was not answered.
