### ISSUE TITLE
Fatal error on ActionFactory class

### ISSUE THREAD

**Issue by kermage** [Prospress/action-scheduler#999]
![wp-mail-smtp](https://github.com/woocommerce/action-scheduler/assets/8350223/a455b7ba-d4f7-4232-90a5-c54514c7377a)

![seo-by-rank-math](https://github.com/woocommerce/action-scheduler/assets/8350223/bdd101a2-579d-4c7f-959d-df6b1ddea265)

Plugin | Version
--- | ---
[cardanopress-governance](https://github.com/CardanoPress/plugin-governance/blob/cb84e406f65faf0a7bff1148184164ec6372c0bc/cardanopress-governance.php#L35) | 3.5.3
[wp-mail-smtp](https://github.com/awesomemotive/WP-Mail-SMTP/blob/3dbe933e8a527f6ad202096afcec7013addd0137/src/Core.php#L857) | 3.6.1
[seo-by-rank-math](https://github.com/rankmath/seo-by-rank-math/blob/5acf665a91ae87f2a64ead498e3fe6e773be33c2/rank-math.php#L258) | 3.6.3

There seems to be an issue with loading the right class which should be from the latest version.

From what I can tell, the [functions.php](https://github.com/woocommerce/action-scheduler/blob/754dc005b82a858c6398f1d0799d41771e2f5779/functions.php#L94) file loaded was of the 3.6+ version but the [action factory](https://github.com/woocommerce/action-scheduler/blob/754dc005b82a858c6398f1d0799d41771e2f5779/classes/abstracts/ActionScheduler.php#L17) used was from the older 3.5 version which does not have the `create` method

**Comment by Konamiman** [comment]
For whoever at Automattic picks this:

- Useful info: p7bje6-3wM-p2
- Please make the above information public, maybe by converting it to a post in the WooCommerce developer blog (and then add a link here: https://actionscheduler.org/faq/).

**Comment by pbwebdev** [comment]
Are there any work arounds for this issue?

**Comment by jorgeatorres** [comment]
Hi @pbwebdev!

We're still looking into ways to address this, as it's a bit of an edge case. Our suggestion for now would be to make sure that you're running up to date plugins, so that their dependencies (Action Scheduler in particular) are also up to date. If any of your plugins is using an old version of Action Scheduler, nudging the developers so that they update their copy of AS will certainly help.

**Comment by barryhughes** [comment]
> From what I can tell, the [functions.php](https://github.com/woocommerce/action-scheduler/blob/754dc005b82a858c6398f1d0799d41771e2f5779/functions.php#L94) file loaded was of the 3.6+ version but the [action factory](https://github.com/woocommerce/action-scheduler/blob/754dc005b82a858c6398f1d0799d41771e2f5779/classes/abstracts/ActionScheduler.php#L17) used was from the older 3.5 version which does not have the create method

The root of this seems to be the use of [Jetpack Autoloader with a static classmap](https://plugins.trac.wordpress.org/browser/cardanopress-governance/tags/1.1.0/dependencies/vendor/composer/jetpack_autoload_classmap.php) from within Cardanopress Governance, which contains all of the Action Scheduler classes.

In situations like this one, that will 'subvert' Action Scheduler's own version resolution procedure and potentially cause an intermixing of classes from different versions—which, of course, if the problem we're facing here.

@kermage are you one of the developers of that plugin? Can you exclude Action Scheduler from the static classmap?

**Comment by barryhughes** [comment]
...In the meantime, some other ideas that may solve this:

- Install and activate the latest version of [Action Scheduler](https://wordpress.org/plugins/action-scheduler/) (ie, as a standalone plugin).
- Or, if that doesn't work, move it to the `mu-plugins` directory.

The principle being if we can get the latest version of Action Scheduler (and, importantly, its class loader) to be first, we might solve the problem that way.

**Comment by barryhughes** [comment]
Closing, as it's essentially beyond our control if other products load Action Scheduler in a way that isn't recommended.
